<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_informeMatricula_selectCiclo</name>
   <tag></tag>
   <elementGuidId>3f995025-4878-4b60-919a-a3a11ca0084f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ciclo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ciclo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ciclo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c3a2f8ef-1fb5-4a1d-8a55-957605a184b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ciclo</value>
      <webElementGuid>689665ec-28c8-4912-a2fd-37a23fa37b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CargarNiveles();</value>
      <webElementGuid>53301030-68fc-4f62-9f22-fc215416da1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Todos 
                     Pre-Básica
                     Básica
                     Media
                </value>
      <webElementGuid>95bf39be-0454-4152-ad38-cae0d52eda59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ciclo&quot;)</value>
      <webElementGuid>2e6a74b6-163f-42aa-a4e7-f50845e446ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ciclo']</value>
      <webElementGuid>fe738b79-1683-4c57-969a-668a2bcb9f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr/td[4]/select</value>
      <webElementGuid>626b23cd-62a1-481f-ae49-57ebca802222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo :'])[1]/following::select[1]</value>
      <webElementGuid>0305f812-42a9-42ef-bdfc-3970df6cfdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año del proceso :'])[1]/following::select[2]</value>
      <webElementGuid>cc1bd950-4b41-475f-8d81-708439af8f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel :'])[1]/preceding::select[1]</value>
      <webElementGuid>3317dfbe-2a4d-452f-a7bd-d9c3da7a6fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso :'])[1]/preceding::select[2]</value>
      <webElementGuid>7feac976-9928-47c9-81aa-b3caf6fe79cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>38d2ef69-36a0-4667-8fc7-1363fbfc7a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ciclo' and (text() = '
                     Todos 
                     Pre-Básica
                     Básica
                     Media
                ' or . = '
                     Todos 
                     Pre-Básica
                     Básica
                     Media
                ')]</value>
      <webElementGuid>96db6ad9-6e79-452a-ad17-a61ee042d4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
