<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_informeMatricula_selectCalidad</name>
   <tag></tag>
   <elementGuidId>310a510b-208e-41d0-b82f-af7a2fdc68d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='calidad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calidad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#calidad</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>55482cac-9818-4b3f-a25f-9ca7cb9ce823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calidad</value>
      <webElementGuid>d0b6dfca-c47a-4cd5-862c-aaa1905f83e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CargarGrillaMatriculas()</value>
      <webElementGuid>03179f3a-8a95-4411-9678-86426b43f7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Todos
                    Prioritario
                    Preferente
                    Vulnerable
                </value>
      <webElementGuid>ce5f9d51-6126-4ae7-a872-2e436d9d1b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calidad&quot;)</value>
      <webElementGuid>1f247cd8-8f2f-4847-be86-752b3fbc3476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='calidad']</value>
      <webElementGuid>edeaa65a-b5f7-426b-a9c5-2abbec245869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr[3]/td[6]/select</value>
      <webElementGuid>858f9e2b-d1c1-4a6a-895e-787d93863b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calidad alumno/a:'])[1]/following::select[1]</value>
      <webElementGuid>388ddf7c-a59c-47cc-884a-8160a3e7adf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código enseñanza:'])[1]/following::select[2]</value>
      <webElementGuid>1c484dbf-a967-4369-ab8e-d6d06af68c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumno'])[1]/preceding::select[1]</value>
      <webElementGuid>f0a90447-ed20-4760-8259-ce3b663fd992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apoderado'])[1]/preceding::select[1]</value>
      <webElementGuid>4b947919-87eb-4a80-804e-ee09c986cbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/select</value>
      <webElementGuid>474d23f4-baea-4e13-bc0f-f5058ca65150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'calidad' and (text() = '
                    Todos
                    Prioritario
                    Preferente
                    Vulnerable
                ' or . = '
                    Todos
                    Prioritario
                    Preferente
                    Vulnerable
                ')]</value>
      <webElementGuid>ea050333-1287-4470-8a97-2125f7c9b474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
