<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_informeMatricula_selectAnio</name>
   <tag></tag>
   <elementGuidId>510fbba4-3f90-4b86-a626-6ab42d8c78e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='anio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#anio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9e71ab8d-4d08-4be8-905c-d884b59ca01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anio</value>
      <webElementGuid>2d52ce9f-840c-48ae-85e2-f97eeeb68ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anio</value>
      <webElementGuid>8c1d59b6-1c1c-415b-a0c0-5bc547cde2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CargarNiveles();</value>
      <webElementGuid>b145dd7c-d443-4eb2-abc2-b3afe067702b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             2025
                                                 2024
                                                 2023
                                                 2022
                                                 2020
                                                 2019
                                                 2018
                                                 2017
                                                 2016
                                                 2015
                                                 2014
                                                 2013
                                        </value>
      <webElementGuid>30d0868c-e30a-4d4d-8b73-fdb3e33fd215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anio&quot;)</value>
      <webElementGuid>89f0d902-dc5c-462d-8849-54e9012ea7cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='anio']</value>
      <webElementGuid>ccdc382c-c7f1-431d-8452-fccd547283ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>99193799-2c1b-4b2b-8702-e156b1a6d6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año del proceso :'])[1]/following::select[1]</value>
      <webElementGuid>2815018d-1620-486f-9d05-50aaecde8167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::select[1]</value>
      <webElementGuid>34e9c490-5613-4055-82d2-332bc345c6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo :'])[1]/preceding::select[1]</value>
      <webElementGuid>06bdc1a7-2769-4e1b-b3da-05cc7f99a251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel :'])[1]/preceding::select[2]</value>
      <webElementGuid>0d65ae47-f1ad-4d80-9cb8-9b8ad3402274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>aeb7d5e1-49d5-4136-98ed-7c135d192649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'anio' and @id = 'anio' and (text() = '
                                             2025
                                                 2024
                                                 2023
                                                 2022
                                                 2020
                                                 2019
                                                 2018
                                                 2017
                                                 2016
                                                 2015
                                                 2014
                                                 2013
                                        ' or . = '
                                             2025
                                                 2024
                                                 2023
                                                 2022
                                                 2020
                                                 2019
                                                 2018
                                                 2017
                                                 2016
                                                 2015
                                                 2014
                                                 2013
                                        ')]</value>
      <webElementGuid>2da4f2a2-3d1c-4743-8676-838dbc815a6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
