<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_informeMatricula_selectDeManera</name>
   <tag></tag>
   <elementGuidId>6ec2dce2-4f15-4cc3-9b82-d61fcade0963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='orden']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#orden</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#orden</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3e00271f-d448-4181-bc51-3258f06ec503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orden</value>
      <webElementGuid>6f4d7ce4-2e29-481c-abdb-a1cb1b0caa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CargarGrillaMatriculas()</value>
      <webElementGuid>bf4a04bc-752b-4860-9456-d171a5d18666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Ascendente
                    Descendente
                </value>
      <webElementGuid>ba2b0601-772a-47ec-9d06-a8e30cd7f1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orden&quot;)</value>
      <webElementGuid>edac9757-c8ce-4f84-9697-ce0ceefaeeec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='orden']</value>
      <webElementGuid>0eabf03d-b27b-48e8-9c1b-048dd3fbbdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr[2]/td[6]/select</value>
      <webElementGuid>bbe410d3-e1d3-48a6-9a78-60ebf35c2004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De manera :'])[1]/following::select[1]</value>
      <webElementGuid>1b99f841-00ba-4df3-bea1-bfe17a06d419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar por :'])[1]/following::select[2]</value>
      <webElementGuid>bd4a3a63-b7eb-48ec-b180-ec3f96e452fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Considerar retirados:'])[1]/preceding::select[1]</value>
      <webElementGuid>b9f27986-1326-4418-9bc4-b30dd319f84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código enseñanza:'])[1]/preceding::select[2]</value>
      <webElementGuid>b6dc6388-d5f5-459a-8527-c4a7e532f98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/select</value>
      <webElementGuid>676e6a35-3faa-4e62-9ad7-4c288e06a405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'orden' and (text() = '
                    Ascendente
                    Descendente
                ' or . = '
                    Ascendente
                    Descendente
                ')]</value>
      <webElementGuid>934e10fa-d882-43b1-9b04-a52636dc4e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
