<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_informeMatricula_selectConsiderarRetirados</name>
   <tag></tag>
   <elementGuidId>67fa2bed-42e3-400c-9dbb-298e078952f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='retirados']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#retirados</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#retirados</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2e80f82f-2102-4e98-99a2-6aeec1bf40d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retirados</value>
      <webElementGuid>211c6ed3-6ab2-4a8c-abc5-708fd466e421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CargarGrillaMatriculas()</value>
      <webElementGuid>513eec43-2d46-4ad7-a9ee-22f6556d223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     No 
                     Si
                </value>
      <webElementGuid>db24895e-4e83-451a-b9db-0868a16233d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retirados&quot;)</value>
      <webElementGuid>cfa1d030-016e-456f-86c1-840bd71b0842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='retirados']</value>
      <webElementGuid>3daf8df6-208d-43b0-8b7a-075f7dba9605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>88fb4755-8465-401a-8ed5-2899d9ae2e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Considerar retirados:'])[1]/following::select[1]</value>
      <webElementGuid>87b34068-ac05-4eb5-9f6c-295b885dda73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De manera :'])[1]/following::select[2]</value>
      <webElementGuid>c630a5f7-4151-450b-93f7-c93b975134a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código enseñanza:'])[1]/preceding::select[1]</value>
      <webElementGuid>b7dd389b-d1fa-4a9e-8b17-7b5da7afb3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calidad alumno/a:'])[1]/preceding::select[2]</value>
      <webElementGuid>44fb6875-5f4c-460e-8159-9f2ce2c859aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/select</value>
      <webElementGuid>65603bbb-5515-4472-ab1a-6a47e6378d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'retirados' and (text() = '
                     No 
                     Si
                ' or . = '
                     No 
                     Si
                ')]</value>
      <webElementGuid>cf933054-1d3c-4ba7-9b29-9c7a23ac043b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
