<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cambioCurso_inputFechaMatriculaDestino</name>
   <tag></tag>
   <elementGuidId>c6ef2289-325f-4fc1-b93b-1361fc82e704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ingresoDestino']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ingresoDestino</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ingresoDestino</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60052a54-8539-434d-b86f-6ef3a18bf660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMigrador</value>
      <webElementGuid>6ffed01c-2510-46a5-8308-86eb54f62b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>7a735f7f-d99b-4550-aaaf-9c80b77e63b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fechaIngresoDestino</value>
      <webElementGuid>6d099434-2d4d-40bf-b401-4452b502f37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ingresoDestino</value>
      <webElementGuid>68c77687-2ab7-41b5-94a0-da538f27e1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>verificarDatos()</value>
      <webElementGuid>fcd5038b-9c2c-4ee6-a326-63b6ed89900e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ingresoDestino&quot;)</value>
      <webElementGuid>dabbaa12-03cc-47f6-87ea-e084fd051eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ingresoDestino']</value>
      <webElementGuid>0db5fa8f-f919-4338-b19f-3bf920cf2d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/div[2]/div[2]/div[3]/div[3]/h5/input</value>
      <webElementGuid>b1c619d1-31d4-4d91-bc7b-31e7194a4666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/h5/input</value>
      <webElementGuid>08e9a128-07fd-4ce0-bf08-4cfabcc51888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'fechaIngresoDestino' and @id = 'ingresoDestino']</value>
      <webElementGuid>71854ab2-51e1-4667-accf-d6500768c357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
