<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cambioCurso_buttonFinalizar</name>
   <tag></tag>
   <elementGuidId>ce9c53c8-bce8-43b2-ae2a-2177d8656553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonMigradorFinalizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#botonMigradorFinalizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Finalizar&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c1cbc38-123e-48b2-a64e-0b22b4c90703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonMigrador</value>
      <webElementGuid>5787f4fb-ade7-4aa8-a3d1-e29d62ab9666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonMigradorFinalizar</value>
      <webElementGuid>8ef09823-a737-4596-8622-3bec8ccf5b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>finalizarMigrador()</value>
      <webElementGuid>14ef1e69-aa28-4dcb-a11b-aa5902de9808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Finalizar
                    </value>
      <webElementGuid>c37c11a3-a235-42f4-b971-b5bf5c4eed86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonMigradorFinalizar&quot;)</value>
      <webElementGuid>3dd11524-1ebc-4d73-85e2-2cc296fa33f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonMigradorFinalizar']</value>
      <webElementGuid>c22a067a-eefa-4bd3-928c-b0a0902b16af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/div[4]/button[2]</value>
      <webElementGuid>3c037272-b91f-4f9c-9199-0d6157134f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar'])[1]/following::button[1]</value>
      <webElementGuid>72bec115-1a9f-4055-87a6-60b4471883da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocultar estudiante del listado original del curso'])[1]/following::button[2]</value>
      <webElementGuid>41b3c8a6-a2e5-416e-a828-02c6fb59889d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar']/parent::*</value>
      <webElementGuid>de1b30c9-6b14-4a4c-a1ca-cce0e6a3b3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/button[2]</value>
      <webElementGuid>39512f8a-313c-445d-bbe9-d3511571b185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'botonMigradorFinalizar' and (text() = '
                        Finalizar
                    ' or . = '
                        Finalizar
                    ')]</value>
      <webElementGuid>ce2f7754-aeed-463b-b18d-6e3ab5ccda7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
