<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cambioCurso_checkConfirmo</name>
   <tag></tag>
   <elementGuidId>91bb9f07-b636-4a3c-8f2a-25d571e027db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SIGEDestino']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIGEDestino</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SIGEDestino</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3b45b8-2c11-413f-b609-64c9a903a122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SIGEDestino</value>
      <webElementGuid>0d943592-7d96-4f74-88dc-0e111ef54706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>19b1a076-3b38-496d-a4e5-108216abb0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>verificarDatos()</value>
      <webElementGuid>a0c0799f-4297-45ed-b803-f335a7adc18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIGEDestino&quot;)</value>
      <webElementGuid>0c04ab85-2b40-4699-b61f-d6dc8e42a5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SIGEDestino']</value>
      <webElementGuid>4387e00d-0425-4875-a769-570836c0bd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/div[2]/div[2]/div[3]/div[3]/h5/div[8]/input</value>
      <webElementGuid>b396a8f4-b1d0-4fef-9b35-58dfdf62c962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>2c5988f7-9270-4ddd-a040-96ecb72bc259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SIGEDestino' and @type = 'checkbox']</value>
      <webElementGuid>c1f4eeea-4403-4805-bf1b-0732de165561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
