<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cambioCurso_buttonCambiar</name>
   <tag></tag>
   <elementGuidId>ce662a3b-1155-45a2-9f9a-fcbaeba5ce02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_alumnos']/table/tbody/tr[2]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Bolaños Madariaga Juan Cambiar&quot;s] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b814cc5-34e8-47d5-b3ab-8263d995050c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>290442e0-cb58-479d-be77-cc14608d0fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cambiar</value>
      <webElementGuid>222bad49-6f7c-4c43-ab35-c83678c25d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42cc1862-1e70-40af-8ec9-b67693188b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cambiar(5843577,'Bolaños Madariaga Juan 17187073-9','https://qacertificacion7.webescuela.cl')</value>
      <webElementGuid>f789aad6-48df-4f54-9adb-e2b6f625470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_alumnos&quot;)/table[@class=&quot;sortable&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>90a6e8ab-c0cf-4609-8ee4-caa2ebd9d876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Cambiar']</value>
      <webElementGuid>08482ca6-0e58-48d2-8f17-8a8963bd22c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_alumnos']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f04051de-ca3f-4ffc-b204-1d465f9c360d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>39cc302e-e932-4d55-8b8c-87d5b686c4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ac8d84ea-2027-4b44-8097-bcc626900c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
