<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cambioClases_inputFechaRetiroEst</name>
   <tag></tag>
   <elementGuidId>785f993f-290c-4cfc-a0aa-9095ada115cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retiroOrigen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#retiroOrigen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#retiroOrigen</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef70fc97-21a6-4e08-a85f-a2dda76c7503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMigrador</value>
      <webElementGuid>ca8009cf-c13d-4c07-b03a-372f58d39d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>64486cf8-076d-49fe-a5c8-15fc726098a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fechaRetiroOrigen</value>
      <webElementGuid>cd6b828f-189a-4f51-8726-c6c74a2c549f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retiroOrigen</value>
      <webElementGuid>55fcfc47-632b-4de8-b103-34eb80754a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>verificarDatos()</value>
      <webElementGuid>229dabe1-ccfb-4d26-aeb1-fea6c9c50dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retiroOrigen&quot;)</value>
      <webElementGuid>d82b94e2-01c5-44ab-85c7-91b6bea23d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retiroOrigen']</value>
      <webElementGuid>f3c26ff7-8c18-428c-8a6c-6a2a471051a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/div[2]/div[2]/div/div[3]/h5/input</value>
      <webElementGuid>0157fd89-856b-4396-9a3f-e1522ca94685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/input</value>
      <webElementGuid>6726eb5b-e48c-44b2-b564-864b1ce95d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'fechaRetiroOrigen' and @id = 'retiroOrigen']</value>
      <webElementGuid>83dabcec-a7d2-4d56-b3c1-0597708a7a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
