<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cambioCurso_buttonCambiarConfirmar</name>
   <tag></tag>
   <elementGuidId>d3776bce-6d29-4248-98da-9a5f433d23fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonMigradorCambiar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#botonMigradorCambiar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Se realizará el cambio del alumno Bolaños Madariaga Juan 17187073-9\n            Desde primero basico t A hacia Primero Básico B&quot;i >> internal:text=&quot;Cambiar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ac1c50f-a695-4e56-a5f6-234688e23d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonMigrador</value>
      <webElementGuid>3c01cc8f-07ce-474e-a6e0-43879474a217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonMigradorCambiar</value>
      <webElementGuid>5641fcbf-3827-4be9-bc60-489f8fa7b263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>migracionPaso2(5843577,{&quot;observaciones&quot;:0,&quot;notas&quot;:1,&quot;apoderados&quot;:1,&quot;matricula&quot;:{&quot;fecha_ingreso&quot;:&quot;01-01-2025&quot;,&quot;fecha_retiro&quot;:null,&quot;numero_matricula&quot;:&quot;8&quot;,&quot;numero_lista&quot;:1}},200306,'https://qacertificacion7.webescuela.cl')</value>
      <webElementGuid>09eca65e-56f3-4cef-aedd-cf90bdfedf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Cambiar
                    </value>
      <webElementGuid>65d543a4-d35a-4161-9b34-70c05fe2ab12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonMigradorCambiar&quot;)</value>
      <webElementGuid>6e1908f3-b83e-473d-9467-7d0af2813cf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonMigradorCambiar']</value>
      <webElementGuid>5bb20868-f601-4d57-9083-91d9c9c257af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/div[4]/button</value>
      <webElementGuid>3e980669-afad-42e8-88ea-0a2de7559838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocultar estudiante del listado original del curso'])[1]/following::button[1]</value>
      <webElementGuid>89f81496-e531-4039-8365-d6b32868faf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGE y son los correctos.'])[1]/following::button[1]</value>
      <webElementGuid>7b1eca2c-9d7d-47e9-8a51-b835acc92891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cambiar']/parent::*</value>
      <webElementGuid>b295705a-9118-4a42-a433-d5804ac6a6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/button</value>
      <webElementGuid>d2d6bc9d-560c-45a8-ad88-663f00fdf686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'botonMigradorCambiar' and (text() = '
                        Cambiar
                    ' or . = '
                        Cambiar
                    ')]</value>
      <webElementGuid>0ce777fc-0081-4b02-9614-ce630c42d5ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
