<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libbroDigital_observaciones_nueInci_buttonAgregarProto</name>
   <tag></tag>
   <elementGuidId>c86beb27-0814-42f3-bb34-76deddd41342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='quitarProtocolo()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Quitar&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df06f456-d48b-4f73-ac45-81f59c40cc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quitarProtocolo()</value>
      <webElementGuid>1f500c8d-7c50-4092-9fd9-92d8386589f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-red-button</value>
      <webElementGuid>63f1c8bd-8cca-4161-89ad-d3c787a6ea71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Quitar </value>
      <webElementGuid>415ec7fb-9079-4e11-8410-913f1eaaf27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incidenteObs&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-box-main&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-2 i-center&quot;]/div[@class=&quot;i-col-12 i-center&quot;]/button[@class=&quot;i-red-button&quot;]</value>
      <webElementGuid>b5a3a988-9d63-4fb3-b985-0d6d113f37c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='quitarProtocolo()']</value>
      <webElementGuid>893b8179-8dd8-4587-88b4-5b9a3c77ab45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div[2]/div[2]/button</value>
      <webElementGuid>b2373042-efa3-4b36-ae82-d6f39211d1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/following::button[1]</value>
      <webElementGuid>f0b8d9f1-df28-456f-a97a-7c7df1d488cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedimiento:'])[1]/following::button[2]</value>
      <webElementGuid>e9188b6e-b24d-4ea3-97d3-fd8e715fd1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de Artículos o Protocolos y Procedmientos acordádos'])[1]/preceding::button[1]</value>
      <webElementGuid>4c7748f7-fd93-410f-a946-d49e4d794126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acuerdos y Medidas Disciplinarias'])[1]/preceding::button[1]</value>
      <webElementGuid>2765f59a-1efd-4262-a6d2-4665baceb7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quitar']/parent::*</value>
      <webElementGuid>d2f662e3-4147-4a4c-84d4-2c60d811f0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div[2]/button</value>
      <webElementGuid>8f5d93a3-a01b-428e-a316-d72ddf6a9a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Quitar ' or . = ' Quitar ')]</value>
      <webElementGuid>ec996673-f578-4bd1-915d-0ede81be88c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
