<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_inputNombreReu</name>
   <tag></tag>
   <elementGuidId>99a51cea-83c3-40db-98bc-6d7414240826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nombreReunion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nombreReunion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nombreReunion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0796e6f9-f12a-46c9-aeb3-fa73341fa343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nombreReunion</value>
      <webElementGuid>2d6f6bfc-ab7c-4b18-a0d3-1015b1153002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nombreReunion&quot;)</value>
      <webElementGuid>70d848ae-ecb3-4630-9245-f73766b00798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nombreReunion']</value>
      <webElementGuid>f4b187b7-d00f-4ab1-a337-2fbd6f01383b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>abdb982f-c1e3-4cd3-ba22-f8437654dd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>5a837968-10a7-4bee-b1e3-4bb04fd58c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nombreReunion']</value>
      <webElementGuid>963a53f9-155a-40b0-bd93-4c7b40bc1349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
