<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_textDescripcion</name>
   <tag></tag>
   <elementGuidId>a8526bf1-72f0-4455-a424-1046dae2531f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descripcion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='descripcion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#descripcion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4d7f6970-b5d6-49c4-ac28-adc3b583dc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>774fe3c7-3c2e-4917-bcdb-015a5178a18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descripcion</value>
      <webElementGuid>097bd7bd-49d2-4c4a-8c37-674686781133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f36703f9-12ec-49f9-b61d-a0009146f1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripcion de la reunion...</value>
      <webElementGuid>0800e1b7-71e5-49e2-aa06-65f3b8fcd375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>408158b6-a5a0-4643-8185-d61bff8f5529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descripcion&quot;)</value>
      <webElementGuid>55ade4ed-c165-4cbc-9340-941bd198be8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='descripcion']</value>
      <webElementGuid>c617b8c6-530d-47a0-94de-cf076eff0e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[4]/div/div[2]/div/div/div[2]/textarea</value>
      <webElementGuid>f1e0df75-d821-4cd4-96e6-962fffea6395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f59a601b-f355-4c88-add5-d6ab2b66ce9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'descripcion' and @placeholder = 'Descripcion de la reunion...']</value>
      <webElementGuid>4c4e2572-c51f-43ed-85e4-d9a45e1ac6f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
