<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_buttonIncidencias</name>
   <tag></tag>
   <elementGuidId>ebbfdad9-ba47-49b1-8204-f703628e0bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-incidentes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-incidentes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Incidentes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44812e4e-521e-4cb8-befc-9c9f890130a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-tab-button</value>
      <webElementGuid>3107a549-ae72-49f6-86cc-fbd8c8369238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-incidentes</value>
      <webElementGuid>edaa7930-30d3-435a-b12e-54b504cce0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mostrarIncidentes()</value>
      <webElementGuid>f782d348-08c6-49d0-b21a-3b7e2f1f5f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Incidentes </value>
      <webElementGuid>fd58ba70-df54-45fd-be5a-ad56e8ba3821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-incidentes&quot;)</value>
      <webElementGuid>a1d38dfd-0cb6-4bdc-9495-d8a9e4cba0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tab-incidentes']</value>
      <webElementGuid>32136a57-1c96-4fe3-bf1c-d88a7e90d1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inicio']/div[2]/div[2]/button</value>
      <webElementGuid>ffb03478-742f-4502-9955-33e5a7b4009d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[4]/following::button[1]</value>
      <webElementGuid>0f1bd18a-1c6f-4793-b502-60595ebfa8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N°:'])[1]/following::button[2]</value>
      <webElementGuid>07a13256-8659-4bf8-94be-317068e71062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrevistas'])[1]/preceding::button[1]</value>
      <webElementGuid>56f672bd-40a2-4e6b-9dcb-93f8a364d027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N°'])[1]/preceding::button[2]</value>
      <webElementGuid>1acf59aa-be8e-49e6-9427-73a8700dbbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Incidentes']/parent::*</value>
      <webElementGuid>f6b9c3bd-d0a0-4d5e-a80f-ffdb676ac98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>8603952d-65a6-4c8f-b1c4-de2db73943bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tab-incidentes' and (text() = ' Incidentes ' or . = ' Incidentes ')]</value>
      <webElementGuid>84037b54-3505-42b1-a6da-bbf53a60a4b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
