<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_textAcuerdoMedida</name>
   <tag></tag>
   <elementGuidId>da54409c-e96a-4df2-a0af-753562b6b3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medidasDisciplinariasReunion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='medidasDisciplinariasReunion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Medidas disciplinarias...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>80e5e17f-d1f7-4384-9c5f-4a62ab9ff4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>1be7bea4-fd14-4d1a-b11e-05ad835c6df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>medidasDisciplinariasReunion</value>
      <webElementGuid>823441ae-1548-4834-b4fc-c4640c110a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>66f85dda-fb11-4ac0-89e2-876a83bdcd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Medidas disciplinarias...</value>
      <webElementGuid>935ea289-5ea0-4cc4-9593-5cb169a3cf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>750</value>
      <webElementGuid>c644a0c4-c345-4917-9999-da28adbce0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medidasDisciplinariasReunion&quot;)</value>
      <webElementGuid>f65a7777-7fa9-4cb9-8e5a-761e751de6ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='medidasDisciplinariasReunion']</value>
      <webElementGuid>474d1678-a36e-45c4-b4b5-4b08af034f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[4]/div/div[2]/div/div[2]/div[2]/textarea</value>
      <webElementGuid>ae028065-be36-41ef-84a9-484099b2ead7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>a70df267-cacc-4f89-b409-fd525ae345a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'medidasDisciplinariasReunion' and @placeholder = 'Medidas disciplinarias...']</value>
      <webElementGuid>62e808bb-b1bf-405e-9147-416d3ca5ffde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
