<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectDonde</name>
   <tag></tag>
   <elementGuidId>7e89b3ab-7fc8-45ac-96b1-1e9dfa2a2465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idRefDonde']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idRefDonde</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idRefDonde</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ed776fe-fccf-4b1b-9b5f-008f6fdf32b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idRefDonde</value>
      <webElementGuid>c85a40d4-c9a5-419f-9e4c-5ee89613f4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>25d6b0e6-384e-4f71-8cd4-6b2fc68f001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                 Desconocido 
                                                  Fuera del campus en otro lugar no relacionado con la escuela    Fuera del campus en una actividad patrocinada por la escuela    En línea    Fuera del campus en otra instalación del distrito escolar    Fuera del campus en otra escuela    Caminar hacia o desde la escuela    Autobús escolar    Parada de autobús    Fuera del campus    En el campus otra área exterior    Estacionamiento    Estadio    campo de atletismo o parque infantil    En el campus otra área interior    Sala    Laboratorio de computación    Biblioteca/centro de medios    Area de aseo    Vestuario o áreas de gimnasio    Pasillo o escaleras    Sala de clases    Área de cafetería    Área de oficinas administrativas    En el campus                                              </value>
      <webElementGuid>a2c32b16-6195-4915-9d36-6785a28b2c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idRefDonde&quot;)</value>
      <webElementGuid>4c3afc43-60f4-452a-923d-8771c74cd405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idRefDonde']</value>
      <webElementGuid>903d9187-ae94-4c9a-805e-9e1f39304fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div[4]/select</value>
      <webElementGuid>ed8ebf56-9fdc-462a-b821-229b84ff8357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donde:'])[1]/following::select[1]</value>
      <webElementGuid>9347a4c7-5aa1-47c5-9ab4-dea7eb569b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuando:'])[1]/following::select[2]</value>
      <webElementGuid>67e3704b-9d91-494a-9430-d85ef6033b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denunciante:'])[1]/preceding::select[1]</value>
      <webElementGuid>bdd936c9-c7be-4a3f-b79b-1acfc13e48cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Involucrados'])[1]/preceding::select[2]</value>
      <webElementGuid>788c784a-97dd-44be-a7cc-377d609f591d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/select</value>
      <webElementGuid>89a0252b-e986-4dbd-8e3d-42573c5ddbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idRefDonde' and (text() = '
                                                 Desconocido 
                                                  Fuera del campus en otro lugar no relacionado con la escuela    Fuera del campus en una actividad patrocinada por la escuela    En línea    Fuera del campus en otra instalación del distrito escolar    Fuera del campus en otra escuela    Caminar hacia o desde la escuela    Autobús escolar    Parada de autobús    Fuera del campus    En el campus otra área exterior    Estacionamiento    Estadio    campo de atletismo o parque infantil    En el campus otra área interior    Sala    Laboratorio de computación    Biblioteca/centro de medios    Area de aseo    Vestuario o áreas de gimnasio    Pasillo o escaleras    Sala de clases    Área de cafetería    Área de oficinas administrativas    En el campus                                              ' or . = '
                                                 Desconocido 
                                                  Fuera del campus en otro lugar no relacionado con la escuela    Fuera del campus en una actividad patrocinada por la escuela    En línea    Fuera del campus en otra instalación del distrito escolar    Fuera del campus en otra escuela    Caminar hacia o desde la escuela    Autobús escolar    Parada de autobús    Fuera del campus    En el campus otra área exterior    Estacionamiento    Estadio    campo de atletismo o parque infantil    En el campus otra área interior    Sala    Laboratorio de computación    Biblioteca/centro de medios    Area de aseo    Vestuario o áreas de gimnasio    Pasillo o escaleras    Sala de clases    Área de cafetería    Área de oficinas administrativas    En el campus                                              ')]</value>
      <webElementGuid>0ac439f8-0b4c-4bfb-a437-0cb2b4c5198e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
