<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_buttonEntrevistas</name>
   <tag></tag>
   <elementGuidId>63640f4b-158f-449a-b394-fae4fac11a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-entrevistas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab-entrevistas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Entrevistas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dac01fd1-9f53-4849-9ebf-a8dc77a89027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-tab-button</value>
      <webElementGuid>9cec0aa6-c6aa-45d0-b2b4-760696507be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-entrevistas</value>
      <webElementGuid>6c66f2b0-2f0f-42a3-9b0a-5d2a6fea444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mostrarEntrevistas()</value>
      <webElementGuid>e6dbddf4-b16e-482a-8512-2f53b88b163e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Entrevistas </value>
      <webElementGuid>2f38a4b8-b191-41dc-9602-f04fca550f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-entrevistas&quot;)</value>
      <webElementGuid>e1772a5c-9f07-48f4-a7e9-61d37fd0db58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tab-entrevistas']</value>
      <webElementGuid>f42d0403-8f74-4b8d-8fc8-79cd4e76fbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inicio']/div[2]/div[3]/button</value>
      <webElementGuid>bb58323f-0337-4c60-84fb-8a1d05c70061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incidentes'])[1]/following::button[1]</value>
      <webElementGuid>798644aa-ee44-4cb1-912a-f1fbfe47c0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[4]/following::button[2]</value>
      <webElementGuid>083826e9-e0ac-42fc-9f4c-9c71eec2b659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N°'])[1]/preceding::button[1]</value>
      <webElementGuid>f600096a-0166-407e-be77-998d60f34b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignatura'])[1]/preceding::button[1]</value>
      <webElementGuid>6cdc2777-580d-4450-8402-129ebb6ec361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrevistas']/parent::*</value>
      <webElementGuid>95c5ef9a-85d7-4109-a9ed-4607230c68e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>fa35e0e1-3805-4bd4-9631-20a3714257d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tab-entrevistas' and (text() = ' Entrevistas ' or . = ' Entrevistas ')]</value>
      <webElementGuid>fd31ab2b-6bad-428d-8e24-644fc196a3fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
