<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInci_textAcuerdoOmedidas</name>
   <tag></tag>
   <elementGuidId>5ab8ae09-5516-4025-9ed5-4f3317d3093a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medidasDisciplinarias</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='medidasDisciplinarias']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Escriba su acuerdo o medida disciplinarias...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ffd287bb-6f9f-4f5b-8c0b-0c82fdb9d870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>medidasDisciplinarias</value>
      <webElementGuid>88270e00-6d8e-4522-a59a-864eaa4ba5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>5fbe59f4-2d07-4839-91b9-d115a83b197c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>52f64659-6ffe-4e10-86f8-f0a5a00d672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escriba su acuerdo o medida disciplinarias...</value>
      <webElementGuid>30af83e8-6630-4f5f-a16d-788249c30d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medidasDisciplinarias&quot;)</value>
      <webElementGuid>218ddd7f-e805-4576-bdb5-f9c81f7663a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='medidasDisciplinarias']</value>
      <webElementGuid>5850f302-490b-4d85-9ed2-ef22aa38092a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[7]/div/div[2]/div/div[2]/textarea</value>
      <webElementGuid>eb1c8dbf-9ed5-473f-b901-c8a8aa120ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>4917e039-5f05-4705-85d5-68164ad8b747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'medidasDisciplinarias' and @placeholder = 'Escriba su acuerdo o medida disciplinarias...']</value>
      <webElementGuid>02a8c7d3-b381-4fa6-ac7f-5ba1f3c3c059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
