<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInci_buttonGuardar</name>
   <tag></tag>
   <elementGuidId>61440043-8ee3-4722-a48d-837514c8866f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.i-col-3.i-center > button.i-blue-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Guardar sin firmar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4098d757-88db-4890-beb5-81577bb58988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01f03d74-4965-4e8a-8ec2-6ac5a4049507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>8dcd1a1c-a494-47cc-b840-d66c4e6f6c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>crearIncidente(null,0,'',14)</value>
      <webElementGuid>16865f44-0d90-4819-ad8f-12e4ed58f173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                         Guardar sin firmar
                                    </value>
      <webElementGuid>7abb11e6-1b19-498f-a09a-a6d88f9c8255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incidenteObs&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-box-main&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-row i-box-body&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-3 i-center&quot;]/button[@class=&quot;i-blue-button&quot;]</value>
      <webElementGuid>1b81eee3-9983-43fa-ae3d-b33635f059f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>486bf56c-2136-4f30-b45c-028d31d07cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[9]/div/div[2]/div[5]/div[2]/button</value>
      <webElementGuid>5cc09224-0dbe-4852-97c3-bf2edaeccd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fernanda Laux ZINGONI'])[1]/following::button[1]</value>
      <webElementGuid>10db7861-59ed-4245-a60a-d5212649587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar y Guardar'])[1]/following::button[1]</value>
      <webElementGuid>84acb16c-09dc-4742-92a7-020fdca3bb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar sin firmar']/parent::*</value>
      <webElementGuid>3430419c-0041-405d-b06b-f0a877154529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/button</value>
      <webElementGuid>0b2831f4-a16a-4d86-90ff-e9ebbd462cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                         Guardar sin firmar
                                    ' or . = '
                                         Guardar sin firmar
                                    ')]</value>
      <webElementGuid>03b4a0c1-8d33-46a6-8d41-e4629df13ac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
