<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_buttonAgregarInci</name>
   <tag></tag>
   <elementGuidId>820422ba-be21-473b-b115-ed4b6aae1601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='agregarInvolucradoBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agregarInvolucradoBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Agregar Seleccionado&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>072293ed-09c7-4e91-90f3-18389a5299e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67f826b3-fa01-4604-b6bd-41bd76f3877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>061426ef-f942-4e80-88f7-9cee1fb9e5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agregarInvolucradoBtn</value>
      <webElementGuid>9af94329-2a1f-4617-93f3-24eb8e6817e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>agregarInvolucrado()</value>
      <webElementGuid>1f49e627-53ce-441d-92bd-1431dd738e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Agregar Seleccionado </value>
      <webElementGuid>e6af0dd7-27f9-4955-b072-b98a663b530f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agregarInvolucradoBtn&quot;)</value>
      <webElementGuid>c31a13da-e33f-444b-88fb-db82fdf14927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='agregarInvolucradoBtn']</value>
      <webElementGuid>86c222d2-0d33-470e-8666-94645d036d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[3]/div/div/div[2]/div/button</value>
      <webElementGuid>5051cb2e-f870-4243-9b16-dda35bef9e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol en la comunidad:'])[1]/following::button[1]</value>
      <webElementGuid>1ac7d27d-c2f4-4cd2-b5e9-16c513cb38f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persona Involucrada'])[1]/following::button[1]</value>
      <webElementGuid>88496ef4-d0dc-46aa-b981-173ef1955939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quitar Seleccionado'])[1]/preceding::button[1]</value>
      <webElementGuid>3e76e914-8f08-4ee1-af11-fc06ed9574b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de Involucrados'])[1]/preceding::button[2]</value>
      <webElementGuid>34d28529-3dac-4c61-8792-cc89ccf074f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar Seleccionado']/parent::*</value>
      <webElementGuid>875e3273-7a25-46ac-8eb3-a391740801a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/button</value>
      <webElementGuid>e61fca36-4760-4f34-a74d-0cfadfad3fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'agregarInvolucradoBtn' and (text() = ' Agregar Seleccionado ' or . = ' Agregar Seleccionado ')]</value>
      <webElementGuid>a7d786d5-f62a-465b-9f35-14d9351d2132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
