<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInic_selectRelacionado</name>
   <tag></tag>
   <elementGuidId>c4d64b35-6da2-4f70-9721-98d127844da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='relacionColegio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#relacionColegio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#relacionColegio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c58202c-e358-45b4-84bb-d7cf23f2a6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relacionColegio</value>
      <webElementGuid>2f6d9584-a1db-4037-9e25-85d420bf0fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>57676a1a-46e5-4ba7-a98d-045a24539dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Seleccione Tipo </value>
      <webElementGuid>629b42f8-9032-41a3-a8ef-8dbdb930063e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relacionColegio&quot;)</value>
      <webElementGuid>1b0b64fa-70f0-47d9-bdc9-cf20768dbf53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='relacionColegio']</value>
      <webElementGuid>86372d6f-135f-411b-bcfe-4e259d8db21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div/div[4]/select</value>
      <webElementGuid>b68d5741-de88-405c-a9ab-64c932dd14ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relacionado:'])[1]/following::select[1]</value>
      <webElementGuid>605045ce-8962-4e1b-82a3-5bf1657227df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo:'])[1]/following::select[2]</value>
      <webElementGuid>07b183ac-9e0b-46bb-a36d-6b6403d74062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción corta del incidente:'])[1]/preceding::select[1]</value>
      <webElementGuid>f4e531f8-7b92-4eea-aace-22312e5bf7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción larga del incidente:'])[1]/preceding::select[1]</value>
      <webElementGuid>430d3264-83f4-420f-ad39-4d7c55eea380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/select</value>
      <webElementGuid>86e66a37-c72e-4b58-aeb7-9ce17a48e8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'relacionColegio' and (text() = ' Seleccione Tipo ' or . = ' Seleccione Tipo ')]</value>
      <webElementGuid>fe6939b9-dbcd-4b64-8b51-5d09872edb99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
