<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectRolInvolucrado</name>
   <tag></tag>
   <elementGuidId>1b2f9632-56ea-4cd0-a78e-11ec7db70033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rolWebclass']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rolWebclass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rolWebclass</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41d19eca-c2ed-4947-9e06-70d5af3035d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rolWebclass</value>
      <webElementGuid>b3d98d0b-cb98-437d-af61-f94ca89de5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>0a70dc2c-7efc-4e04-aaa0-1c19c5bbebf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>involucradosRolChange(this)</value>
      <webElementGuid>e03f6baf-7da2-430c-a9d3-371f30699938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                              Alcalde    Alumno    Apoderado    Asistentes de la Educación    Capacitador    Convivencia escolar    Director    Finanzas    Inspector general    Orientador    Pastor de colegio / Capellán    Perfil finanzas (Recaudación)    Profesor    Sostenedor    UTP    Webclass Manager                                          </value>
      <webElementGuid>3474c824-d7f1-4064-915b-beac23880cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rolWebclass&quot;)</value>
      <webElementGuid>75c69b47-5e8a-4208-a4bc-d7ab3831df86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rolWebclass']</value>
      <webElementGuid>ace7ce95-7754-46ae-8d2e-2e76019b7d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[3]/div/div/div/div[2]/div/div[2]/select</value>
      <webElementGuid>c48844d4-bc05-43c3-85d6-d8c7ce8fd3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol involucrado:'])[1]/following::select[1]</value>
      <webElementGuid>4cf6049f-8efd-40e6-b156-4a6c9e189854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Involucrados'])[1]/following::select[1]</value>
      <webElementGuid>adbbc786-ebd0-4eeb-9a17-22f2d0abf5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol en incidente:'])[1]/preceding::select[1]</value>
      <webElementGuid>29b6bb80-8778-4cb1-9fbc-43b76f8d5f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persona Involucrada'])[1]/preceding::select[2]</value>
      <webElementGuid>6c3b8e7a-f733-44f3-9ad9-e4174684028b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div[2]/select</value>
      <webElementGuid>f7f576e6-374e-4002-9780-1b2055c7ff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rolWebclass' and (text() = '
                                              Alcalde    Alumno    Apoderado    Asistentes de la Educación    Capacitador    Convivencia escolar    Director    Finanzas    Inspector general    Orientador    Pastor de colegio / Capellán    Perfil finanzas (Recaudación)    Profesor    Sostenedor    UTP    Webclass Manager                                          ' or . = '
                                              Alcalde    Alumno    Apoderado    Asistentes de la Educación    Capacitador    Convivencia escolar    Director    Finanzas    Inspector general    Orientador    Pastor de colegio / Capellán    Perfil finanzas (Recaudación)    Profesor    Sostenedor    UTP    Webclass Manager                                          ')]</value>
      <webElementGuid>2c5aafce-7ba4-46ff-93cc-416115d94a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
