<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectRolEnLaComuna</name>
   <tag></tag>
   <elementGuidId>da6ea643-98c6-4ea7-83d7-ec18e30d6e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoPersona']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipoPersona</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoPersona</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c92cebb-84d0-44c4-b238-849aa0fb5a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoPersona</value>
      <webElementGuid>4e81a3cd-2519-45ef-b55c-e5c4cf92f8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>549ebca7-42d2-4d34-a59c-f3866e52c6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Desconocido 
                                              Adjunto/asociado/vicedirector/subdirector    Administrador    Adulto responsable o conocido del estudiante    Alumno    Alumno de otro establecimiento    Alumno expulsado o retirado involuntariamente    Alumno Matriculado en el establecimiento    Alumno matriculado en la escuela donde ocurrió el incidente    Alumno matriculado en otra escuela    Apoderado    Bibliotecarios/especialista en medios    Cocinero/preparador de alimentos (personal de servicio de alimentos)    Conductor de autobús    Consejero    Consejero de actividades estudiantiles/entrenador no atlético    Consejero de la escuela    Custodio    Decano de instrucción/decano de estudiantes/decano de niños/decano de actividades estudiantiles    Director/director/directora/directora de escuela    Docente    Enfermera registrada    Entrenador de atletismo    Ex alumno    Guardia de seguridad    Maestro suplente    Miembro de la junta de educación/junta escolar/miembro del consejo de administración    Miembro del equipo    Oficial de la ley    Oficial de policía del distrito escolar asignado a la escuela    Oficial de policía del distrito escolar no asignado a la escuela    Oficial de policía municipal asignado a la escuela    Oficial de policía municipal no asignado a la escuela    Otro adulto    Otro personal profesional    Otros jóvenes no estudiantes    Paraprofesionales/Asistente de Instrucción    Personal administrativo    Personal de Apoyo Administrativo Escolar    Personal educativo profesional    Personal no escolar    Profesional de la educacion    Profesor    Representante de la escuela visitante    Superintendente adjunto/asociado/asistente/comisionado    Superintendente/comisionado    Todo el resto del personal de apoyo    Trabajador social    Tutor                                          </value>
      <webElementGuid>adc08eab-ca51-4f56-85ae-95417f065caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoPersona&quot;)</value>
      <webElementGuid>1cbd938d-8ee1-474f-8b72-6dd88abb2f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoPersona']</value>
      <webElementGuid>048bf7ab-1ed4-4ee2-9ea9-2ccf1b779468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[3]/div/div/div/div[2]/div[6]/div[2]/select</value>
      <webElementGuid>f26d6459-0bfe-4e7f-bf7f-41167c990561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol en la comunidad:'])[1]/following::select[1]</value>
      <webElementGuid>9a61cebd-dd05-47b7-8ad8-ec66d3ccf128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persona Involucrada'])[1]/following::select[2]</value>
      <webElementGuid>7072c88b-2607-49a4-b328-8b643b2672db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar Seleccionado'])[1]/preceding::select[1]</value>
      <webElementGuid>6f75e28d-1874-47bf-8fee-1cc0ddc140ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quitar Seleccionado'])[1]/preceding::select[1]</value>
      <webElementGuid>3a6be058-27ad-4a85-a767-9cd86c11c61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/select</value>
      <webElementGuid>98e39e0e-7588-41d8-8660-56cffc5bed3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoPersona' and (text() = '
                                             Desconocido 
                                              Adjunto/asociado/vicedirector/subdirector    Administrador    Adulto responsable o conocido del estudiante    Alumno    Alumno de otro establecimiento    Alumno expulsado o retirado involuntariamente    Alumno Matriculado en el establecimiento    Alumno matriculado en la escuela donde ocurrió el incidente    Alumno matriculado en otra escuela    Apoderado    Bibliotecarios/especialista en medios    Cocinero/preparador de alimentos (personal de servicio de alimentos)    Conductor de autobús    Consejero    Consejero de actividades estudiantiles/entrenador no atlético    Consejero de la escuela    Custodio    Decano de instrucción/decano de estudiantes/decano de niños/decano de actividades estudiantiles    Director/director/directora/directora de escuela    Docente    Enfermera registrada    Entrenador de atletismo    Ex alumno    Guardia de seguridad    Maestro suplente    Miembro de la junta de educación/junta escolar/miembro del consejo de administración    Miembro del equipo    Oficial de la ley    Oficial de policía del distrito escolar asignado a la escuela    Oficial de policía del distrito escolar no asignado a la escuela    Oficial de policía municipal asignado a la escuela    Oficial de policía municipal no asignado a la escuela    Otro adulto    Otro personal profesional    Otros jóvenes no estudiantes    Paraprofesionales/Asistente de Instrucción    Personal administrativo    Personal de Apoyo Administrativo Escolar    Personal educativo profesional    Personal no escolar    Profesional de la educacion    Profesor    Representante de la escuela visitante    Superintendente adjunto/asociado/asistente/comisionado    Superintendente/comisionado    Todo el resto del personal de apoyo    Trabajador social    Tutor                                          ' or . = '
                                             Desconocido 
                                              Adjunto/asociado/vicedirector/subdirector    Administrador    Adulto responsable o conocido del estudiante    Alumno    Alumno de otro establecimiento    Alumno expulsado o retirado involuntariamente    Alumno Matriculado en el establecimiento    Alumno matriculado en la escuela donde ocurrió el incidente    Alumno matriculado en otra escuela    Apoderado    Bibliotecarios/especialista en medios    Cocinero/preparador de alimentos (personal de servicio de alimentos)    Conductor de autobús    Consejero    Consejero de actividades estudiantiles/entrenador no atlético    Consejero de la escuela    Custodio    Decano de instrucción/decano de estudiantes/decano de niños/decano de actividades estudiantiles    Director/director/directora/directora de escuela    Docente    Enfermera registrada    Entrenador de atletismo    Ex alumno    Guardia de seguridad    Maestro suplente    Miembro de la junta de educación/junta escolar/miembro del consejo de administración    Miembro del equipo    Oficial de la ley    Oficial de policía del distrito escolar asignado a la escuela    Oficial de policía del distrito escolar no asignado a la escuela    Oficial de policía municipal asignado a la escuela    Oficial de policía municipal no asignado a la escuela    Otro adulto    Otro personal profesional    Otros jóvenes no estudiantes    Paraprofesionales/Asistente de Instrucción    Personal administrativo    Personal de Apoyo Administrativo Escolar    Personal educativo profesional    Personal no escolar    Profesional de la educacion    Profesor    Representante de la escuela visitante    Superintendente adjunto/asociado/asistente/comisionado    Superintendente/comisionado    Todo el resto del personal de apoyo    Trabajador social    Tutor                                          ')]</value>
      <webElementGuid>eb09afdd-c6ed-420d-ab53-5ce5938eb85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
