<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_labelAlumnoQuitar</name>
   <tag></tag>
   <elementGuidId>8155610c-5ae2-404a-84af-8ece1a4fa587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//option[@value='5845803'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combo_selecionados > option[value=&quot;5845803&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#combo_selecionados</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f7a9de45-fc8b-444f-950f-3387e6b9cb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5845803</value>
      <webElementGuid>cd97a2b4-d49a-4697-a48f-c9795791fb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> asdasd asdas  </value>
      <webElementGuid>ae8d48f4-58fa-4049-b75c-30cb5154b23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo_selecionados&quot;)/option[1]</value>
      <webElementGuid>77092eb2-8bb4-498c-9735-fbe177ca1593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//option[@value='5845803'])[2]</value>
      <webElementGuid>bc668f95-f0cd-464f-b0f9-df36b901e2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='combo_selecionados']/option</value>
      <webElementGuid>aa701cfc-e2f5-427f-8b5f-6881a0481293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista alumnos selecionados'])[1]/following::option[1]</value>
      <webElementGuid>820d8d71-f621-44c0-8b34-2da5479a33d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar alumnos'])[1]/following::option[3]</value>
      <webElementGuid>4d29a0d9-0786-4bf2-836e-275cdab64ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalles de la Observación'])[1]/preceding::option[1]</value>
      <webElementGuid>33a587e4-cbdb-446b-97d0-5132245b61f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Negativa'])[1]/preceding::option[1]</value>
      <webElementGuid>33d5c86b-b29a-4fbb-a708-87768d767003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='asdasd asdas']/parent::*</value>
      <webElementGuid>e0adc57a-f219-4aee-b5a6-a36ce6fcd935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select/option</value>
      <webElementGuid>98a08048-b415-490b-9da2-ba6217a4638f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = ' asdasd asdas  ' or . = ' asdasd asdas  ')]</value>
      <webElementGuid>0d682306-22ec-4add-ac19-e763aef84ce2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
