<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_labelApoSeleccionado</name>
   <tag></tag>
   <elementGuidId>9c040904-941e-4146-8fef-88d8c63345a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>option.optionsStyle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='0_1_22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#participantesLista</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>62f94d7e-9773-4180-b488-c7361cc4f440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionsStyle</value>
      <webElementGuid>e4f96d76-7435-458c-9a6e-59ab05edc266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0_1_22</value>
      <webElementGuid>a9cbef93-a983-49c0-b4d5-3a4801325b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;participantesLista&quot;)/option[@class=&quot;optionsStyle&quot;]</value>
      <webElementGuid>824dea30-79a2-405a-95ba-b2c8b9d88caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='0_1_22']</value>
      <webElementGuid>16e981cc-61b6-4bf6-8561-04d2c7225c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='participantesLista']/option</value>
      <webElementGuid>dfa68642-0b5c-4806-a597-a8f1b0a953fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Apoderado'])[1]/following::option[1]</value>
      <webElementGuid>3077e181-1ade-41e6-b132-092d08ef9edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar Apoderado'])[1]/following::option[1]</value>
      <webElementGuid>8c4e00e5-551e-4daa-afb9-81a3ec4d4ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antecedentes de la reunión:'])[1]/preceding::option[1]</value>
      <webElementGuid>7e4da0b3-89fb-403a-bc2b-cbdb0247794c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/select/option</value>
      <webElementGuid>4e6d10bb-b6b6-416c-8a39-f289a816907c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
