<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectTipoArma</name>
   <tag></tag>
   <elementGuidId>ea2b6d7e-032d-44ad-9b4e-979deb36182b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idTipoArmaUsada']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idTipoArmaUsada</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idTipoArmaUsada</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9ffbb7a-575c-4746-a83b-d5772a5d5215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTipoArmaUsada</value>
      <webElementGuid>b2c3f4e4-63f2-4566-bcf3-d07a9193895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>8ab2c83d-97e5-4e59-9c97-b9cc3499945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>armausadaI(this,1);</value>
      <webElementGuid>4b3ce39d-edba-4d4c-9118-ce52c42c04cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Ninguna 
                              pistolas / revolveres    Rifles / escopetas    Más de un tipo de armas de fuego    Otro                          </value>
      <webElementGuid>34803b2c-fcb1-4114-82b7-a4d4d589dffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTipoArmaUsada&quot;)</value>
      <webElementGuid>df656dde-44b1-4f14-b7ab-307ef56f5009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idTipoArmaUsada']</value>
      <webElementGuid>7b3adb5b-2478-4001-b292-516fa1683b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[4]/div[6]/select</value>
      <webElementGuid>14006e55-4dfd-408a-af63-6d51674da722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Arma:'])[1]/following::select[1]</value>
      <webElementGuid>511d7094-7a3d-4e76-8634-66aa39ee782d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severidad:'])[1]/following::select[2]</value>
      <webElementGuid>83ae85e7-8efa-4156-85fd-5bbe2337ac02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arma Usada:'])[1]/preceding::select[1]</value>
      <webElementGuid>fa24fa9e-f12d-47b5-a647-19f382764bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gravedad de Heridas y/o Lesiones del Incidente'])[1]/preceding::select[2]</value>
      <webElementGuid>83c64484-855b-4814-b4f1-0831ce72c98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[6]/select</value>
      <webElementGuid>a12e9fac-efb7-4d01-bcbe-243edf14fec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idTipoArmaUsada' and (text() = '
                         Ninguna 
                              pistolas / revolveres    Rifles / escopetas    Más de un tipo de armas de fuego    Otro                          ' or . = '
                         Ninguna 
                              pistolas / revolveres    Rifles / escopetas    Más de un tipo de armas de fuego    Otro                          ')]</value>
      <webElementGuid>153d562f-ce41-45d4-9af3-637d76e6ae9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
