<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_denunciante</name>
   <tag></tag>
   <elementGuidId>88ab3422-5dd6-4323-ac2d-1746906aeff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoInformante']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipoInformante</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoInformante</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a7a6d09-efc3-4782-a97c-2840a6b01c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoInformante</value>
      <webElementGuid>43b160b8-de17-4e80-9bd8-85647e8e1ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>6811ca6a-4506-4021-b458-fc5f183524bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                  Alumno    Alumno matriculado en la escuela donde ocurrió el incidente    Alumno matriculado en otra escuela    Alumno expulsado o retirado involuntariamente    Miembro del equipo    Personal educativo profesional    Profesor    Profesor suplente    Bibliotecarios/especialista en medios    Consejero    Consejero de la escuela    Entrenador de atletismo    Consejero de actividades estudiantiles/entrenador no atlético    Otro personal profesional    Enfermera registrada    Trabajador social    Administrador    Director/director/directora/directora de escuela    Adjunto/asociado/vicedirector/subdirector    Decano de instrucción/decano de estudiantes/decano de niños/decano de actividades estudiantiles    Superintendente/comisionado    Superintendente adjunto/asociado/asistente/comisionado    Miembro de la junta de educación/junta escolar/miembro del consejo de administración    Todo el resto del personal de apoyo    Conductor de autobús    Personal de Apoyo Administrativo Escolar    Custodio    Cocinero/preparador de alimentos (personal de servicio de alimentos)    Paraprofesionales/Asistente de Instrucción    Guardia de seguridad    Oficial de la ley    Oficial de policía municipal asignado a la escuela    Oficial de policía municipal no asignado a la escuela    Oficial de policía del distrito escolar asignado a la escuela    Oficial de policía del distrito escolar no asignado a la escuela    personal no escolar    Tutor    Representante de la escuela visitante    Otro adulto    Ex alumno    Otros jóvenes no estudiantes    Desconocido                                              </value>
      <webElementGuid>471cf564-27d1-4485-90d9-f291e2817d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoInformante&quot;)</value>
      <webElementGuid>60902ac0-3372-4af7-bc0d-6c3b67961ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoInformante']</value>
      <webElementGuid>f9c53516-2a78-4634-9ebc-f09a59911c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[2]/div/div[2]/div/div/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>a717b0a7-6af6-45a1-9aa4-c01d205fd83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denunciante:'])[1]/following::select[1]</value>
      <webElementGuid>0276ed62-d7ff-4237-8370-760d42de7b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donde:'])[1]/following::select[2]</value>
      <webElementGuid>eb2421fb-45d2-402b-ae37-3917f4503853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Involucrados'])[1]/preceding::select[1]</value>
      <webElementGuid>f4616032-95bb-4bdb-86f0-2756db8460aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol involucrado:'])[1]/preceding::select[1]</value>
      <webElementGuid>762bbe5d-338d-49ea-bd87-729a1ebff29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>0757f617-937a-481d-a503-d467001a01a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoInformante' and (text() = '
                                                  Alumno    Alumno matriculado en la escuela donde ocurrió el incidente    Alumno matriculado en otra escuela    Alumno expulsado o retirado involuntariamente    Miembro del equipo    Personal educativo profesional    Profesor    Profesor suplente    Bibliotecarios/especialista en medios    Consejero    Consejero de la escuela    Entrenador de atletismo    Consejero de actividades estudiantiles/entrenador no atlético    Otro personal profesional    Enfermera registrada    Trabajador social    Administrador    Director/director/directora/directora de escuela    Adjunto/asociado/vicedirector/subdirector    Decano de instrucción/decano de estudiantes/decano de niños/decano de actividades estudiantiles    Superintendente/comisionado    Superintendente adjunto/asociado/asistente/comisionado    Miembro de la junta de educación/junta escolar/miembro del consejo de administración    Todo el resto del personal de apoyo    Conductor de autobús    Personal de Apoyo Administrativo Escolar    Custodio    Cocinero/preparador de alimentos (personal de servicio de alimentos)    Paraprofesionales/Asistente de Instrucción    Guardia de seguridad    Oficial de la ley    Oficial de policía municipal asignado a la escuela    Oficial de policía municipal no asignado a la escuela    Oficial de policía del distrito escolar asignado a la escuela    Oficial de policía del distrito escolar no asignado a la escuela    personal no escolar    Tutor    Representante de la escuela visitante    Otro adulto    Ex alumno    Otros jóvenes no estudiantes    Desconocido                                              ' or . = '
                                                  Alumno    Alumno matriculado en la escuela donde ocurrió el incidente    Alumno matriculado en otra escuela    Alumno expulsado o retirado involuntariamente    Miembro del equipo    Personal educativo profesional    Profesor    Profesor suplente    Bibliotecarios/especialista en medios    Consejero    Consejero de la escuela    Entrenador de atletismo    Consejero de actividades estudiantiles/entrenador no atlético    Otro personal profesional    Enfermera registrada    Trabajador social    Administrador    Director/director/directora/directora de escuela    Adjunto/asociado/vicedirector/subdirector    Decano de instrucción/decano de estudiantes/decano de niños/decano de actividades estudiantiles    Superintendente/comisionado    Superintendente adjunto/asociado/asistente/comisionado    Miembro de la junta de educación/junta escolar/miembro del consejo de administración    Todo el resto del personal de apoyo    Conductor de autobús    Personal de Apoyo Administrativo Escolar    Custodio    Cocinero/preparador de alimentos (personal de servicio de alimentos)    Paraprofesionales/Asistente de Instrucción    Guardia de seguridad    Oficial de la ley    Oficial de policía municipal asignado a la escuela    Oficial de policía municipal no asignado a la escuela    Oficial de policía del distrito escolar asignado a la escuela    Oficial de policía del distrito escolar no asignado a la escuela    personal no escolar    Tutor    Representante de la escuela visitante    Otro adulto    Ex alumno    Otros jóvenes no estudiantes    Desconocido                                              ')]</value>
      <webElementGuid>9a65b5f4-99bd-4377-8040-a09fc4360bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
