<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_buttonObservaciones</name>
   <tag></tag>
   <elementGuidId>87cce9b5-c4dd-4228-8920-f74cbefce419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='observaciones']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.textos-suitems</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Observaciones&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f33990bc-e1ef-4c1b-b11e-430927ac1977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textos-suitems</value>
      <webElementGuid>adb89b5b-5293-4023-9908-dc5ff01be84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Observaciones</value>
      <webElementGuid>a232336d-4b39-4b8f-9703-4f8bd658f05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;observaciones&quot;)/span[@class=&quot;textos-suitems&quot;]</value>
      <webElementGuid>fdde20ed-e570-481a-a4a1-e3016cfdc2f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='observaciones']/span</value>
      <webElementGuid>6822ff70-e66e-4e7a-bf6f-a51f48df4535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistencia apoderado'])[1]/following::span[1]</value>
      <webElementGuid>f4839083-7400-46eb-aafa-e2e7b9033eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalidad'])[2]/preceding::span[1]</value>
      <webElementGuid>9365f9c2-973a-4a40-aadb-638548b0c0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Situación final'])[2]/preceding::span[2]</value>
      <webElementGuid>bb82cf1b-731f-4f73-a12f-8b4b8c123727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[11]/a/span</value>
      <webElementGuid>2b87c457-4014-480b-bf71-de396fa5965d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Observaciones' or . = ' Observaciones')]</value>
      <webElementGuid>829cb9de-77b5-486e-a614-34448707b51e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
