<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_selectRolComunidad</name>
   <tag></tag>
   <elementGuidId>41702d9d-cdac-4545-9f0f-4f550f58b408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='roles2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alumnos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#alumnos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>991a363e-b2cd-463c-9ec7-85866d01db7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alumnos</value>
      <webElementGuid>b7a0235e-ede7-486c-9a9c-37dffae8411f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alumnos</value>
      <webElementGuid>71173878-dce4-4ab2-8132-0eb58ac6dddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>c977154a-ec0e-429c-ae77-f708c2959819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cargarApoderadoReunionesAlumno(this,1)</value>
      <webElementGuid>c2f31759-1d89-4792-bc2f-e8d36d4ec7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Seleccione un Curso </value>
      <webElementGuid>e22602e6-6124-4f30-a2a2-b00b48fa5169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alumnos&quot;)</value>
      <webElementGuid>dd73d144-4779-4309-a277-7343dca5e724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='alumnos']</value>
      <webElementGuid>cfafaed7-ea75-447d-b920-3fce035e8baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[3]/div/div[2]/div/div[4]/select</value>
      <webElementGuid>5cd49bbe-00b2-493e-8713-4abfb2dda449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[8]/following::select[1]</value>
      <webElementGuid>bfd4acc5-6b93-42ef-b325-cf27a21eff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[9]/preceding::select[1]</value>
      <webElementGuid>1a7d75a9-a771-4cd6-86c7-101d64c08644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/select</value>
      <webElementGuid>0e2ceaec-2e87-4d9d-bbeb-636a1a51dd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'alumnos' and @name = 'alumnos' and (text() = ' Seleccione un Curso ' or . = ' Seleccione un Curso ')]</value>
      <webElementGuid>a2873231-722f-4b20-8943-059680f13ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
