<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectSeveridad</name>
   <tag></tag>
   <elementGuidId>f250719d-5317-44e4-85bc-5ff1c63fdea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='severidadIncident']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#severidadIncident</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#severidadIncident</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a74c5c2c-d8c8-4cd7-a7fc-4e085e0ad78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>severidadIncident</value>
      <webElementGuid>1fc623fa-ad71-48a0-9eae-1c6f24bf48e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>4a4d3f36-4a49-4acf-b68e-ed2f286e4b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Neutro 
                             Leve 
                             Grave 
                        </value>
      <webElementGuid>96427b71-a101-4446-8e60-fc8f03742005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;severidadIncident&quot;)</value>
      <webElementGuid>80ceb4d1-5285-469d-a18b-79dd3728c7c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='severidadIncident']</value>
      <webElementGuid>f998c344-e000-4335-b936-bcdb684dbc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[4]/div[4]/select</value>
      <webElementGuid>cab9856f-f737-4666-a57e-90fb4b5b8049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severidad:'])[1]/following::select[1]</value>
      <webElementGuid>2ea45d86-cf55-4f1e-ab7e-16247c537a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[1]/following::select[2]</value>
      <webElementGuid>bc80eeeb-9869-4f1e-b10d-e502acc253e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Arma:'])[1]/preceding::select[1]</value>
      <webElementGuid>c63a037a-dc11-4c5f-adfb-85c31ce89d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arma Usada:'])[1]/preceding::select[2]</value>
      <webElementGuid>8acb7025-4e49-416c-88fc-4cee452b59cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/select</value>
      <webElementGuid>202a1d0e-e73f-4c78-bee0-1f7ab27ce343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'severidadIncident' and (text() = '
                             Neutro 
                             Leve 
                             Grave 
                        ' or . = '
                             Neutro 
                             Leve 
                             Grave 
                        ')]</value>
      <webElementGuid>46ca033d-d4b5-42ab-b1e3-8d20d4845b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
