<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_inoutHora</name>
   <tag></tag>
   <elementGuidId>07c320b4-6142-4eea-af2c-2030808903a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horaIncidente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#horaIncidente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#horaIncidente</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbde0ea7-1617-428e-9a5f-71e2439e9360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>771bb956-a3c2-4e65-92dc-d9a003fd696c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horaIncidente</value>
      <webElementGuid>c805fe0f-e5a4-44b4-97a7-f9a6348e7463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horaIncidente&quot;)</value>
      <webElementGuid>5d6a34c4-efe6-4d69-9f25-315b0c3167d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horaIncidente']</value>
      <webElementGuid>6ab05967-01bc-473a-8a87-c5e9b84a72fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[2]/div/div[2]/div/div/div/div[2]/div[4]/input</value>
      <webElementGuid>46c21bd5-a031-42d7-821e-1c9a655ecb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a0ee4359-6590-46ba-b019-085d9b83451c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @id = 'horaIncidente']</value>
      <webElementGuid>0d7a9824-b5ef-492a-a37c-5ca78dca721f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
