<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_selectTipoObservacion</name>
   <tag></tag>
   <elementGuidId>6469dc64-c405-48e9-8ac0-87e9661caf0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>487878f2-fc1b-41a0-95ce-57485be49d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipo</value>
      <webElementGuid>959424dd-fd95-4b29-a75b-7fd4eb66e253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipo</value>
      <webElementGuid>d11d7604-c39e-4cba-bda4-b839e49cf336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>98fd0d6a-3e70-494a-ad13-bc6fc415465b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>detectChange(this)</value>
      <webElementGuid>2c62017f-25d6-4768-ba49-0e1046995c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Seleccione             Positiva
                         Negativa
                         Neutra
            </value>
      <webElementGuid>bea9499d-bf7c-4d91-a585-ac0cac248e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipo&quot;)</value>
      <webElementGuid>8026b9ce-87a4-4b57-a330-8325201d0451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipo']</value>
      <webElementGuid>09e159b9-e810-448a-b94e-d1c349588f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nueva']/div/section[3]/div[2]/div/div/div/div/div[2]/div/div/div[3]/select</value>
      <webElementGuid>0ab504bc-8410-4330-9a4e-bfddb00b26fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[3]/following::select[1]</value>
      <webElementGuid>b4926937-e604-4852-aeb6-8d23fe076e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[4]/preceding::select[1]</value>
      <webElementGuid>f4c28d62-eff3-4a25-9786-02b2821a691a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/select</value>
      <webElementGuid>fa0f9417-ef0d-4129-8917-c955c44460ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipo' and @id = 'tipo' and (text() = '        Seleccione             Positiva
                         Negativa
                         Neutra
            ' or . = '        Seleccione             Positiva
                         Negativa
                         Neutra
            ')]</value>
      <webElementGuid>a0700a34-ebe0-46cd-b0f4-b6cd172645b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
