<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_buttonQuitarTodos</name>
   <tag></tag>
   <elementGuidId>52e3acbe-c8f6-4652-aec4-017eba7cd433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Quitar todos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1bb1f94c-0580-4479-9593-e588f2b52b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46211f75-9966-4310-b9ef-e4dd07563685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-red-button</value>
      <webElementGuid>3f4d3247-ed33-4a87-9faf-abc41f6a9781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dc9a7289-84f4-4a9b-83d6-b89eb59a7231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quitarAlumno(0)</value>
      <webElementGuid>cf9f45ac-3d6a-4410-8853-a6fc1af2448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Quitar todos </value>
      <webElementGuid>f9a4208f-6da1-445e-972f-a244fa0fbb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nueva&quot;)/div[@class=&quot;incidentes-container&quot;]/section[@class=&quot;alumnos-incidentes&quot;]/div[1]/div[@class=&quot;alumnos-incidentes_btn i-center&quot;]/div[@class=&quot;i-col-8&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-12&quot;]/button[@class=&quot;i-red-button&quot;]</value>
      <webElementGuid>caf9cfaf-3199-44ae-9508-5bb1c96cf025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>8e6f8270-6668-4988-89fb-c1294b83787e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nueva']/div/section[2]/div/div[2]/div/div/div[4]/button</value>
      <webElementGuid>d0b4632b-ebc0-4cae-84d7-baf7650d5af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar alumnos'])[1]/following::button[4]</value>
      <webElementGuid>91807919-f4fa-4b26-ad8a-f09e3bfeaa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::button[4]</value>
      <webElementGuid>89b482b0-95c4-4599-ba6b-1390978a9cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista alumnos selecionados'])[1]/preceding::button[1]</value>
      <webElementGuid>cc135143-2be0-4ab2-9311-70a699baf908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalles de la Observación'])[1]/preceding::button[1]</value>
      <webElementGuid>81306cb4-e5a1-4fae-a246-a3802f0f1dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quitar todos']/parent::*</value>
      <webElementGuid>f41a4d70-77b9-46d1-af32-e21d99223411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/button</value>
      <webElementGuid>d080bdc2-176c-4e9a-974d-b3fe2f0340f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @href = '#' and (text() = ' Quitar todos ' or . = ' Quitar todos ')]</value>
      <webElementGuid>c7d41841-1d26-49cd-bc06-1b72749701f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
