<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInci_selectTipo</name>
   <tag></tag>
   <elementGuidId>46943247-98d7-4461-9972-f92978e2645f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipoC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoC</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa55c5fe-2581-49b2-ae84-20ad96ce29c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoC</value>
      <webElementGuid>df597fec-7e1d-4d28-a8e5-91baf4ebf4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>d703065a-04f3-43b5-8d60-666dc63475ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>habilitarRelacionado(this)</value>
      <webElementGuid>321bb417-cb6e-46fb-bab4-6696ba6b0593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Seleccione
                             Positiva
                             Negativa
                             Neutra
                        </value>
      <webElementGuid>e5a83bd9-dd4e-41db-a513-c86ac42c82ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoC&quot;)</value>
      <webElementGuid>bf65ec20-cf78-4aad-b62f-fc9f7852f4ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoC']</value>
      <webElementGuid>30c39bcf-dd00-4884-b59c-e73ae89a68b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div/div[2]/select</value>
      <webElementGuid>29bf6dda-04ff-45a4-97f8-f45ace64cb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo:'])[1]/following::select[1]</value>
      <webElementGuid>3312b200-a191-4809-991d-5f28220e1a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de Involucrados'])[1]/following::select[2]</value>
      <webElementGuid>dfb52cd8-e329-40c9-931f-a597a70c6720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relacionado:'])[1]/preceding::select[1]</value>
      <webElementGuid>072e39f8-31aa-48b6-b4ad-f5446d70fa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción corta del incidente:'])[1]/preceding::select[2]</value>
      <webElementGuid>d97c3cb3-9f52-44e5-b26d-267ea8cb5719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/select</value>
      <webElementGuid>37c18ff2-ee61-4d5b-a7f9-df9ea1a63fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoC' and (text() = '
                            Seleccione
                             Positiva
                             Negativa
                             Neutra
                        ' or . = '
                            Seleccione
                             Positiva
                             Negativa
                             Neutra
                        ')]</value>
      <webElementGuid>4ded4c01-d2db-475a-8316-deab000710ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
