<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacioenes_nueInci_inputArticuloProtocolo2</name>
   <tag></tag>
   <elementGuidId>0943a757-af3a-4bc2-8ca9-b9a0fb6643a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div/div[2]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tituloArticuloInfringido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tituloArticuloInfringido</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ac3c2ba-d000-4f80-8427-c465b3e26cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tituloArticuloInfringido</value>
      <webElementGuid>1e19bff2-be51-498a-9834-bc7dfb934052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb54ef56-9def-480c-835f-7bccb9bd1ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Titulo</value>
      <webElementGuid>9cd11a17-287a-4592-a7e9-ea3e2e4aafd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tituloArticuloInfringido&quot;)</value>
      <webElementGuid>8bc1c246-037b-47fb-be0f-0a242bdd7108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tituloArticuloInfringido']</value>
      <webElementGuid>432bff36-13b5-4323-abe8-0d12e7693a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div/div[2]/div/div/div[3]/input</value>
      <webElementGuid>dbee9b6a-945c-44e5-a467-87ff9eab7db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>1c904c57-285d-46fd-be02-faeb7df74640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tituloArticuloInfringido' and @type = 'text' and @placeholder = 'Titulo']</value>
      <webElementGuid>94762f5f-e8b3-4df5-9442-5a10ac09bd76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
