<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_buttonEliminarEntrevistas</name>
   <tag></tag>
   <elementGuidId>8ae76079-2c3c-4dd2-8188-4f298335d3ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabla_anotaciones']/div/div[2]/div[12]/div/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Borrar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>09876e03-7508-4316-af5b-794fcace13d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash-o</value>
      <webElementGuid>f1f228d6-ae79-46c0-81b9-46187928b0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>177619d5-5c7a-4110-8a8d-60f120eb4722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabla_anotaciones&quot;)/div[@class=&quot;i-container i-table&quot;]/div[@class=&quot;i-row i-center i-table-body i-table-body-hover&quot;]/div[@class=&quot;i-col-1 i-center i-table-rows ent-col-12&quot;]/div[@class=&quot;i-row i-center i-herramientas&quot;]/div[@class=&quot;i-col-4 i-center&quot;]/a[1]/i[@class=&quot;fa fa-trash-o&quot;]</value>
      <webElementGuid>cb781453-4056-4874-8b67-50c022edac10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabla_anotaciones']/div/div[2]/div[12]/div/div[3]/a/i</value>
      <webElementGuid>a37d0cb2-e484-4cd7-86ea-cba01d4d19a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>98f59f53-247c-47b9-a8ed-c89f25b18d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
