<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_inputHoraReunion</name>
   <tag></tag>
   <elementGuidId>9cef8496-ab32-47f4-a48f-3f13cfe2485c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horaReu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='horaReu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#horaReu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51348332-d96d-41df-9bbf-5aed6a3fd0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>743536dd-4a22-42bd-8f9e-03b7e1c976e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horaReu</value>
      <webElementGuid>6928e926-3cda-433e-9d22-75d4ddb34686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appt</value>
      <webElementGuid>e3428539-779b-45da-89de-f636aa4ed447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>08:00</value>
      <webElementGuid>5d00198d-a872-45be-a743-78f190119f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>23:00</value>
      <webElementGuid>16978400-bd4c-434a-b5d8-2d2378be65f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horaReu&quot;)</value>
      <webElementGuid>ae9b6c8e-b314-410b-8149-f275c5b266fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='horaReu']</value>
      <webElementGuid>ad012b9b-01fb-43be-86aa-9befabe82872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[2]/div/div[2]/div/div[6]/input</value>
      <webElementGuid>fe0d5cb7-d336-4d59-a795-b6d57534de87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>06f6b644-4120-4d16-85f6-ef71ff185bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @id = 'horaReu' and @name = 'appt']</value>
      <webElementGuid>082318fb-c3d2-47f6-b5c8-b9693e9df76b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
