<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_buttonAgregarTodos</name>
   <tag></tag>
   <elementGuidId>d38c022c-bf59-4a52-8544-b523d6d3825b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Agregar todos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaee4435-ff3b-4e5a-83ec-ae5c21adf70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9062bf2-e5a7-43ff-8463-8f405891a035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>cf5560f6-476c-4c5c-8eb9-805c7e0d779b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d824d748-c206-4ae2-a40d-56694621bf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>agregarAlumnoAlaAnotacion('5845803::5845801::',0)</value>
      <webElementGuid>20449858-c7e5-4f9a-b5d9-efda3f1e5a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Agregar todos </value>
      <webElementGuid>d1d6394e-ef4c-4014-9d35-7b8eac179310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nueva&quot;)/div[@class=&quot;incidentes-container&quot;]/section[@class=&quot;alumnos-incidentes&quot;]/div[1]/div[@class=&quot;alumnos-incidentes_btn i-center&quot;]/div[@class=&quot;i-col-8&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-12&quot;]/button[@class=&quot;i-blue-button&quot;]</value>
      <webElementGuid>e54e6ce1-eeb1-426f-b78c-e5c5a6a475ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>67b8e4ab-8371-4aec-b7bd-614d25be229b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nueva']/div/section[2]/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>3d70a96e-23fb-4843-a9fb-43e435c36f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar alumnos'])[1]/following::button[3]</value>
      <webElementGuid>5f36d17b-4648-49df-8b38-775a172e5cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::button[3]</value>
      <webElementGuid>c274a195-cf31-43ff-b61d-5530cafe4e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista alumnos selecionados'])[1]/preceding::button[2]</value>
      <webElementGuid>9bf95497-9597-4bac-bf57-60f26c042067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalles de la Observación'])[1]/preceding::button[2]</value>
      <webElementGuid>fe878d10-1286-4560-9a70-0773b17830ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar todos']/parent::*</value>
      <webElementGuid>31a413ab-d6ab-4e57-b3fd-cbeb97eacae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/button</value>
      <webElementGuid>c7cba9fc-c09a-4ac6-aadf-baf0738f4c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @href = '#' and (text() = ' Agregar todos ' or . = ' Agregar todos ')]</value>
      <webElementGuid>9f322d2e-a3ac-40df-8193-1aed70b363cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
