<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_buttonEliminar</name>
   <tag></tag>
   <elementGuidId>9f850907-d754-4111-89c1-bc329cde0f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabla_anotaciones']/div/div[2]/div[10]/div/div[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Borrar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c1c9a47d-b22f-42f4-a95c-bc3e97fa0ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash-o</value>
      <webElementGuid>5e125540-d135-4175-b88b-b257a38d62ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c14a96cf-8999-4156-a2a2-e065429b8525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabla_anotaciones&quot;)/div[@class=&quot;i-container i-table&quot;]/div[@class=&quot;i-row i-center i-table-body i-table-body-hover&quot;]/div[@class=&quot;i-col-1 i-center i-table-rows col-obs-10&quot;]/div[@class=&quot;i-row i-center i-herramientas&quot;]/div[@class=&quot;i-col-4 i-center&quot;]/a[1]/i[@class=&quot;fa fa-trash-o&quot;]</value>
      <webElementGuid>25688598-add3-4746-8079-2e07cda333e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabla_anotaciones']/div/div[2]/div[10]/div/div[3]/a/i</value>
      <webElementGuid>e4149abb-e647-49e0-8051-8473df67cd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>24a341b0-e296-4695-8cee-0796559888dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
