<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInici_buttonQuitarProtocolo</name>
   <tag></tag>
   <elementGuidId>ae382e18-1365-4e08-bf71-c04490f49e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='quitarProtocolo()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Quitar&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8dace269-6e19-4533-9dc5-db0595093f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quitarProtocolo()</value>
      <webElementGuid>3d3d8960-9f6f-43be-87f7-8c20881f748e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-red-button</value>
      <webElementGuid>632d2296-232b-4380-8c45-3cfddeb60bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Quitar </value>
      <webElementGuid>4aacf760-1333-4494-a5fa-477349396760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incidenteObs&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-box-main&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-2 i-center&quot;]/div[@class=&quot;i-col-12 i-center&quot;]/button[@class=&quot;i-red-button&quot;]</value>
      <webElementGuid>cd99a24e-ffde-45f3-a0bb-6c31254c4ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='quitarProtocolo()']</value>
      <webElementGuid>b9c83880-1554-4c51-9978-7f335b52a4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div[2]/div[2]/button</value>
      <webElementGuid>9be78b7f-e830-4a7a-b7e9-fe2cb031d177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/following::button[1]</value>
      <webElementGuid>dd59214e-d4a9-435f-8d07-430bdd673faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedimiento:'])[1]/following::button[2]</value>
      <webElementGuid>8f9fbc2b-e244-4db7-8c32-08196da6e104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de Artículos o Protocolos y Procedmientos acordádos'])[1]/preceding::button[1]</value>
      <webElementGuid>be8b4fa2-03ba-4004-aaad-51dd625ae1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acuerdos y Medidas Disciplinarias'])[1]/preceding::button[1]</value>
      <webElementGuid>01e7840c-ac74-43d4-a201-60e8e88ed5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quitar']/parent::*</value>
      <webElementGuid>7f936e91-95cb-44c2-bea7-3d1a78f80a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div[2]/button</value>
      <webElementGuid>1162573f-2265-4a86-9f00-aa5cfe065de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Quitar ' or . = ' Quitar ')]</value>
      <webElementGuid>f109b7ca-1c9c-4370-9235-278aa73daafc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
