<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_buttonGuardar</name>
   <tag></tag>
   <elementGuidId>63c0e9ac-09ea-4596-b3f3-ab01d73193bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.i-col-6.i-center > button.i-blue-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Guardar sin Firmar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>381075b8-731b-4a27-9cff-76cc8fa988d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7255c12-80f8-4e1d-ac92-9574652045cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>6b9dbce9-d5f3-4304-9169-e30d78c65ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GuardarNuevaReunion(0,0,14)</value>
      <webElementGuid>aac9d9bd-4743-4ad1-8add-cefec07e5b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Guardar sin Firmar </value>
      <webElementGuid>e2b05a06-ba98-4441-b993-eda1e4a72c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entrevista&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-row i-box-main&quot;]/div[@class=&quot;i-col-12&quot;]/div[@class=&quot;i-box-body&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-6&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-6 i-center&quot;]/button[@class=&quot;i-blue-button&quot;]</value>
      <webElementGuid>3f671adb-476d-4424-a143-77f4f0838fed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>b46a3a97-53ff-4210-8375-da3f6a466b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[6]/div/div[2]/div/div[3]/div/div[4]/button</value>
      <webElementGuid>0420c1a8-cdf0-447a-8b06-e0c35eb18b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authy'])[1]/following::button[1]</value>
      <webElementGuid>6f95f3dc-9c75-49e6-ae3e-e9bc5368dff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar y Guardar'])[1]/preceding::button[1]</value>
      <webElementGuid>ccb12bd4-e3c7-4a84-b363-e3063e10d60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar sin Firmar']/parent::*</value>
      <webElementGuid>b89f1572-74fc-4720-9e98-ae5b81dfbe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/button</value>
      <webElementGuid>3afaca5e-521c-489d-9b2a-48985e9685fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Guardar sin Firmar ' or . = ' Guardar sin Firmar ')]</value>
      <webElementGuid>9fd1079c-1baf-4684-99db-d97e4c7e38fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
