<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectArmaUsada</name>
   <tag></tag>
   <elementGuidId>32442e00-cf23-4002-bd49-ab766e955163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idArmaUsadaI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idArmaUsadaI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idArmaUsadaI</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>68b1adc2-ce72-4d67-9705-45371065b198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idArmaUsadaI</value>
      <webElementGuid>e54a24ba-5155-4e8a-86b2-5722ec14bc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>8d8e3b62-5b54-4b50-b907-48944545dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Ninguna 
                        </value>
      <webElementGuid>a14a763f-8cf3-43c6-835d-6ca199d81d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idArmaUsadaI&quot;)</value>
      <webElementGuid>3dfe79fc-a144-4a4a-8522-45db5a0f6c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idArmaUsadaI']</value>
      <webElementGuid>bec0730f-8414-4ff2-ab9d-b313799f3915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[4]/div[8]/select</value>
      <webElementGuid>dcdd45f9-eeaf-4f68-8755-31d5e01f6307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arma Usada:'])[1]/following::select[1]</value>
      <webElementGuid>5b43a180-348f-4198-9781-a50b419ad7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Arma:'])[1]/following::select[2]</value>
      <webElementGuid>6f0bb2ed-b71c-44e2-a3a9-bf116c878526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gravedad de Heridas y/o Lesiones del Incidente'])[1]/preceding::select[1]</value>
      <webElementGuid>85a5eaab-f3c5-4fa4-8479-1f765516e866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripcion de la Reunión:'])[1]/preceding::select[1]</value>
      <webElementGuid>c7877148-3577-4544-94b2-22c178313390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>e83ef5ee-ff19-4099-adfb-d617f270eae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idArmaUsadaI' and (text() = '
                             Ninguna 
                        ' or . = '
                             Ninguna 
                        ')]</value>
      <webElementGuid>b232a019-4475-45cc-b5b9-2bea136daea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
