<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacioenes_nueInci_inputProcedimiento</name>
   <tag></tag>
   <elementGuidId>647ab959-9515-4331-bffe-6197e348f927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tituloProtocoloInfringido</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tituloProtocoloInfringido']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tituloProtocoloInfringido</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3398a3c9-6859-42d4-8e75-01c206272102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tituloProtocoloInfringido</value>
      <webElementGuid>10303d17-af4b-401b-ade0-a9a05600d626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de4f304c-bb85-43eb-b15a-146827ea500e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Titulo</value>
      <webElementGuid>7edba824-13c2-4fbf-8407-b7c3e97b104f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tituloProtocoloInfringido&quot;)</value>
      <webElementGuid>c4721f1f-691d-46ca-9a54-d61a80813b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tituloProtocoloInfringido']</value>
      <webElementGuid>64da6327-e6cf-424c-957a-ae85cbf0f3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div/div[2]/div/div[3]/div[3]/input</value>
      <webElementGuid>3309b517-fd31-42eb-b4f8-4c0309ab3e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>bfd04054-e476-4d5b-8863-77a87ee095d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tituloProtocoloInfringido' and @type = 'text' and @placeholder = 'Titulo']</value>
      <webElementGuid>0168ea2c-7fb4-43a9-aa21-f6f2104ddd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nroProtocoloInfringido']</value>
      <webElementGuid>f808b8e4-84b2-4e72-8c76-dbaba6395020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>0c8c70cc-8414-4c75-9223-48a1e99affb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>5c6da524-3e43-416e-a564-7192c7d616d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nroProtocoloInfringido' and @type = 'number' and @placeholder = 'N°']</value>
      <webElementGuid>c6057e92-c6af-4367-8b20-1f5a59cc49dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
