<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_buttonEliminarApo</name>
   <tag></tag>
   <elementGuidId>396002ef-85fa-42fa-ba26-8ebd2a6c3e17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.i-red-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='eliminarApoderado()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Eliminar Apoderado&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07bd9011-48ba-4b4b-85a6-2f0da441d040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>eliminarApoderado()</value>
      <webElementGuid>1e1f60a5-d200-4902-94b4-dd5c38e73c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-red-button</value>
      <webElementGuid>b0619127-c615-41a3-aaff-61f30b2ae6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar Apoderado</value>
      <webElementGuid>1f56f2f2-54d9-484c-b759-6a6951b6fa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entrevista&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-row i-box-main&quot;]/div[@class=&quot;i-col-12&quot;]/div[@class=&quot;i-box-body&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-3 i-center&quot;]/div[@class=&quot;i-row i-center&quot;]/div[@class=&quot;i-col-12 i-center&quot;]/button[@class=&quot;i-red-button&quot;]</value>
      <webElementGuid>609ca5fc-73d4-4779-bbf4-34f98bd28dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='eliminarApoderado()']</value>
      <webElementGuid>8f06d2ed-eb73-4191-9f05-ba4c7976b9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[3]/div/div[2]/div/div[12]/div/div[2]/button</value>
      <webElementGuid>1c9062fb-c027-44ca-a759-2bd918c74acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar Apoderado'])[1]/following::button[1]</value>
      <webElementGuid>6930a92e-a53a-4b88-8c25-cfab3853aacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[11]/following::button[2]</value>
      <webElementGuid>6aa1b109-c06f-4756-8310-10ba136b3b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antecedentes de la reunión:'])[1]/preceding::button[1]</value>
      <webElementGuid>54181b2b-91a7-4395-bece-546907b3c6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminar Apoderado']/parent::*</value>
      <webElementGuid>6ae75625-e338-4d8b-9468-1acecf908301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/button</value>
      <webElementGuid>3b574c35-b3e5-4560-9bbe-66e5950c595a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Eliminar Apoderado' or . = 'Eliminar Apoderado')]</value>
      <webElementGuid>89b09a2b-5cca-413f-abd7-d499a08ad58b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
