<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectGravedadLesiones</name>
   <tag></tag>
   <elementGuidId>6806a2d3-b57e-4dbc-9a98-16abbc459a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idLesionIncidente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idLesionIncidente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idLesionIncidente</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8cbeb38f-8f1d-436b-b5c7-67bcd4f6bbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idLesionIncidente</value>
      <webElementGuid>491b68a0-9866-4fef-87b1-c7ce3586c6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>6b88d21a-0ab1-4175-b282-9eb6f821aa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                  Sin Lesiones    Lesión Mayor    Lesión Menor    Lesiones Fisicas Graves    Lesión Fatal                                              </value>
      <webElementGuid>a5948d34-2ed7-40ae-a899-c6ffbd476641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idLesionIncidente&quot;)</value>
      <webElementGuid>14b04459-2f41-4da5-bf67-1ff77014b0a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idLesionIncidente']</value>
      <webElementGuid>83c5136a-6c7b-4ffd-b447-7d389006e335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[5]/div/div[2]/div/div[2]/div/div[4]/select</value>
      <webElementGuid>ea107bfe-0c3a-42f2-9abe-aa07d2649cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gravedad de las lesiones:'])[1]/following::select[1]</value>
      <webElementGuid>aa7dfda9-15fd-44d8-bff7-78f5a896865c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gravedad de las heridas:'])[1]/following::select[2]</value>
      <webElementGuid>48f02721-291c-4834-be49-2aafe74bcf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjunte un documento(evidencia, registros...)'])[1]/preceding::select[1]</value>
      <webElementGuid>2d206d42-664d-4e60-8d9e-7bd121f5d7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículo o Protocolo infringido y/o Procedimiento'])[1]/preceding::select[1]</value>
      <webElementGuid>d75bf813-f60b-4287-a687-da88dac40954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[4]/select</value>
      <webElementGuid>4d7021e9-92f8-4c31-8a43-8cd4f00e5595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idLesionIncidente' and (text() = '
                                                  Sin Lesiones    Lesión Mayor    Lesión Menor    Lesiones Fisicas Graves    Lesión Fatal                                              ' or . = '
                                                  Sin Lesiones    Lesión Mayor    Lesión Menor    Lesiones Fisicas Graves    Lesión Fatal                                              ')]</value>
      <webElementGuid>706eb10c-b9ac-42a4-9d84-ac2001291647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
