<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_buttonAgregarApo</name>
   <tag></tag>
   <elementGuidId>dbf37d08-8afe-4509-891c-2c1664bcb6d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.i-blue-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='agregarApoderado()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Agregar Apoderado&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86e0db3a-07f4-441c-a730-1cea4ff93f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>agregarApoderado()</value>
      <webElementGuid>8e81bee5-8027-4d9c-8a6d-c8b9267f1530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>66886023-6e4f-4f57-a9ec-e3e318aa2b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar Apoderado</value>
      <webElementGuid>8edb7065-8c12-483f-9d61-ff8b107078c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entrevista&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-row i-box-main&quot;]/div[@class=&quot;i-col-12&quot;]/div[@class=&quot;i-box-body&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-3 i-center&quot;]/div[@class=&quot;i-row i-center&quot;]/div[@class=&quot;i-col-12 i-center&quot;]/button[@class=&quot;i-blue-button&quot;]</value>
      <webElementGuid>f3d7fd01-155a-4e2f-b380-974559b9b1f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='agregarApoderado()']</value>
      <webElementGuid>255ab21f-00fa-4707-82e0-6b700176556d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[3]/div/div[2]/div/div[12]/div/div/button</value>
      <webElementGuid>4bec45ab-376c-4497-a098-4683b2fe4a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[11]/following::button[1]</value>
      <webElementGuid>a76001a6-e35f-4c10-a9c9-b896e0175dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Apoderado'])[1]/preceding::button[1]</value>
      <webElementGuid>1095d263-23c5-4a9e-94d9-878dc856e183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antecedentes de la reunión:'])[1]/preceding::button[2]</value>
      <webElementGuid>2a3e67ca-028c-47a4-a6f9-035eac7599b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar Apoderado']/parent::*</value>
      <webElementGuid>fc7157d2-029b-48b2-93d6-10a671e164cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/button</value>
      <webElementGuid>8a5da074-dead-4cc1-a29e-88363359060f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Agregar Apoderado' or . = 'Agregar Apoderado')]</value>
      <webElementGuid>ddd08d22-78bd-4b57-8b11-dbf5273b40dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
