<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_selectCursoEstud</name>
   <tag></tag>
   <elementGuidId>3041825f-126a-4324-98d0-6d29079c9335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='curso']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#asistente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#asistente</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>24daa9b9-ecc4-41b5-98f5-7728858ae6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asistente</value>
      <webElementGuid>ec3f643b-95e2-4143-9aed-5e94c4dc2003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asistente</value>
      <webElementGuid>3095961e-10fc-4b66-99f0-473efc86abe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>1b7b95fe-795a-4d5d-bb83-d56dae8385a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Selecciona un asistente </value>
      <webElementGuid>0f5f55fb-ff5b-4b37-bf65-e26a0c6c1ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asistente&quot;)</value>
      <webElementGuid>b207eac0-b6e9-4388-a574-fe3e40d89182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='asistente']</value>
      <webElementGuid>1f55fa9b-bc40-4480-83e1-93c9c4a52935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[3]/div/div[2]/div/div[6]/select</value>
      <webElementGuid>859d5934-f1f3-4d8f-9fe6-94a8cbd56a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[9]/following::select[1]</value>
      <webElementGuid>baa49f13-d40d-4ee8-9715-f9dc2596b08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[10]/preceding::select[1]</value>
      <webElementGuid>0600fa88-df5c-4634-a7a2-17ab4e9eee51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/select</value>
      <webElementGuid>863b3b4e-b4a8-46c1-898b-e06af170f5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'asistente' and @name = 'asistente' and (text() = ' Selecciona un asistente ' or . = ' Selecciona un asistente ')]</value>
      <webElementGuid>12934085-cf9d-4768-bf0b-14d9803fb55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
