<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacioenes_nueInci_inputSeveridad</name>
   <tag></tag>
   <elementGuidId>f49af435-c147-4490-a4df-aa32ad0a1946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#severidadArtProtInfringido</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='severidadArtProtInfringido']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#severidadArtProtInfringido</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1956559-02a4-4974-a9bd-5f5ed0fb345d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>severidadArtProtInfringido</value>
      <webElementGuid>5b60fe53-b270-4eb2-b83b-2323430a12f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>2e021d1b-c446-4ebe-8ffb-c71dbdc56452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Leve
                                                Normal
                                                Grave
                                            </value>
      <webElementGuid>1bb8bf74-3184-49e3-a864-4725daa44e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;severidadArtProtInfringido&quot;)</value>
      <webElementGuid>7880cd85-e68c-4ccc-a095-1c05bda14873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='severidadArtProtInfringido']</value>
      <webElementGuid>455e4ed9-1c43-419f-8ddf-03095ab12630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div/div[2]/div/div[2]/div[2]/select</value>
      <webElementGuid>8c0a3bac-0a82-4251-ba9f-e7f7ca1414f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severidad:'])[2]/following::select[1]</value>
      <webElementGuid>8f94bee4-ecf8-4650-9b2b-92020a0d434c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículo o protocolo infringido:'])[1]/following::select[1]</value>
      <webElementGuid>8227b4ef-a0f1-400f-b833-e018a6e8a4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedimiento:'])[1]/preceding::select[1]</value>
      <webElementGuid>1345cebd-39df-48c7-ac6c-d986895a14bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir'])[1]/preceding::select[1]</value>
      <webElementGuid>d0416806-ba4b-475c-afe8-f2ecc76113a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/select</value>
      <webElementGuid>140d6e90-e496-482d-a7ee-0830af0a2952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'severidadArtProtInfringido' and (text() = '
                                                Leve
                                                Normal
                                                Grave
                                            ' or . = '
                                                Leve
                                                Normal
                                                Grave
                                            ')]</value>
      <webElementGuid>0130b520-c11e-4fb9-9a42-fc792d9c4ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
