<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectRolIncidente</name>
   <tag></tag>
   <elementGuidId>730215f6-9012-41e3-a7b0-348faf47f69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rolInvolucrado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rolInvolucrado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rolInvolucrado</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f88fa6e-4be0-422d-878b-018c713ce6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rolInvolucrado</value>
      <webElementGuid>99167a2b-52ff-491a-bd79-3b501014d70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>960a987c-4680-4d86-b141-42eba04c4bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                              Victima    Perpetrador    Testigo    Denunciante    Entrevistado    Entrevistador    Presidente del curso    Vicepresidente del curso    Tesorero del curso    Delegado del curso                                          </value>
      <webElementGuid>20e1a177-b7f8-4e92-a556-cb97df8bfb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rolInvolucrado&quot;)</value>
      <webElementGuid>5c80297d-74d9-47ea-884c-3a395068bbe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rolInvolucrado']</value>
      <webElementGuid>4a976a07-5e1f-4a07-b580-f37a0d79feaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[3]/div/div/div/div[2]/div[4]/div[2]/select</value>
      <webElementGuid>e9479ca1-baaf-41fa-8fb0-d1d6102acb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol en incidente:'])[1]/following::select[1]</value>
      <webElementGuid>62a3d6e7-35ee-45b1-a89c-de8e47838a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol involucrado:'])[1]/following::select[2]</value>
      <webElementGuid>20ff222d-0167-4a24-803c-cccbc4373665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persona Involucrada'])[1]/preceding::select[1]</value>
      <webElementGuid>dc825aac-2464-4721-91b9-70c3ab75fb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rol en la comunidad:'])[1]/preceding::select[2]</value>
      <webElementGuid>2f2d735f-81a9-452d-9ce5-945875995ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/select</value>
      <webElementGuid>b58e9a66-5fc5-4978-9498-7f5cdb927e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rolInvolucrado' and (text() = '
                                              Victima    Perpetrador    Testigo    Denunciante    Entrevistado    Entrevistador    Presidente del curso    Vicepresidente del curso    Tesorero del curso    Delegado del curso                                          ' or . = '
                                              Victima    Perpetrador    Testigo    Denunciante    Entrevistado    Entrevistador    Presidente del curso    Vicepresidente del curso    Tesorero del curso    Delegado del curso                                          ')]</value>
      <webElementGuid>e4489fcb-8673-4771-b9a9-5f075398d282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
