<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInci_selectGravedadHeridas</name>
   <tag></tag>
   <elementGuidId>50b5ffbc-9cc7-41e6-9ec9-a0b3feeb086c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idHeridadIncidente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idHeridadIncidente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idHeridadIncidente</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87257b51-5647-4491-a740-64cc68cde811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idHeridadIncidente</value>
      <webElementGuid>aefc65b0-b40a-4393-b674-fa88b7cc2126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>d2b9d0d5-b780-4c3e-a0f4-e556cdb3d0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                  Sin heridas    Herida grave    Herida menor    Herida corporal seria    Herida fatal                                              </value>
      <webElementGuid>ac331fa3-412c-4fd9-95f1-9c3447a32797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idHeridadIncidente&quot;)</value>
      <webElementGuid>92c4194c-f4f4-453d-afd4-19d7a139b95c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idHeridadIncidente']</value>
      <webElementGuid>de2c429d-78cb-4a84-a6b7-40d5c1459d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[5]/div/div[2]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>d2fd3202-edaf-4c78-b40d-342976ccc326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gravedad de las heridas:'])[1]/following::select[1]</value>
      <webElementGuid>fcafb507-59c7-4f6f-a1ee-4e301b51d84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripcion de la Reunión:'])[1]/following::select[1]</value>
      <webElementGuid>95eb38a0-f5f0-428f-a014-0745687a07d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gravedad de las lesiones:'])[1]/preceding::select[1]</value>
      <webElementGuid>576eccd4-0527-40a2-afa6-0255a9480fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjunte un documento(evidencia, registros...)'])[1]/preceding::select[2]</value>
      <webElementGuid>bee37f2a-f4e7-4427-a0fb-803f7dfa7574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>2eddb832-1150-469b-a04d-effcf2945b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idHeridadIncidente' and (text() = '
                                                  Sin heridas    Herida grave    Herida menor    Herida corporal seria    Herida fatal                                              ' or . = '
                                                  Sin heridas    Herida grave    Herida menor    Herida corporal seria    Herida fatal                                              ')]</value>
      <webElementGuid>487dea4d-31bf-440f-afac-3aac47f840c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
