<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueInci_buttonAadirArt</name>
   <tag></tag>
   <elementGuidId>776e2391-1366-45dc-9710-1b08fa973ab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='agregarProtocolo()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Añadir&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfe2fdde-5d3b-4590-bc49-6ddb4c0a7172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>agregarProtocolo()</value>
      <webElementGuid>d2ad8ac4-7491-4273-b433-9f704d7ac3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>a0bd5f2d-8a56-4c92-8474-6b2aed464311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Añadir </value>
      <webElementGuid>25a41ba7-0e4e-431c-b9e7-cebf99be793a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incidenteObs&quot;)/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-container&quot;]/div[@class=&quot;i-box-main&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-2 i-center&quot;]/div[@class=&quot;i-col-12 i-center&quot;]/button[@class=&quot;i-blue-button&quot;]</value>
      <webElementGuid>4ea7ee82-70a6-458b-a689-ed3b8ff402b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='agregarProtocolo()']</value>
      <webElementGuid>f94d3044-43ff-4053-b47f-f9d7d04be3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div[2]/div/button</value>
      <webElementGuid>fa4db207-0135-436b-9560-6d3932a71c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procedimiento:'])[1]/following::button[1]</value>
      <webElementGuid>e70f1150-626c-4f76-83c0-116e5ea39e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Severidad:'])[2]/following::button[1]</value>
      <webElementGuid>2382caa3-e1ba-4eba-8482-d4dbcb6aba99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quitar'])[1]/preceding::button[1]</value>
      <webElementGuid>7bcbbac1-a583-4180-83ff-03234d6761f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de Artículos o Protocolos y Procedmientos acordádos'])[1]/preceding::button[2]</value>
      <webElementGuid>3ca61b72-fb0f-450e-9d6b-2146d3d343b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Añadir']/parent::*</value>
      <webElementGuid>e3bd8f42-3236-4b0f-b09a-6d151c26caf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/button</value>
      <webElementGuid>357884bb-0df0-48bb-9cf8-3e912ccf35db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Añadir ' or . = ' Añadir ')]</value>
      <webElementGuid>931c4c37-5f5a-46f3-b719-80aacf4256e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
