<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_buttonagregar</name>
   <tag></tag>
   <elementGuidId>72997874-2a86-4604-a9ec-22b68d3ba038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.i-blue-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Agregar&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e92b465d-a384-4e42-95f7-a0999ced57b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59c9067f-3618-47ff-a514-15bd51a95f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-blue-button</value>
      <webElementGuid>00c2f63d-2397-4a93-bcbe-189fbaa5e7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>159d681a-73a4-4f77-87ab-f3f09f7f5408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>agregarAlumnoAlaAnotacion(0,1)</value>
      <webElementGuid>00902602-9916-4e97-8ddd-4448b77fcbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Agregar </value>
      <webElementGuid>bcaba807-f0d4-412c-b08c-7ac83a2062d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nueva&quot;)/div[@class=&quot;incidentes-container&quot;]/section[@class=&quot;alumnos-incidentes&quot;]/div[1]/div[@class=&quot;alumnos-incidentes_btn i-center&quot;]/div[@class=&quot;i-col-8&quot;]/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-12&quot;]/button[@class=&quot;i-blue-button&quot;]</value>
      <webElementGuid>9e2e97a3-1f1e-4e21-8821-bfa5d62bbe39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>f7a7e140-ebc2-4c7f-9d52-7919b3850480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nueva']/div/section[2]/div/div[2]/div/div/div/button</value>
      <webElementGuid>d6da310e-5ac9-458e-b818-ac2af806bec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar alumnos'])[1]/following::button[1]</value>
      <webElementGuid>522f9903-5049-42bb-97fd-8f423e93f60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::button[1]</value>
      <webElementGuid>7af736b2-33df-4cf4-be31-e290b4f3826e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista alumnos selecionados'])[1]/preceding::button[4]</value>
      <webElementGuid>6a39ce9a-1a27-4092-9763-dd8a5bca498e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalles de la Observación'])[1]/preceding::button[4]</value>
      <webElementGuid>42b96c60-cb98-4505-a963-e36e82b30757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar']/parent::*</value>
      <webElementGuid>d3d81ea6-19d0-4754-a50e-ce8c0b05363c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>79addc90-1e84-4d1d-8212-f3ae2c31ee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @href = '#' and (text() = ' Agregar ' or . = ' Agregar ')]</value>
      <webElementGuid>4d49577d-c8d6-4354-a857-1be676fc67be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
