<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_inputRelacion</name>
   <tag></tag>
   <elementGuidId>fa6fa63b-8a34-42a7-9951-23766c21995e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='relacionado_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#relacionado_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#relacionado_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7a9f3ab-7100-425a-9119-d14265080832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>relacion</value>
      <webElementGuid>967df049-9dc2-4394-918b-98ad2c480b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relacionado_id</value>
      <webElementGuid>f6f84e21-abf1-44d1-8d8d-8eb6a8a4c5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>fc8ce5b0-ae32-4874-8ed7-37f19d2d2e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                    Seleccione Tipo
                                                                </value>
      <webElementGuid>3162e9e0-c7f3-4288-b6d4-88675a132857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relacionado_id&quot;)</value>
      <webElementGuid>cab883b7-9b4f-45fa-a104-b020e153e9b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='relacionado_id']</value>
      <webElementGuid>28f8fd61-da20-4343-b88b-518a4221939b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nueva']/div/section[3]/div[2]/div/div/div/div/div[2]/div/div/div[5]/div/div/div/select</value>
      <webElementGuid>515e9140-b4d6-4d68-834a-143b991381b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relacionado:'])[1]/following::select[1]</value>
      <webElementGuid>548c68f0-325f-4564-93e5-662214410f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[4]/following::select[2]</value>
      <webElementGuid>2f107857-2e7e-4182-abe4-f0c775e37a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver eventos'])[1]/preceding::select[1]</value>
      <webElementGuid>6a0c8aab-e7da-4396-b36e-95b36c860a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear relacionado'])[1]/preceding::select[1]</value>
      <webElementGuid>279e2044-45b5-40f8-8746-89d489a10e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/select</value>
      <webElementGuid>1c9712b9-72bb-4057-9f5f-2858be85dac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'relacion' and @id = 'relacionado_id' and (text() = '
                                                                    Seleccione Tipo
                                                                ' or . = '
                                                                    Seleccione Tipo
                                                                ')]</value>
      <webElementGuid>163a6496-faec-4980-b128-09261b0a7c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
