<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacioenes_nueInci_inputProcedimiento (1)</name>
   <tag></tag>
   <elementGuidId>b28c1bef-a132-4620-af67-a643b2690a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tituloProtocoloInfringido</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tituloProtocoloInfringido']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tituloProtocoloInfringido</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2f87a26-faeb-4c18-82c0-23de5274ecd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tituloProtocoloInfringido</value>
      <webElementGuid>03714d00-8830-48f0-bcf5-e1444b524c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3764a905-8c1f-404c-bcb5-bf7c3cf886fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Titulo</value>
      <webElementGuid>a87bc77c-bfdc-42c3-9e3a-ffaaf0fb0e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tituloProtocoloInfringido&quot;)</value>
      <webElementGuid>2e8c37fb-bfae-430b-b255-14cb3a3fe66e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tituloProtocoloInfringido']</value>
      <webElementGuid>ead4be6a-ec82-4178-a096-3deb0e71ca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[4]/div[6]/div/div/div[2]/div/div[3]/div[3]/input</value>
      <webElementGuid>8d4870b0-dc28-4237-9e5f-6414679b0988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>0da912ae-dced-46f6-8789-027fb980d00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tituloProtocoloInfringido' and @type = 'text' and @placeholder = 'Titulo']</value>
      <webElementGuid>b94b9a72-cca9-4832-9ebd-d13b3b46fe80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
