<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observaciones_nueEntre_textRegistroDetallado</name>
   <tag></tag>
   <elementGuidId>bf21e601-6f76-4cc0-8303-6ef09a102d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descripcionEntrevistaLarga</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='descripcionEntrevistaLarga']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#descripcionEntrevistaLarga</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0c1a6b8a-b194-44ca-b76d-3a15e68455d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descripcionEntrevistaLarga</value>
      <webElementGuid>b435af07-57a1-47d7-8111-303daf9864a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>1c65a10b-59f1-4c23-821d-973b0191abfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripcion de la reunion...</value>
      <webElementGuid>6c9d5b5b-fac5-448e-8e76-037aa770bfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descripcionEntrevistaLarga&quot;)</value>
      <webElementGuid>8e468a4e-c56d-4c25-934f-3628a3ace1bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='descripcionEntrevistaLarga']</value>
      <webElementGuid>f62e1c47-5e3f-4238-ab45-2323754658a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entrevista']/div/div[4]/div/div[3]/div/textarea</value>
      <webElementGuid>d7717b53-7bfa-4c91-ae66-eb3cfeb0d653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/textarea</value>
      <webElementGuid>36aec090-37bd-4df7-b920-5437d480efe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'descripcionEntrevistaLarga' and @placeholder = 'Descripcion de la reunion...']</value>
      <webElementGuid>10d5a9b3-f9b7-44de-b41f-c8b049ceb2a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
