<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_observacion_nueInci_selectCuando</name>
   <tag></tag>
   <elementGuidId>a4ac700d-3434-4876-b72c-72c124072cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idRefCuando']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idRefCuando</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#idRefCuando</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ace7085-e4fb-4ed4-88a5-6e02f5518a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idRefCuando</value>
      <webElementGuid>601f722f-0b63-477a-891f-0b99a5335588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>c0181d61-3b17-4491-8c9a-135a399035c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                  Después de clases    Antes de clases    Durante la clase    Durante el almuerzo/receso    durante el paso    Actividad no patrocinada por la escuela    En el camino de la escuela    De camino a la escuela    Otro tiempo durante el horario escolar    Otro tiempo fuera del horario escolar    Actividad patrocinada por la escuela    Desconocido                                              </value>
      <webElementGuid>18139330-457a-4f0a-8eb0-eaa15742b853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idRefCuando&quot;)</value>
      <webElementGuid>cacc746d-5dee-4bb1-8b85-370c799c5033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idRefCuando']</value>
      <webElementGuid>e9758f09-b4ea-4237-871a-e935109834e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incidenteObs']/div/div[2]/div/div[2]/div/div/div[2]/div[2]/div[2]/select</value>
      <webElementGuid>c4b38997-795e-4010-a53a-7a874fa06174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuando:'])[1]/following::select[1]</value>
      <webElementGuid>de2a0250-c43d-4b57-81f2-ec4350c36682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso asociado:'])[1]/following::select[2]</value>
      <webElementGuid>2d87b5c3-8132-40b6-97d6-91df0177a653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donde:'])[1]/preceding::select[1]</value>
      <webElementGuid>ac673e17-aae7-4488-b66c-2700985f314e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denunciante:'])[1]/preceding::select[2]</value>
      <webElementGuid>fc26a44c-c888-42d7-9c98-9375af4d8703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>593abc7b-b2f0-4745-87fa-06c7f07b6bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idRefCuando' and (text() = '
                                                  Después de clases    Antes de clases    Durante la clase    Durante el almuerzo/receso    durante el paso    Actividad no patrocinada por la escuela    En el camino de la escuela    De camino a la escuela    Otro tiempo durante el horario escolar    Otro tiempo fuera del horario escolar    Actividad patrocinada por la escuela    Desconocido                                              ' or . = '
                                                  Después de clases    Antes de clases    Durante la clase    Durante el almuerzo/receso    durante el paso    Actividad no patrocinada por la escuela    En el camino de la escuela    De camino a la escuela    Otro tiempo durante el horario escolar    Otro tiempo fuera del horario escolar    Actividad patrocinada por la escuela    Desconocido                                              ')]</value>
      <webElementGuid>5e55ebcf-1767-4669-ab6d-2740dd34ff6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
