<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lobroDigital_observaciones_textDescripcion</name>
   <tag></tag>
   <elementGuidId>26808710-82df-4aa2-b91a-7898ccccb498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='anotacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anotacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Escriba su observación&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>056933ea-a0ff-4fbd-bc68-06fe88b91a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anotacion</value>
      <webElementGuid>bff09040-5612-4cdf-a7f1-d479b0ac9ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anotacion</value>
      <webElementGuid>1605a22c-056c-4b5b-9840-afa39fb3a2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCustom</value>
      <webElementGuid>cba81a26-b2ef-4ed2-a41b-365353386207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fb8d8bf4-3306-4408-8da2-5f8982e9244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escriba su observación</value>
      <webElementGuid>10190e6e-3f33-417b-87a2-6d527328100a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anotacion&quot;)</value>
      <webElementGuid>af40808b-b7fb-4c85-8ce2-9b23b88ee49d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='anotacion']</value>
      <webElementGuid>856537ab-03fa-4325-80de-7bd6ca4d4b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nueva']/div/section[3]/div[2]/div/div/div/div/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>9c3aa216-be2c-4ca2-8999-f17c852cdf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4ab69010-3ebf-4c02-ac78-1e1552240f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'anotacion' and @id = 'anotacion' and @placeholder = 'Escriba su observación']</value>
      <webElementGuid>749fcce1-d215-402f-8c2f-f1da197a865e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
