<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cursos2025_inputCapasidadAlumnos</name>
   <tag></tag>
   <elementGuidId>53b10c5d-f83c-4d4a-9512-1f856e083b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cap_alumnos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cap_alumnos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;-Ej: 35-&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dc92102-f496-4379-b7a8-5e034ff84b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>98e3cb04-a65d-4f0d-a4b2-fb4c620f5f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cap_alumnos</value>
      <webElementGuid>6d038f79-b1b6-4270-b675-5df7a4d637e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4414e06b-9cc0-4a3c-a823-cc278651cca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable form-control</value>
      <webElementGuid>bcf407ab-d3fd-4a08-9f32-627106bfd1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Ej: 35-</value>
      <webElementGuid>f5fc8b9f-9dd0-4e3c-a5c5-e3b6aed9dc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cap_alumnos&quot;)</value>
      <webElementGuid>cf3cc3dd-fe16-4a16-a081-e2bc7557e305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cap_alumnos']</value>
      <webElementGuid>3069446c-b8f6-4526-8ecb-5af9c732d69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr/td/table/tbody/tr/td[10]/input</value>
      <webElementGuid>d8cb8b59-a656-40a2-a017-81712e03a2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>075583a2-f3ba-42b0-b5cf-0a49fcff698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'cap_alumnos' and @placeholder = '-Ej: 35-']</value>
      <webElementGuid>ccfcab3a-5f31-451a-9afb-4b266fa40129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
