<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cursos2025_buttonEliminar</name>
   <tag></tag>
   <elementGuidId>c43d233f-5a2b-4c1a-8885-3b6a9576b3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lista_cursos']/table/tbody/tr[2]/td[7]/table/tbody/tr/td[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;219907 A Nivel Medio Menor A 10 40 0&quot;s] >> internal:role=link >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7e0e41b9-1be0-4dad-838c-ae44fbfa89f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash</value>
      <webElementGuid>88c85050-14ae-4694-abb7-7cba988b2b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cabd598a-3d17-4d84-ab61-3920830007f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Eliminar curso</value>
      <webElementGuid>28601586-eca3-4369-bb67-f9f1adf9016d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lista_cursos&quot;)/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[2]/td[7]/table[1]/tbody[1]/tr[1]/td[3]/a[1]/i[@class=&quot;fa fa-trash&quot;]</value>
      <webElementGuid>4d9b8aef-17cd-41e7-9768-e9480f37b4e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lista_cursos']/table/tbody/tr[2]/td[7]/table/tbody/tr/td[3]/a/i</value>
      <webElementGuid>3b21f5fb-3ff2-454d-9fd0-3772593be81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/i</value>
      <webElementGuid>957c6b3f-68d4-436e-8201-ad640ff81ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Eliminar curso']</value>
      <webElementGuid>ba384d9a-bfa7-48b9-8af3-583b09f03e67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
