<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_matricula_cursos2025_selectLetraCurso</name>
   <tag></tag>
   <elementGuidId>741f5a07-a6c7-4668-a66b-7206161e5755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='letra']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#letra</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#letra</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1af00a7d-876c-49ab-8ffd-f27b155d8801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>letra</value>
      <webElementGuid>e5dfd4cf-40e6-4969-b03e-584d99796a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>52c69168-d1f6-4c1e-8311-533bb6a9d505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            A
                                                                B
                                                                C
                                                                D
                                                                E
                                                                F
                                                                G
                                                                H
                                                                I
                                                                J
                                                                K
                                                                L
                                                                M
                                                                N
                                                                Ñ
                                                                O
                                                                P
                                                                Q
                                                                R
                                                                S
                                                                T
                                                                U
                                                                V
                                                                W
                                                                X
                                                                Y
                                                                Z
                                                        </value>
      <webElementGuid>18ce56aa-d6fd-4cc7-809c-bc6bfbce0319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;letra&quot;)</value>
      <webElementGuid>6fd0c1b9-acf4-42ec-bdd6-b8d711debff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='letra']</value>
      <webElementGuid>18a61e07-d4cd-4ffc-b9f6-93bf88e5b8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/table/tbody/tr/td/table/tbody/tr/td[6]/select</value>
      <webElementGuid>34e950ae-b2bd-47ec-9832-055ccfec9b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Letra :'])[1]/following::select[1]</value>
      <webElementGuid>bfce7323-5d94-447a-9920-ad4f5f9f819f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel :'])[1]/following::select[2]</value>
      <webElementGuid>89dc3716-1835-4e5d-b4bc-6fa58ac06d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cód. tipo enseñanza :'])[1]/preceding::select[1]</value>
      <webElementGuid>b5fff23f-ea60-4034-9804-1c4101267777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capacidad de alumnos :'])[1]/preceding::select[2]</value>
      <webElementGuid>d71f9d45-b409-4777-9dfd-3d2a5dfcd008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/select</value>
      <webElementGuid>8e9601b3-67c3-4261-aa58-d0bbf1c9c933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'letra' and (text() = '
                                                            A
                                                                B
                                                                C
                                                                D
                                                                E
                                                                F
                                                                G
                                                                H
                                                                I
                                                                J
                                                                K
                                                                L
                                                                M
                                                                N
                                                                Ñ
                                                                O
                                                                P
                                                                Q
                                                                R
                                                                S
                                                                T
                                                                U
                                                                V
                                                                W
                                                                X
                                                                Y
                                                                Z
                                                        ' or . = '
                                                            A
                                                                B
                                                                C
                                                                D
                                                                E
                                                                F
                                                                G
                                                                H
                                                                I
                                                                J
                                                                K
                                                                L
                                                                M
                                                                N
                                                                Ñ
                                                                O
                                                                P
                                                                Q
                                                                R
                                                                S
                                                                T
                                                                U
                                                                V
                                                                W
                                                                X
                                                                Y
                                                                Z
                                                        ')]</value>
      <webElementGuid>181297b9-0151-416e-a5f9-b72c799acc2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
