<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Listado</name>
   <tag></tag>
   <elementGuidId>83f65a67-2637-461a-b6ca-b904c5400149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='administracion'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Listado&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a73b992-e2ba-4b46-a890-999442584c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>administracion</value>
      <webElementGuid>8c99c16a-9987-400c-867f-8410e52acfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect active</value>
      <webElementGuid>12d6335b-a39a-444f-8c1f-3f23e05ff3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sistema/webclass/home/administracion/detalleCursos.php</value>
      <webElementGuid>761a9544-2126-4348-983c-aa4963d81dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>/sistema/webclass/home/administracion/detalleCursos.php</value>
      <webElementGuid>f9abb9c0-9bed-4076-8d76-bac9ca45b17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                 Listado
            </value>
      <webElementGuid>e19ae1d8-90f7-4974-a72a-62cb9bc04502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-menu&quot;)/ul[1]/li[@class=&quot;has_sub list-administracion active&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;active&quot;]/a[@id=&quot;administracion&quot;]</value>
      <webElementGuid>f31b61ff-aa1e-43d2-8368-42d83be931d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='administracion'])[2]</value>
      <webElementGuid>e2aad7d3-7421-4d6b-b825-45578a51c304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-menu']/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>c2178ae8-0912-457c-ba5a-ed875584a2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro digital'])[1]/following::a[2]</value>
      <webElementGuid>faeeadea-2167-4dd5-8252-53cb73e91d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/following::a[3]</value>
      <webElementGuid>2592e4c6-2ab1-47d0-bc6a-3e0f52551732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro de clase'])[1]/preceding::a[1]</value>
      <webElementGuid>fa7d449a-4670-4800-85cf-fe0086c81e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matrícula'])[2]/preceding::a[2]</value>
      <webElementGuid>8a00afc5-6281-4a68-9a44-16d3767fdde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/sistema/webclass/home/administracion/detalleCursos.php')])[3]</value>
      <webElementGuid>7c0c25ea-5baa-4f67-9972-a36e87517b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>e64a0c50-1403-41f6-90c1-72f6af7b3526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'administracion' and @href = '/sistema/webclass/home/administracion/detalleCursos.php' and (text() = '
                 Listado
            ' or . = '
                 Listado
            ')]</value>
      <webElementGuid>e2cccca9-2ef5-4ec4-aaad-a9eca5ae7f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
