<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>aef13eee-c0a0-421b-a4af-7f17491602a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[12]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admin usuarios&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5f80b1e-aa4e-4880-af55-912606a046a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../css/img/libroclases.png</value>
      <webElementGuid>05115756-1f1b-4d28-b74c-eba36238ba97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30px</value>
      <webElementGuid>d34d2b2b-1647-44f5-9bd9-8df10f6a6298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-webclass&quot;]/div[@class=&quot;container-fluid&quot;]/ul[@class=&quot;list-group list-group-horizontal-sm w-auto&quot;]/li[@class=&quot;list-group-item&quot;]/a[1]/img[1]</value>
      <webElementGuid>0502007f-c7bd-4200-98a0-67944d3316df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/a/img</value>
      <webElementGuid>0fc127f7-57d9-41fc-b3df-09a5964b69c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../css/img/libroclases.png']</value>
      <webElementGuid>f6c87f54-f76c-4dda-99de-928defa0e462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
