<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_selectCurso</name>
   <tag></tag>
   <elementGuidId>57fc5692-8263-4d80-bc6f-96b8afce19c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cursos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cursos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cursos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8676ab9b-b7a4-428f-9068-df49d45b66c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>a73d3c17-25b0-48ed-9e55-d7bddc842deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>13c57dad-bb77-4cab-aaa0-8f6a3f592ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cargarAsignaturas(this.value, 22, 0, 0, 0)</value>
      <webElementGuid>998f4026-379d-40d1-9399-1cc64f0fb7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A</value>
      <webElementGuid>1ce27d58-b870-41e4-ac97-ec1fe560145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursos&quot;)</value>
      <webElementGuid>a89eafa7-7f5a-4412-9c4e-83245daf8df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ifraime_notas</value>
      <webElementGuid>a3ccc145-31fb-4058-9721-1d32309de5a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cursos']</value>
      <webElementGuid>4f3926ec-1eb7-4ac8-a53e-f8cccf39e2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/select</value>
      <webElementGuid>9c8a7e3c-3d59-4979-9f79-a5e690068b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::select[1]</value>
      <webElementGuid>9db71a49-4ca4-4636-8d7a-ef587a9db72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año:'])[1]/following::select[2]</value>
      <webElementGuid>cf50348f-8493-4ecf-a534-7362d0b9fa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignatura:'])[1]/preceding::select[1]</value>
      <webElementGuid>acc45aec-089e-43bd-b9ed-992d74523593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Período:'])[1]/preceding::select[2]</value>
      <webElementGuid>e6d9e7c9-d9b1-47bc-92a5-e261adc48e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>33e4ef70-5749-4466-ac4b-403bbd968f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cursos' and (text() = 'Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A' or . = 'Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A')]</value>
      <webElementGuid>790507a8-35a4-490a-88ad-b26ba7b060e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
