<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Todos los cursos (2024)Pre Kinder AK_26ae2f</name>
   <tag></tag>
   <elementGuidId>cf2563de-61bf-4165-bd52-7bea1d559fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cursos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cursos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cursos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80f6e767-17c2-4c16-9a07-928896a93646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>160708a5-0abb-4c86-91d8-f4ee314a6843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>74a48757-554f-4791-a30f-d8af5c121058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e250f4b0-4d66-4b83-bafd-0a94c396dca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>generarCabeceraGrillaPrincipal(this.value, 0); cargar_detalle_fotos(); mostrar_herramientas();</value>
      <webElementGuid>08dddb84-8cee-4f68-bd6c-d35633629ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Todos los cursos (2024)Pre Kinder AKinder APrimero Básico APrimero Básico BSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BQuinto Básico BSexto Básico ASexto Basico BSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio CSegundo Medio ATercero Medio AIII° medio Cpráctica mecánicaCuarto Medio Acuarto medio B le</value>
      <webElementGuid>aadd6bb8-e001-4972-b1e9-c240275af860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursos&quot;)</value>
      <webElementGuid>5aff54b6-7ec9-4454-b828-81a46ee571c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cursos']</value>
      <webElementGuid>f3a49d78-f3ef-4662-98c5-9ae2bba6438d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div[3]/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>b04b4f1f-bbd1-4856-b32f-0f3dab18c0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::select[1]</value>
      <webElementGuid>0c74edac-3c6b-4cbe-a5ab-1eff656ab13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto'])[1]/preceding::select[1]</value>
      <webElementGuid>d11e5aa4-9c0c-48dc-8be3-c817ae1d2782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUT'])[1]/preceding::select[1]</value>
      <webElementGuid>1a433da7-7da9-4977-b7a2-be4e4b3982f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>291596ca-ce06-479f-aa6f-16c1c43ff91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cursos' and @id = 'cursos' and (text() = ' Todos los cursos (2024)Pre Kinder AKinder APrimero Básico APrimero Básico BSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BQuinto Básico BSexto Básico ASexto Basico BSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio CSegundo Medio ATercero Medio AIII° medio Cpráctica mecánicaCuarto Medio Acuarto medio B le' or . = ' Todos los cursos (2024)Pre Kinder AKinder APrimero Básico APrimero Básico BSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BQuinto Básico BSexto Básico ASexto Basico BSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio CSegundo Medio ATercero Medio AIII° medio Cpráctica mecánicaCuarto Medio Acuarto medio B le')]</value>
      <webElementGuid>27d7d415-2eb4-44e7-b62f-5fcc804d637a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
