<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_selectViveCon</name>
   <tag></tag>
   <elementGuidId>efa2c8b9-0afb-41b5-8225-f13d345d8a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vive_con']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vive_con</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#vive_con</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>62b08733-bb7d-4ba8-bdb1-e6f85cb7370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vive_con</value>
      <webElementGuid>8ebae1a0-2974-48ba-9536-19e717465346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vive_con</value>
      <webElementGuid>a25ba196-9bf2-435b-977d-0e4bf3870136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>MostrarViveOtros(this.value)</value>
      <webElementGuid>870d402d-0dad-42f1-8572-5c2dff526599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>ff6b82e6-b117-4b7a-9b31-b2c3565fdeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                     No especifica                            
                                                         Padres                            
                                                         Papá                            
                                                         Mamá                            
                                                         Otros                            
                                                </value>
      <webElementGuid>6c795a35-eee1-48a3-9733-aaee87a7adda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vive_con&quot;)</value>
      <webElementGuid>85122dcb-5f9a-40f8-9e77-4203439a4ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vive_con']</value>
      <webElementGuid>1933350f-9895-48ec-8701-77a9c6f78aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>cc864faa-eef7-44c6-919e-e41dbef84e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[51]/following::select[1]</value>
      <webElementGuid>9bcb50cd-af84-4516-9fe4-2e562be03b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumno vive con'])[1]/following::select[1]</value>
      <webElementGuid>33988b51-6484-4b22-81ff-8bbc3edfa701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N° de personas del grupo familiar'])[1]/preceding::select[1]</value>
      <webElementGuid>a8ba535e-2598-46c6-b66d-4603f037b16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[52]/preceding::select[1]</value>
      <webElementGuid>47846193-d9b6-4f67-b4ca-34d3d46c83ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>55189350-9b30-41de-ab4c-8ab52fd02423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'vive_con' and @id = 'vive_con' and (text() = '
                                                     No especifica                            
                                                         Padres                            
                                                         Papá                            
                                                         Mamá                            
                                                         Otros                            
                                                ' or . = '
                                                     No especifica                            
                                                         Padres                            
                                                         Papá                            
                                                         Mamá                            
                                                         Otros                            
                                                ')]</value>
      <webElementGuid>2f07de6a-e812-456c-bf5a-de8d34382489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
