<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputAnioIngreso</name>
   <tag></tag>
   <elementGuidId>e9edc814-05fd-4b4f-a9ba-07ed12a28cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anio_ingreso']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anio_ingreso</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#anio_ingreso</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7981618c-fa40-4e9b-a2d8-75b851639faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea39ca46-4c19-4675-9d64-dd647389c1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ae0fa4db-19e8-475f-b060-8f41c2a87bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anio_ingreso</value>
      <webElementGuid>cab742e6-2b3d-415c-bfc1-0241932cb2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anio_ingreso</value>
      <webElementGuid>751d873b-114d-4e08-873f-8a137a0e93b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>af438058-7c9f-446a-b577-e7da4baf2547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>e3501a0e-4685-4465-8f70-023582d7689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anio_ingreso&quot;)</value>
      <webElementGuid>c5a6b0f2-bccb-40cf-9c88-cdae158f4eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anio_ingreso']</value>
      <webElementGuid>e1924837-97df-48ab-9c73-61fe6f36a89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>d4d3b813-4a6d-47f1-9091-becc372c4624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div/table[2]/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>a5a03fd4-9108-4696-a131-52f0ff18498b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'anio_ingreso' and @id = 'anio_ingreso']</value>
      <webElementGuid>f013a405-49a4-486a-aaec-509134ec45d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
