<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_numMatricula</name>
   <tag></tag>
   <elementGuidId>44478978-982d-4b4a-b3a4-25b54ac9bb27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_matricula']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n_matricula</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_matricula</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dec2777-208f-4fb1-94b3-a44c71ebc11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57a1756a-6d6f-4e30-86e1-af5693d92e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>n_matricula</value>
      <webElementGuid>cba0e992-93b5-4149-92bb-ffd57fd480a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_matricula</value>
      <webElementGuid>d5df3bd8-d8f9-4d44-b3af-4b707e5be41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1234</value>
      <webElementGuid>5b6f9702-37f9-4134-81ba-9c4b93031825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>ddcbfad8-24c7-4d2b-88de-9e140246fdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_matricula&quot;)</value>
      <webElementGuid>982ca808-523e-4067-80c5-0a086e504d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_matricula']</value>
      <webElementGuid>c7a25338-e6b6-4f8e-8fb6-30811e8eb2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_2']/tbody/tr/td[2]/input</value>
      <webElementGuid>1ca52c42-e951-4f17-a27e-1673dcf320a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>753c0c2e-61a2-462d-9b43-d16b4b0d8b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'n_matricula' and @id = 'n_matricula']</value>
      <webElementGuid>a3f13604-c541-45d7-bf00-3ff949bea20b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
