<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_check3eraColacion</name>
   <tag></tag>
   <elementGuidId>4bed4fcb-461e-4cf4-8960-2e29ddbe4867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OtrBen2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OtrBen2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;3era colación&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6021c66-c3be-427f-83ad-06ac6024c170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d21a630c-2043-4e0c-a04a-d53d9ac6e64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtrBen2</value>
      <webElementGuid>ab823e43-a626-42fc-b759-64305f43df63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtrBen2&quot;)</value>
      <webElementGuid>8bb21d50-d4ea-44a4-83f9-7c4209f751e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OtrBen2']</value>
      <webElementGuid>34d371a8-add2-4dca-a644-8ec10ea6e2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='otros_beneficios']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b2f2dce5-1150-4896-ab2a-15eb31ef67f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>06c71ad8-fa72-4d1d-9141-63007870bba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'OtrBen2']</value>
      <webElementGuid>59a9c7a4-ba42-4a90-959f-e3f2b2959b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
