<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_checkUtilesEscolares</name>
   <tag></tag>
   <elementGuidId>27e7aeee-f3a7-4eef-a290-00e855b49080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OtrBen3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OtrBen3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Utiles escolares&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63bd8f8d-ce98-4fd7-a281-635372f77962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8416a2ad-6323-4cb8-b936-2c816dc66ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtrBen3</value>
      <webElementGuid>2d8a9e33-9a54-45b7-aa90-96c08dd35fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtrBen3&quot;)</value>
      <webElementGuid>b7d7c056-7e40-4744-bcdf-674162b069d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OtrBen3']</value>
      <webElementGuid>cd54ba60-82f9-40d3-9e47-f8d61562516a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='otros_beneficios']/table/tbody/tr/td[3]/input</value>
      <webElementGuid>7b54ea88-3ed5-4459-ab3d-7674fe3dd738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>c19cd450-6672-4657-b943-59a70ee5dd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'OtrBen3']</value>
      <webElementGuid>13517a65-90af-4ed2-ae3c-20ceed7c8a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
