<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputNumLugarEntreHermanos</name>
   <tag></tag>
   <elementGuidId>f1d1c0bc-dcc9-4d50-9714-40c572e2834c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_leh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n_leh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_leh</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d1f981b-af38-4d14-a851-b2a53b59bb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65bc6f70-ef3b-4d37-8f8e-a77b624b054d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>39</value>
      <webElementGuid>ebc21942-78ab-47ab-93a3-73772567756d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a9dd23ed-4f88-46b0-9de1-98109879e899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_leh</value>
      <webElementGuid>eceb15ab-6d7c-45e0-a2e1-c5ce2a235f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &amp; lt; 48) || (event.keyCode &amp; gt; 57)) event.returnValue = false;</value>
      <webElementGuid>09da7d76-6f9a-4305-8b33-feadc1f33946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>302ebff6-7a10-4c94-a377-77ef4d9187c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_leh&quot;)</value>
      <webElementGuid>18c7c1ca-edbf-4a54-ab1f-3c1240854f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_leh']</value>
      <webElementGuid>51d8e932-2f87-4c23-adbf-15425513e675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>bbd59937-7a32-461b-a516-a7c61c419de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>d83969b7-9572-4270-b6d8-d2a91d278ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'n_leh']</value>
      <webElementGuid>e5fdb493-f39d-44f7-a3ba-84d8463b2312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
