<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_selectTipoDocApo</name>
   <tag></tag>
   <elementGuidId>ead4ff0d-c4fc-4401-a9c0-497287f2d648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='e_apo_doc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_doc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#e_apo_doc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>71c67c22-577a-4b62-bc99-8863a5f45e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac28d495-03d8-44af-8738-01b547db2fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_doc</value>
      <webElementGuid>46cd6579-e739-40c2-92c6-a32fb8376b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_doc</value>
      <webElementGuid>27f4e7f8-8c5d-4aa0-9537-ffca76c14602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            RUN
                                                Pasaporte
                                        </value>
      <webElementGuid>01f14829-efce-4ecf-bc90-91e1f2300a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_doc&quot;)</value>
      <webElementGuid>c1924c55-8b0e-4be0-84be-502656ebf322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e_apo_doc']</value>
      <webElementGuid>24a070c4-f45a-4d9a-b854-0c295c8e0a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[3]/td/select</value>
      <webElementGuid>dca81231-8c27-4611-b305-d4c4ee2f3732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rut/Pasaporte:'])[1]/preceding::select[1]</value>
      <webElementGuid>562929e9-5b3b-476d-88a3-a6da499210ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/table/tbody/tr[3]/td/select</value>
      <webElementGuid>ea4a4258-1514-46e2-aeab-ae55757b0240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e_apo_doc' and @name = 'e_apo_doc' and (text() = '
                                            RUN
                                                Pasaporte
                                        ' or . = '
                                            RUN
                                                Pasaporte
                                        ')]</value>
      <webElementGuid>7ae18dc3-c007-4490-8c64-f10a1500ee78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
