<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputSistemaSaludApo2</name>
   <tag></tag>
   <elementGuidId>87b4218d-ce04-449d-9f53-6eb3d2c88d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e_apo_sal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_sal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;FONASA/ISAPRE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d29dd25-c5c5-48a1-82df-12a798a8d2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>980dcfdb-d9c7-4c4e-b629-f503f667b24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28847802-20c2-4940-aaa3-83b526878718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_sal</value>
      <webElementGuid>d62fa77d-037c-467e-b127-44bab697f0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_sal</value>
      <webElementGuid>1c46e40b-88be-4521-ab13-a0c0ebcf3a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>FONASA/ISAPRE</value>
      <webElementGuid>7b3649a1-63fa-4928-a7a4-8d8f2c53818d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_sal&quot;)</value>
      <webElementGuid>1a853d6e-bfd0-4c55-bd32-6c3b7e58c347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e_apo_sal']</value>
      <webElementGuid>310fb70e-18ea-4fc6-8090-a0729f223bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>1575e0bf-50e0-4dac-a946-f31eda38087a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>67042f28-49fc-405d-ab3b-44e11ffbbaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'e_apo_sal' and @name = 'e_apo_sal' and @placeholder = 'FONASA/ISAPRE']</value>
      <webElementGuid>f53d7d05-59fd-4042-9049-5a9a5826214b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
