<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputNumHermanosEnCole</name>
   <tag></tag>
   <elementGuidId>acd6d76e-49b7-4796-b071-22d43ac88a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_dhmec']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n_dhmec</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_dhmec</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3281fc3f-ad04-46e4-81f0-214e7a2f5fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d97bead-e403-4d74-8c3f-156effd05718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>d7d164e3-122d-44f2-ba17-385f7e812956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>59904b3a-b8cb-49cd-b67f-df4db1b9ce3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_dhmec</value>
      <webElementGuid>1bb44408-f89e-47b1-b527-748fdb0194aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &amp; lt; 48) || (event.keyCode &amp; gt; 57)) event.returnValue = false;</value>
      <webElementGuid>efeefc81-8d1b-4189-8e2d-c74f5a559a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5ddc8a55-b634-4353-8353-61701ddfad57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_dhmec&quot;)</value>
      <webElementGuid>dd81464c-4d1e-4cff-a2b2-669300b605e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_dhmec']</value>
      <webElementGuid>26b83156-39fb-4413-b148-a8d766281056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>b5ed8ae0-fb78-457a-816b-246199c9f178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>9194098f-83da-4c8e-8bbf-e5e62cb95857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'n_dhmec']</value>
      <webElementGuid>4e10ac5d-1ffa-4642-8b20-910659b785fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
