<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputRut</name>
   <tag></tag>
   <elementGuidId>cf1ae812-bc40-459e-8e59-5dcc408ec156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ej: 12123123-2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbd146b1-edc4-4ed7-81bd-282ec152da02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f602e610-af1d-4127-ab7a-b6d19f88d7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rut</value>
      <webElementGuid>d8bdea74-1b28-4d85-94b0-d992d32ba502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rut</value>
      <webElementGuid>017ba31c-b775-425b-aedc-158d88ccc152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RUT sin puntos y con guión</value>
      <webElementGuid>ddc4729c-b0db-4311-a8ee-ba72f71c02a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>da202a1f-4a5e-45e8-9ba2-0af5d6b5eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24173499-4</value>
      <webElementGuid>5541611e-3f7d-4ecb-9238-7c07513cfa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limpiarRut(this.value, 1)</value>
      <webElementGuid>b2ca7892-8f3c-411c-afef-5a98d4e9f973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validarRut(this.value, 1);</value>
      <webElementGuid>960f7e05-fc2c-4f20-8099-0658baab7104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej: 12123123-2</value>
      <webElementGuid>c989d726-b167-4e5d-be87-7b07bb9651c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>98a1409f-5389-4b97-88f3-bf01864259c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rut&quot;)</value>
      <webElementGuid>9cd24795-164f-417f-8203-e116b20c2e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rut']</value>
      <webElementGuid>f9e4331f-ab23-40c6-894e-7c83eae6e297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='checknacional']/td[2]/input</value>
      <webElementGuid>0f18c935-b9b3-4c70-9bcb-8f056378964f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>3be70c41-5183-4bdc-8525-425e1717f3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'rut' and @name = 'rut' and @title = 'RUT sin puntos y con guión' and @placeholder = 'Ej: 12123123-2']</value>
      <webElementGuid>4d6adb3b-41b1-4a1d-8a6b-f4893f090d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
