<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_radioSexo</name>
   <tag></tag>
   <elementGuidId>a423ecf5-1885-464e-9094-55b541dc22fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='genero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#genero</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#genero >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fa88687-9015-4b91-b255-b7ab8a4cc158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bee35ba0-e3ed-475b-958b-743054dc0751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genero</value>
      <webElementGuid>4013c5eb-82c4-41e9-be34-34908dd3dc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genero</value>
      <webElementGuid>e416f8c4-cc24-48d3-b447-6a57ab91f5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee9afd00-e016-4ec7-9a33-f5948952ff2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>1ec0afc1-930f-447a-bc8a-27f86e3533a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_form&quot;)/tbody[1]/tr[4]/td[1]/fieldset[@class=&quot;fieldset-matricula&quot;]/div[@class=&quot;tablas-matricula&quot;]/table[@class=&quot;tbl-matricula-1&quot;]/tbody[1]/tr[7]/td[@class=&quot;input-genero&quot;]/span[2]/input[@id=&quot;genero&quot;]</value>
      <webElementGuid>0e63de84-847e-49bf-9f33-ef94f7354198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='genero']</value>
      <webElementGuid>b72d8a39-1bda-4022-b945-005e5fb2e418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[7]/td[2]/span[2]/input</value>
      <webElementGuid>081f64f0-eb92-4ce7-8ba4-20db58a7ec03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/span[2]/input</value>
      <webElementGuid>b139bac1-95c5-4e0e-b7c7-c40198dd3c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'genero' and @id = 'genero']</value>
      <webElementGuid>6810e4f0-fa1d-4a2f-9968-933855f1d677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
