<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_checkPreKinder</name>
   <tag></tag>
   <elementGuidId>2c8cb045-cc55-4976-8099-5dc94a0a6d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_cr_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chk_cr_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_cr_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>569a0047-7163-473a-8c7b-11e51f314c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>aca135e1-4775-4884-9435-4b03fb99d56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_cr_1</value>
      <webElementGuid>9425b2f9-0dd3-4dc7-b84a-a61c9fe3d571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_cr_1&quot;)</value>
      <webElementGuid>41c9970a-35e6-4ca4-977c-4ccb707f8037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_cr_1']</value>
      <webElementGuid>7adb29df-b4de-406c-8a6c-df4cbcab8d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='repittegrd']/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>d712e1c2-8fd9-43c9-b6fb-a30fc1fa848f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>0ee98430-5a89-47f8-b0a4-d752b27bb46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_cr_1']</value>
      <webElementGuid>f6c1e961-3a3f-43fc-9dd0-4320aa9eb004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
