<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_selectTipoCorreo</name>
   <tag></tag>
   <elementGuidId>dd44f49f-14fe-4235-8e27-e6246179d334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoCorreo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipoCorreo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoCorreo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf3f34d9-0d34-48a7-bca9-031efa201cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipoCorreo</value>
      <webElementGuid>4e35c73e-a2f1-47db-9b1c-bc9f4c530c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoCorreo</value>
      <webElementGuid>0db697c7-6c86-4cf8-8a72-01d2c4a0d39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                             Personal
                                                                                                 Trabajo
                                                                                                 Organizacional
                                                                                                 Otro
                                                                                        </value>
      <webElementGuid>7e9e66d5-13fe-4516-95ce-2c89770f0af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoCorreo&quot;)</value>
      <webElementGuid>76b38a17-e573-41a0-8162-21706b4d9cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoCorreo']</value>
      <webElementGuid>13366c92-81ae-4825-828b-f609c91c01f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>bc511165-cf2e-4dfd-bde3-8afbed6443d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[19]/following::select[1]</value>
      <webElementGuid>9065359f-d837-457d-9fb4-57ab54c50766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Correo'])[1]/following::select[1]</value>
      <webElementGuid>4c453ccf-1b0a-4910-b18c-08f1608ccb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/preceding::select[1]</value>
      <webElementGuid>6d5d21c6-dfca-4a5e-b03b-221a777b4f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[20]/preceding::select[1]</value>
      <webElementGuid>ed3d4589-722b-4ce2-8691-5193d4f5a341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>27783c11-c8dc-4c00-89ea-f4f639d7267d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipoCorreo' and @id = 'tipoCorreo' and (text() = '
                                                                                             Personal
                                                                                                 Trabajo
                                                                                                 Organizacional
                                                                                                 Otro
                                                                                        ' or . = '
                                                                                             Personal
                                                                                                 Trabajo
                                                                                                 Organizacional
                                                                                                 Otro
                                                                                        ')]</value>
      <webElementGuid>77b363f0-5aad-47b2-bc80-031e896058fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
