<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_selectEstadoCivil</name>
   <tag></tag>
   <elementGuidId>c7f1f918-f3a3-447f-890a-b26a16543b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='estado_civil']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#estado_civil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#estado_civil</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>88d41afb-438b-4e1b-8ffb-ca08e2f0e289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estado_civil</value>
      <webElementGuid>d7d6e9c8-7ebb-4be8-b8d2-610cd742fe82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estado_civil</value>
      <webElementGuid>a70f695f-6848-4183-b71a-9fdb8806dc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ef8c4b5c-4133-455b-8cb2-fe4c15ca7d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                             Soltero (a)                                                
                                                                                                 Casado(a)                                                
                                                                                                 Separado(a)                                                
                                                                                                 Viudo(a)                                                
                                                                                                 Divorciado(a)                                                
                                                                                                 Conviviente Civil                                                
                                                                                        </value>
      <webElementGuid>992c5633-d841-40c2-adad-637297d31407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estado_civil&quot;)</value>
      <webElementGuid>621f15ef-e84d-4e80-aa88-36606187e9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='estado_civil']</value>
      <webElementGuid>785a334d-499b-4a40-a5be-9c2de1c7b944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[9]/td[2]/select</value>
      <webElementGuid>ba93694f-15a9-42dc-ae20-76c7a2ed915f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[9]/following::select[1]</value>
      <webElementGuid>7804cd8a-fe50-47ca-a206-e922173d1fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil'])[1]/following::select[1]</value>
      <webElementGuid>8b55db69-698e-44f0-b1a4-273501cfcad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Religión'])[1]/preceding::select[1]</value>
      <webElementGuid>327bfb44-bdea-456e-a2ea-818c2266dca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[10]/preceding::select[1]</value>
      <webElementGuid>be8789c8-ce74-4aaa-8fe1-48d206f33504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/select</value>
      <webElementGuid>09b9fbe3-5d47-4946-8920-0a9f80ae8820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'estado_civil' and @id = 'estado_civil' and (text() = '
                                                                                             Soltero (a)                                                
                                                                                                 Casado(a)                                                
                                                                                                 Separado(a)                                                
                                                                                                 Viudo(a)                                                
                                                                                                 Divorciado(a)                                                
                                                                                                 Conviviente Civil                                                
                                                                                        ' or . = '
                                                                                             Soltero (a)                                                
                                                                                                 Casado(a)                                                
                                                                                                 Separado(a)                                                
                                                                                                 Viudo(a)                                                
                                                                                                 Divorciado(a)                                                
                                                                                                 Conviviente Civil                                                
                                                                                        ')]</value>
      <webElementGuid>58c35a98-54d9-46e2-97c1-8ed61e06ba17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
