<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputdireccion</name>
   <tag></tag>
   <elementGuidId>bb64c301-69f0-4bf3-aac0-e123c040bc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='direccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#direccion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#direccion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcdb15aa-ed4e-4395-8db9-a7e3abfec1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99cd0059-3e74-4550-b79e-b95f77b9339b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>direccion</value>
      <webElementGuid>fe89795a-18ff-4e00-a741-043200e28c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direccion</value>
      <webElementGuid>91ac1c86-d8ed-4393-bfc5-5db215c7e344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>9aa26fe9-559a-49f5-ae6e-e6300247c425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PRUEBA</value>
      <webElementGuid>71cd6c48-bc6e-49cb-8f1d-ac78a44bba54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ce857388-711d-4174-bb20-a132411f7433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validadorCaracteresComillas(this.value, this.id)</value>
      <webElementGuid>015afb72-1e22-4952-8ae7-6cb2fb447107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direccion&quot;)</value>
      <webElementGuid>89d2577f-ac70-4565-bc06-701a0482fc04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='direccion']</value>
      <webElementGuid>5d1b26c5-ffe2-49a0-845d-de39b435ddcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>f6b3a5c9-e32f-4c4f-887a-06070076e075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>23bdae36-34ae-48c5-bc65-fa5655a83b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'direccion' and @id = 'direccion']</value>
      <webElementGuid>f77ad217-c279-4bf6-83cd-b52bc6b0d07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
