<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputFechaNacApo</name>
   <tag></tag>
   <elementGuidId>b455653a-a1c3-4f34-a0f6-b4114d1ed319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e_apo_nac']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_nac</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#e_apo_nac</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c03d707-b36f-40fb-9bd6-4e2fb29dd283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>de2eed39-c4d7-4a3e-bd78-fa596c64e9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7d65fe19-f89a-4cf6-9e0a-11dfeebf5e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_nac</value>
      <webElementGuid>8ceba57b-c44c-4312-a426-8b8dfb2cbf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_nac</value>
      <webElementGuid>9a5a0ead-84d6-4bfc-879b-fa51068ab7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1991-10-10</value>
      <webElementGuid>a6947a0e-217f-4f3a-9b00-8da80c1cfa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_nac&quot;)</value>
      <webElementGuid>27d7efb2-ddfb-423f-b8c3-9133d2d5a675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e_apo_nac']</value>
      <webElementGuid>ea6d818a-235f-4c96-8e53-59c5e99e1af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>f9162cbc-20f4-4c06-aa51-a5f8429cbe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>b5f443d4-cdce-421f-be93-dc8989cf0567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'e_apo_nac' and @name = 'e_apo_nac']</value>
      <webElementGuid>3d8fc4e6-19c3-4167-8aca-354742b69813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
