<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputRutApo</name>
   <tag></tag>
   <elementGuidId>dc29fa63-af6b-44ff-8914-565316dabe66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e_apo_rut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_rut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#e_apo_rut</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a634d0-3d1d-4282-b0d1-3820572e374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74b559f4-4eb5-4192-b89d-6df3c35d4c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f19f2b2-cbf4-44da-96a2-8bd5e7e22fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_rut</value>
      <webElementGuid>3d6a52f9-3a49-461a-b847-cc3655ecf244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_rut</value>
      <webElementGuid>5582072f-d6c7-40c0-a625-f22a517cbc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limpiarRut(this.value, 2,2)</value>
      <webElementGuid>7ff55169-5ba1-43fc-af5d-e1e3142a344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validarRut(this.value, 2,2)</value>
      <webElementGuid>581796b2-f2f5-4ef2-ac85-c4e2caca2abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1130026-K</value>
      <webElementGuid>7c8a8bfe-de43-4da1-a183-0179c69e207b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_rut&quot;)</value>
      <webElementGuid>306843f3-1d0d-460a-b827-8fff220bab7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e_apo_rut']</value>
      <webElementGuid>5a839b9a-c2ab-4b3c-b73c-e001acdcd725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>b65d84a9-50e3-4969-991c-27cba9f1c5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>f33ea2f5-4a34-458f-b61b-410450cef21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'e_apo_rut' and @name = 'e_apo_rut']</value>
      <webElementGuid>dbb701c5-cfdc-4252-b91e-47262fd6bd7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
