<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_checkMineduc</name>
   <tag></tag>
   <elementGuidId>340b7819-0860-415c-9292-7ee297b57f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textosMineduc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textosMineduc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#textosMineduc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f4ded7a-2ef2-4c9c-99e4-04ae834d6243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>03e957c9-3be3-4418-a0f0-c9b9e7150b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cb22f23a-5606-4282-b415-b586f97b0333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textosMineduc</value>
      <webElementGuid>99d49486-16c5-4f6b-ba46-0927958f87bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textosMineduc</value>
      <webElementGuid>61d694f5-652e-4142-969f-858cbcfea702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textosMineduc&quot;)</value>
      <webElementGuid>3aa9a8f3-283b-4136-a503-441ad84e79b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textosMineduc']</value>
      <webElementGuid>695f27e5-06ef-43e8-b0e2-fa13d87736c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form_4']/tbody/tr[3]/td[6]/input</value>
      <webElementGuid>6959f051-8536-4793-ad3f-424ac3d5be1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/input</value>
      <webElementGuid>c81ffb71-f6f9-4659-86d8-bb0a152fb95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'textosMineduc' and @id = 'textosMineduc']</value>
      <webElementGuid>4e1393b8-47d0-43d6-a434-700b42a17a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
