<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_buttonVolver</name>
   <tag></tag>
   <elementGuidId>f98400ef-501d-4b09-bf80-79e3333f8e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='boton_regresar_cabecera_menu']/button/i)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > #boton_regresar_cabecera_menu > button.button-menu-mobile.waves-effect.waves-light.btn-volver-menu > i.fa.fa-mail-reply</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>77f2da3c-239f-4e23-8f62-9bade6079694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-mail-reply</value>
      <webElementGuid>8a7d505d-5984-408c-b1b2-3c797ea6439c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alvaro&quot;)/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav navbar-nav hidden-xs&quot;]/li[3]/a[@id=&quot;boton_regresar_cabecera_menu&quot;]/button[@class=&quot;button-menu-mobile waves-effect waves-light btn-volver-menu&quot;]/i[@class=&quot;fa fa-mail-reply&quot;]</value>
      <webElementGuid>0bd13ed5-11e2-47c6-b629-96ae86c68c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='boton_regresar_cabecera_menu']/button/i)[3]</value>
      <webElementGuid>273bea26-17ae-4707-8032-b64e9dd353ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/button/i</value>
      <webElementGuid>c37004eb-3ee1-49d5-8b6e-79f446ac4bac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
