<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputApellidoMaApo</name>
   <tag></tag>
   <elementGuidId>7c10bf9c-ac34-4d83-bd5b-45c29b0c12eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e_apo_apm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_apm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#e_apo_apm</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e25f4298-ce51-4ec7-a5cf-b1494f1a6138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06e904bb-fc65-45e6-a406-ea04ad4991bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a5b0d01-203d-460b-a89a-1196d71d8d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_apm</value>
      <webElementGuid>c3ba55b2-f552-411f-9a68-5b2917c2548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_apm</value>
      <webElementGuid>c695a9b0-929e-4197-a44e-f534672ee47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PRUEBA</value>
      <webElementGuid>a5db59f4-ff6b-4931-b93a-82b0d46740ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_apm&quot;)</value>
      <webElementGuid>dc54081e-e0f8-4e91-a3a0-d73c186c2634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e_apo_apm']</value>
      <webElementGuid>1c52b418-c7ad-45ea-97f8-d8e60b8928eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>c0ead3ab-0ec3-4f51-bb60-83e2e3180317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>1eacc3ab-9245-45be-89e8-4e0905f8f879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'e_apo_apm' and @name = 'e_apo_apm']</value>
      <webElementGuid>d358535e-3f7b-41e3-b427-d457296724fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
