<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_selectParentescoApo</name>
   <tag></tag>
   <elementGuidId>7fea3f9e-d461-4ee0-ac4e-548a276a26ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='e_apo_par']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_par</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#e_apo_par</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>45e1de9e-7b90-454a-b34f-c3d6662a76d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a95fb03-b8c4-4103-9372-65ff05705411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_par</value>
      <webElementGuid>d3e5c39c-5ae9-4b82-856b-3db8e1cc7e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_par</value>
      <webElementGuid>2607a425-7d2c-4920-b32f-164c16993d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Padre
                                                Madre
                                                Abuelo(a)
                                                Hermano(a)
                                                Tio(a)
                                                Primo(a)
                                                Sin definir
                                        </value>
      <webElementGuid>269c738e-ed90-41fd-8393-b3fccbab65a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_par&quot;)</value>
      <webElementGuid>cf14a9b1-0a29-4bc0-a3a5-7d0ed55911c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e_apo_par']</value>
      <webElementGuid>d0bf461d-e95f-4f3c-b43a-5f53b2fc9c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[3]/td[5]/select</value>
      <webElementGuid>533e80e4-d6a2-49e5-bbad-f66ca9b42cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de contacto'])[3]/preceding::select[2]</value>
      <webElementGuid>5ca71e4f-a277-4811-aa48-f83caa4a6be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/table/tbody/tr[3]/td[5]/select</value>
      <webElementGuid>eddc1889-a06a-4030-8cc3-52a91fa71496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e_apo_par' and @name = 'e_apo_par' and (text() = '
                                            Padre
                                                Madre
                                                Abuelo(a)
                                                Hermano(a)
                                                Tio(a)
                                                Primo(a)
                                                Sin definir
                                        ' or . = '
                                            Padre
                                                Madre
                                                Abuelo(a)
                                                Hermano(a)
                                                Tio(a)
                                                Primo(a)
                                                Sin definir
                                        ')]</value>
      <webElementGuid>1452dd0c-776a-446f-bbdc-5a5732b94263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
