<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_check2B</name>
   <tag></tag>
   <elementGuidId>0e885e44-a198-48b8-9c2e-07d0e964f740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_cr_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chk_cr_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chk_cr_4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>247f3195-be03-4ba3-8556-967b555df316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d3631b62-02c6-4aab-add4-7d8f849215b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_cr_4</value>
      <webElementGuid>e7c3e999-05f8-42c8-8f12-889c0e98c343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_cr_4&quot;)</value>
      <webElementGuid>5a758f82-e291-423e-bd98-d56a3eb31c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_cr_4']</value>
      <webElementGuid>05a6f39b-a70b-4ce5-ae1a-a0ea52eff612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='repittegrd']/td[3]/table/tbody/tr/td[4]/input</value>
      <webElementGuid>1f84df52-c0db-4f89-9db5-cf67a3a8ff8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/table/tbody/tr/td[4]/input</value>
      <webElementGuid>872e9a36-3db5-4dc6-b926-339737779666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_cr_4']</value>
      <webElementGuid>cbb65373-5d16-434c-8def-ef66de08a8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
