<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_checkReligion</name>
   <tag></tag>
   <elementGuidId>92fe9406-a3fa-4a6c-bc24-1a13638e2696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkReligion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkReligion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkReligion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c83671c7-4eaf-4ebc-a130-757df9b06c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5eccf9e1-3d17-4280-be9f-7f5fdd6cc57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkReligion</value>
      <webElementGuid>bab69366-a3c9-481f-a19c-4a8a84c3a107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkReligion</value>
      <webElementGuid>b055ee49-0a6a-4601-a894-357ed990280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkReligion&quot;)</value>
      <webElementGuid>71bde6db-e30e-4741-a274-666c62641a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkReligion']</value>
      <webElementGuid>aadce4a6-f09a-4946-b55b-df913e711eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>87a4921e-6f46-4fd9-899c-089d12dfb5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/input</value>
      <webElementGuid>9a31cd97-c1eb-4e30-9270-9cb44cbb0b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkReligion' and @id = 'checkReligion']</value>
      <webElementGuid>e1ac4525-7c64-4644-951c-94bbca112ad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
