<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputCelularApo2</name>
   <tag></tag>
   <elementGuidId>34ccc307-395d-4aa5-b7ca-ce4d3c4d81e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e_apo_cel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e_apo_cel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Celular: +56&quot;i] >> internal:attr=[placeholder=&quot;98765432&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fae9e390-052d-48e2-a970-db55d7613ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e060cbcb-58dc-44da-8da7-a73636f172a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e_apo_cel</value>
      <webElementGuid>842bae29-c0f8-4b41-9227-19c1b12a6475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_apo_cel</value>
      <webElementGuid>72c362ea-7758-49a4-b37b-9bd07c1a533e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>98765432</value>
      <webElementGuid>93a0d21e-3061-4c1e-a768-ccea2faea38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &lt; 48) || (event.keyCode > 57)) event.returnValue = false;</value>
      <webElementGuid>3839ff7b-c6c2-4761-8748-3a8446843ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>87edd7ad-2c9d-4363-8f40-c97bf0235528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>cdd84d3f-d291-4a1a-8104-0de21f030e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>9e1df154-1136-41d3-bcfa-65693f5a3b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validarNumeros(this,5);</value>
      <webElementGuid>fccf6b5e-493b-4af5-93f0-c9b75dfdbaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_apo_cel&quot;)</value>
      <webElementGuid>28a9a210-4ad3-40ac-bd3a-e99b47c86554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e_apo_cel']</value>
      <webElementGuid>3b8f54a5-e456-4dd1-86ca-c68c0d58c975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editApoForm']/table/tbody/tr[7]/td[2]/div/div[2]/input</value>
      <webElementGuid>39dc2b62-d23c-47c6-a1eb-8e1b5d674efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/div[2]/input</value>
      <webElementGuid>e17ea45c-2d5a-4a68-a5ec-0b25fe6a6902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'e_apo_cel' and @name = 'e_apo_cel' and @placeholder = '98765432']</value>
      <webElementGuid>cff78816-f743-45c9-8afc-be5da7b47fa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
