<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputIndiqueOtro</name>
   <tag></tag>
   <elementGuidId>77d90312-2f99-4060-a73c-22489e702159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vive_otros']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vive_otros</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#vive_otros</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4053814-8dcd-47da-b05f-e5b56cf3d010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bf96a26-282b-4705-8ee4-3493fea40c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>d621b730-894e-4484-ab16-970c22d55bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vive_otros</value>
      <webElementGuid>2afbf465-53d1-42f6-aae3-fa5cbef03ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>8944f61b-7ad2-4ecf-8e7f-0680cd4d5f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vive_otros</value>
      <webElementGuid>4276d8ab-c504-485e-8785-330cee0f4a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>14e96966-b501-4dd9-8a27-b82a061b2702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vive_otros&quot;)</value>
      <webElementGuid>ccea84b0-319e-4b3b-9232-2a7c0b996a89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vive_otros']</value>
      <webElementGuid>7a9f6c3f-b987-4d4f-9a88-5146d9957367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>fdfe16b4-14b6-465e-8067-c2b0918927a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>f5448106-1997-4c59-80aa-393ef5dc4654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vive_otros' and @id = 'vive_otros']</value>
      <webElementGuid>905830b7-45c1-4b93-8a38-657b59d57c96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
