<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matricula_inputReligion</name>
   <tag></tag>
   <elementGuidId>8dd335a1-0a19-498a-929a-a37bd194a046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='religion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#religion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#religion</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1b26844-e312-46d9-9a03-5a82eb05abb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>275bdd41-dc46-4239-bab4-9a97e696de9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>religion</value>
      <webElementGuid>0e6ffa05-3147-4359-ad80-e5fe99139e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>religion</value>
      <webElementGuid>0b2026f0-2663-4213-bdcd-84a263799edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desplegable</value>
      <webElementGuid>124bc51a-8642-4d3a-b336-14c203e28028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>b81aa2a3-9473-40a6-abfe-5495bcfc61c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;religion&quot;)</value>
      <webElementGuid>8b6a12e3-bda5-402a-981a-e92987af10a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='religion']</value>
      <webElementGuid>2aa49b02-3471-4236-afce-dea8ce83ef97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_form']/tbody/tr[4]/td/fieldset/div/table/tbody/tr[11]/td[2]/input</value>
      <webElementGuid>15ccfd1d-8819-41a0-b037-88a09c082e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/input</value>
      <webElementGuid>d19188e6-3b84-4d3d-b7bc-efc92cac770f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'religion' and @id = 'religion']</value>
      <webElementGuid>594db7b2-d637-416d-b1a7-8dfe857acfb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
