<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matriculaVer_inputNumPersonasGrupoFami</name>
   <tag></tag>
   <elementGuidId>69234d82-e9c1-4459-b0eb-18634bef9a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='n_pgf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n_pgf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#n_pgf</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34782ed1-6156-476a-b35b-0e8dee3df3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>e6fb3422-c5fc-4acc-85a4-27bd335d250d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab3b369f-7247-46c9-882f-227917375c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>aba8de10-4cf5-4caf-9e33-9c1cdb9bb442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n_pgf</value>
      <webElementGuid>5aa8d026-6033-45b4-90b7-d1dab23029cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if ((event.keyCode &amp; lt; 48) || (event.keyCode &amp; gt; 57)) event.returnValue = false;</value>
      <webElementGuid>21440583-1b82-41b7-a63b-17a6f31178b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f2f7b11c-c68d-42e2-bf56-02e9f77189ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n_pgf&quot;)</value>
      <webElementGuid>3a2c41aa-e46b-4c65-9462-87d99bfd170c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='n_pgf']</value>
      <webElementGuid>0e28b6ad-7608-4131-912f-5dc37c0821c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new_tabla_apoderados']/fieldset/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>75736b6f-46fe-47fe-8f2c-8e21a85bc51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/fieldset/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>3c723626-11ad-4547-9f03-b20bfd0d3eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'n_pgf']</value>
      <webElementGuid>9a73647c-e13b-4533-8e52-51e79455aab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
