<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_ponderacionAl2</name>
   <tag></tag>
   <elementGuidId>727f8563-5c1a-44b2-9443-24785e6aaae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notaEntrada165834583']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notaEntrada165834583</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#notaEntrada165834583</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c39b7bc-4cea-440f-8242-11ae34c6a991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5926d53e-0811-4a8d-a1a5-149194319ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0606475-db3a-49d0-8e93-bff337170c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>86654ef4-fa7a-48f5-849b-3c2f1e43dda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>765e6dd0-3c33-463c-8994-1ce582999122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notasEntrada16[]</value>
      <webElementGuid>cbbb2f96-ef7f-41ad-83f8-7dc634e1acb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notaEntrada165834583</value>
      <webElementGuid>69ed4a34-ef55-4119-87d2-d64c82e36b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notas nota</value>
      <webElementGuid>3a9a0bca-72df-43cd-ae31-073468570631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-casilla</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8638d4af-5d96-4f5f-98ff-9993bbc5f7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-escala-id</name>
      <type>Main</type>
      <value>585</value>
      <webElementGuid>f429586f-4eda-479b-bbeb-6e96e1d6574d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-type</name>
      <type>Main</type>
      <value>conceptoPersonalizado1</value>
      <webElementGuid>7c3f4786-85bf-468b-95cd-c6d5b22a5244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alumno-id</name>
      <type>Main</type>
      <value>5834583</value>
      <webElementGuid>df575509-94e3-4a71-96ff-0db9ba67622c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escala-id</name>
      <type>Main</type>
      <value>412593</value>
      <webElementGuid>b4287a80-a8b6-4748-a2c0-9f4f65235ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-influye</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>63132ee9-ca0f-4278-9932-571ef3d6cae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vinculada</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1be34cb3-7c48-4544-8ce7-d3f6e2869396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getIDItemsEscala(event)</value>
      <webElementGuid>d815e283-d1d9-4900-928a-1714ba66030e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/,/g, '.')</value>
      <webElementGuid>484ee864-57bc-4c93-acac-3c88fa59fd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notaEntrada165834583&quot;)</value>
      <webElementGuid>bdfdae3e-6b6f-4f9c-b390-ed2bc205aaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/iframe__iframe2</value>
      <webElementGuid>f92b2a9b-2234-4aa5-89cb-ec5f3b48aa6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notaEntrada165834583']</value>
      <webElementGuid>6320894d-dbb6-4407-8c0c-aaeb4a564a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='alumno_5834583']/td[13]/input[2]</value>
      <webElementGuid>5ff28188-79dd-4de7-a455-eb7f460be957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[13]/input[2]</value>
      <webElementGuid>d4eb65de-e695-4679-8aa8-b811d5c5a4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notasEntrada16[]' and @id = 'notaEntrada165834583']</value>
      <webElementGuid>2e1ebc75-59f4-4e03-95ce-a3549a0e2f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
