<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_nota1al2</name>
   <tag></tag>
   <elementGuidId>cc0bd39c-6bd0-4834-858d-72c6349b80c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notaEntrada15834583']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notaEntrada15834583</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#notaEntrada15834583</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2e674bd-974a-471e-8407-46308baaf60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35b2c02e-5eb8-4c0c-b8c5-14163fc8f90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb1027ab-e2e9-41ca-b398-5f951f902734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>61c2f97d-3ba7-4c46-ac3f-4e6c554eccac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b8053140-9380-4b53-86e8-1f38c7fef0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notasEntrada1[]</value>
      <webElementGuid>01494a83-1613-44d1-9df5-e9b1f1fc554a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notaEntrada15834583</value>
      <webElementGuid>47420a57-41a0-4ed0-a47a-b9d61af4f441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notas nota</value>
      <webElementGuid>b1f3e522-6d78-4cc8-82e8-0eeac504850c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-casilla</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78ac5dbe-53bd-45df-b61e-91a4faed1fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-escala-id</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>14d09b5f-d139-46a3-abfd-feb8850164a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-type</name>
      <type>Main</type>
      <value>nota</value>
      <webElementGuid>19036b59-e571-4b04-833e-0ca0195b7df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alumno-id</name>
      <type>Main</type>
      <value>5834583</value>
      <webElementGuid>5ca7f835-01f5-4bc9-aefa-c1d6b6145e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escala-id</name>
      <type>Main</type>
      <value>5972</value>
      <webElementGuid>17b8c248-9901-4cc5-8b20-0825ed18d7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-influye</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fdf8caaa-abbf-4566-9810-b19d16cdb7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vinculada</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1585298e-4659-4340-a6ad-f6207f8b8a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getIDItemsEscala(event)</value>
      <webElementGuid>2377e450-daef-4b4c-b7f0-5c2833df3526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/,/g, '.')</value>
      <webElementGuid>0984ab45-40c6-410b-8db3-61fc5eaa91eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notaEntrada15834583&quot;)</value>
      <webElementGuid>c9c6f688-293d-45c3-99c6-052b56f69051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/iframe__iframe2</value>
      <webElementGuid>c1dc8464-2c98-4f4f-a2a5-4141778ac308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notaEntrada15834583']</value>
      <webElementGuid>5437cbba-bce9-442d-8675-2563d7e8f99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='alumno_5834583']/td[3]/input[2]</value>
      <webElementGuid>63615f2b-31a1-4018-a85c-0f3daa60beea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/input[2]</value>
      <webElementGuid>09111d38-1b5b-42ff-98b4-378f32dbbe96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notasEntrada1[]' and @id = 'notaEntrada15834583']</value>
      <webElementGuid>cfffc0af-96c8-4bc6-ab15-9165d33a9178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
