<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_nota1al1</name>
   <tag></tag>
   <elementGuidId>1492ccb9-701d-4a50-8c4f-7eb384f92d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notaEntrada15843577']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notaEntrada15843577</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#notaEntrada15843577</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1d86f0f-5f83-4ff5-b339-8ee70cd1cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d2fa5c2-9fbb-4251-ae11-7b6f26d0b96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d1e42a6-7c3f-4c6d-9ffd-546add9990ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc8f9696-49c8-48ee-84f7-21eb15af038a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>ec33b190-0536-454c-9b14-f03b9f3bc8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notasEntrada1[]</value>
      <webElementGuid>99c41f4f-431f-4f15-9e26-5c94d6671825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notaEntrada15843577</value>
      <webElementGuid>8d2b0013-bc25-4f2b-bcc8-7f1ac00ca80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notas nota</value>
      <webElementGuid>0991547f-f409-4396-9695-e2fd3edf4d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-casilla</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d1cd8fb-79ec-4c2b-9505-9674d700a4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-escala-id</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>6f3ac21b-416e-4419-8c09-efa521ac0969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-type</name>
      <type>Main</type>
      <value>nota</value>
      <webElementGuid>4c64e841-515a-4ab3-bd3c-d1d74534e2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alumno-id</name>
      <type>Main</type>
      <value>5843577</value>
      <webElementGuid>840c083a-dd33-4760-a783-ec04c80d2b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escala-id</name>
      <type>Main</type>
      <value>5972</value>
      <webElementGuid>b060e0c2-3a05-4cca-9d81-e58cde6f926e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-influye</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>553c1ae1-c58f-4757-81f5-e90cee946a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vinculada</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a1bfbcc-bd06-4390-97c5-3268382bcee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getIDItemsEscala(event)</value>
      <webElementGuid>5677765a-6ed9-493b-af04-95bbb62a09e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/,/g, '.')</value>
      <webElementGuid>cebe61e1-c3e7-49ce-a10c-b93d8780c10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notaEntrada15843577&quot;)</value>
      <webElementGuid>5dba3b8a-6e26-4bf1-878f-608175d2bd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/iframe__iframe2</value>
      <webElementGuid>72b0c54d-a5d5-4749-aea0-22e3a18f7162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notaEntrada15843577']</value>
      <webElementGuid>dcb69b3a-42ee-4ba5-8a44-9b89a34ae38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='alumno_5843577']/td[3]/input[2]</value>
      <webElementGuid>29140423-ff41-491c-a135-389ab9236c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/input[2]</value>
      <webElementGuid>a50bb8d7-36eb-4c16-a78c-8b5b9edeb61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notasEntrada1[]' and @id = 'notaEntrada15843577']</value>
      <webElementGuid>7e361662-91eb-4c37-a40a-6f825b822014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
