<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_selectCurso (1)</name>
   <tag></tag>
   <elementGuidId>96d1e3c3-6134-48d5-93a9-335cd19f76ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cursos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cursos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cursos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b25f2a71-16d2-4029-a01d-99052dc07994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>0376f07b-ea47-40e7-af5a-c9ee18e722a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef554807-f73f-4d43-b4a5-69082234be52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cargarAsignaturas(this.value, 22, 0, 0, 0)</value>
      <webElementGuid>4c9f1311-4dec-472d-9b41-1da7b608a832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A</value>
      <webElementGuid>1dc1f6b4-07ac-42e4-8c27-b8059ef70675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursos&quot;)</value>
      <webElementGuid>a4016326-85cb-4a36-b5bb-35a46bd94fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/ifraime_notas</value>
      <webElementGuid>2f1757b8-cf7e-4c74-9f38-9d4040c12aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cursos']</value>
      <webElementGuid>71a1785d-070d-4e15-84c1-47e5d6d5ef3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/select</value>
      <webElementGuid>6a16184f-bce8-4ba9-b9bf-d5c724942b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::select[1]</value>
      <webElementGuid>89f52779-8ecb-42d4-97a6-51fc7da36521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año:'])[1]/following::select[2]</value>
      <webElementGuid>52d6b8ea-776d-43ce-b6f0-c526c5904b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignatura:'])[1]/preceding::select[1]</value>
      <webElementGuid>24eb9c52-5dbb-49e8-9a13-ffe858940459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Período:'])[1]/preceding::select[2]</value>
      <webElementGuid>8b415f93-d643-42c0-a600-81362ddfda96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>a8532b38-59e9-4166-8342-6447083dd479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cursos' and (text() = 'Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A' or . = 'Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A')]</value>
      <webElementGuid>79aaf50a-48f4-4e36-9bb9-4f604fc224ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
