<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_nota2al2</name>
   <tag></tag>
   <elementGuidId>cdc3f6a8-561a-4ed0-9be1-7489ad5ee5cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notaEntrada25834583']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notaEntrada25834583</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#notaEntrada25834583</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90a16c1d-4a74-4505-86ec-df569d72714d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4dbe6c14-6cb2-4ae3-a24e-22c1e573a7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9beee5fc-911b-4883-87e2-74e353f9028c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9dafd97d-e23e-4f13-84f8-07736fb7ced3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>144d8045-0f7c-478b-888f-c16bb90e1ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notasEntrada2[]</value>
      <webElementGuid>21699a64-c54a-41ab-90d0-64653c1ef400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notaEntrada25834583</value>
      <webElementGuid>a95bbc2b-f1dc-4c01-ad60-15db67ac01a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notas nota</value>
      <webElementGuid>ac234898-3939-48c7-9656-8aa5176a7340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-casilla</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2b585b9b-af72-41c9-bb46-278fdb857cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-escala-id</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>36648868-562f-4248-ba5c-97b220a78e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-type</name>
      <type>Main</type>
      <value>nota</value>
      <webElementGuid>6cda6972-7aff-4a68-afd9-9c84530f3f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alumno-id</name>
      <type>Main</type>
      <value>5834583</value>
      <webElementGuid>9adceef9-b7c6-441a-9e67-87671e3073e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escala-id</name>
      <type>Main</type>
      <value>5972</value>
      <webElementGuid>12ddea1b-a9b7-4b10-ab2a-756fff629e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-influye</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dd5d4740-0e70-410e-a882-c15de999f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vinculada</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2578cc42-aafe-4666-a796-6b6f4452258a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getIDItemsEscala(event)</value>
      <webElementGuid>eac87501-73af-41c1-af7a-0aa6765a9d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/,/g, '.')</value>
      <webElementGuid>6dd93510-3355-4936-a2b1-3b5ef75eb0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notaEntrada25834583&quot;)</value>
      <webElementGuid>1f03d8d6-9359-4272-80f0-ddc9f7def11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/iframe__iframe2</value>
      <webElementGuid>1dd82977-d20c-473d-9a35-9568b4924293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notaEntrada25834583']</value>
      <webElementGuid>d47f06f4-8d1a-41d4-9487-6f27719b7d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='alumno_5834583']/td[4]/input[2]</value>
      <webElementGuid>d3c7b901-4827-41e1-9765-48a7bea525ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input[2]</value>
      <webElementGuid>58de2703-10e5-4f64-aaf9-a69c49191db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notasEntrada2[]' and @id = 'notaEntrada25834583']</value>
      <webElementGuid>46a5adbf-ffad-4b77-ae31-f0bbbee3d3e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
