<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_selectCurso</name>
   <tag></tag>
   <elementGuidId>4f353647-f36a-438c-8cd0-33b3f60f67ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cursos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cursos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cursos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7315e60-6946-44e6-ad23-3bf8ac489a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>78b783ef-391b-48ee-a05c-b2b8081d0a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3139da5a-3486-44c4-9b8e-efe363b25485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cargarAsignaturas(this.value, 22, 0, 0, 0)</value>
      <webElementGuid>f03995bb-ff4b-4dd0-8dd1-d990d524008d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A</value>
      <webElementGuid>79408ad8-d92e-48c6-ba84-b9d6c7b390c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursos&quot;)</value>
      <webElementGuid>30646fec-eb55-41ae-b1c8-38489f1ea056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/ifraime_notas</value>
      <webElementGuid>4f95cd4c-fbf5-4071-a16d-b951b66e4989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cursos']</value>
      <webElementGuid>3e4703ee-b5a1-4599-a903-e07aed0d998d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/select</value>
      <webElementGuid>bfd70994-7e12-4fcc-86ad-8c70f081df7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::select[1]</value>
      <webElementGuid>d18ddfb0-8675-4bc9-abc5-123ea7666104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año:'])[1]/following::select[2]</value>
      <webElementGuid>00346287-fa7d-471f-8c8f-42f4b6aa6116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignatura:'])[1]/preceding::select[1]</value>
      <webElementGuid>4cd0c3db-e63b-42d4-9f0b-d4b2c300ddb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Período:'])[1]/preceding::select[2]</value>
      <webElementGuid>16f01096-6d18-47f1-8503-cc2645a22c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>35a21fac-a651-4b72-b036-bf67c451f0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cursos' and (text() = 'Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A' or . = 'Seleccione CursoTransicion A Pre Kinder APre Kinder AKinder Aprimero basico t APrimero Básico Bprimero basico primero a22 MSegundo Básico ASegundo Básico BTercero Básico ATercero Básico BTercero Básico CCuarto Básico ACuarto básico BCuarto Básico CQuinto Básico A Quinto Básico BSexto Básico ASexto Basico BSexto Básico CSexto Básico CSexto Básico CSexto Básico CSéptimo Básico ASéptimo Básico BOctavo Basico AOctavo Básico BPrimero Medio APrimero Medio BPrimero Medio C´Primero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPrimero Medio CPRIMERO MEDIO CSegundo Medio ATercero Medio ATercero Medio BIII° medio Cpráctica mecánicacuarto medio B leCuarto Medio ANIvel : 7°- 8° ANivel 1: 1º y 2º Medio ANivel 2: 3 y 4  ANivel 2: 3º Medio T-P ANivel 3: 4º Medio T-P A')]</value>
      <webElementGuid>a5a5c728-a82c-4dce-9e6a-19b7ae1c1b6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
