<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_notas_ponderacionAl1</name>
   <tag></tag>
   <elementGuidId>16beca89-9a2a-42cd-b764-251f9686da6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notaEntrada165843577']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notaEntrada165843577</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#notaEntrada165843577</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>017fa24f-4cb2-4904-ab05-9fb67fa87aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc0de491-ea06-4d44-af84-667e36b5aaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f49f694-b012-4e84-934b-7509664d5a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d673396b-595e-4e06-a9fe-0744130a4ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>72185fda-d9d3-4324-b2ac-5ea2706eff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notasEntrada16[]</value>
      <webElementGuid>6c9d6324-01e8-4123-992f-5338139eea21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notaEntrada165843577</value>
      <webElementGuid>a67e7a0d-ea6a-4ae4-beed-a66d17d0247b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notas nota</value>
      <webElementGuid>35693b39-24c9-470c-9187-f0768d80a19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-casilla</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>df67f8f4-5af7-412b-b4ed-96edb67ee379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-escala-id</name>
      <type>Main</type>
      <value>585</value>
      <webElementGuid>c056a39f-61be-4fa5-868b-01f62e8a9aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nota-type</name>
      <type>Main</type>
      <value>conceptoPersonalizado1</value>
      <webElementGuid>3d4b7151-b1f9-4642-a0bd-613600b6714a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alumno-id</name>
      <type>Main</type>
      <value>5843577</value>
      <webElementGuid>ae7b1b2f-4a83-47d9-8d4f-1713c8679348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escala-id</name>
      <type>Main</type>
      <value>412593</value>
      <webElementGuid>b7eb96fe-91a7-48e8-b92f-92b82e65d022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-influye</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>099502c4-f6b4-4756-a9ef-6064e561c768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vinculada</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17e8fa30-8e27-4789-a940-40a39d9b0d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getIDItemsEscala(event)</value>
      <webElementGuid>703e211d-d592-426a-acea-dc0ab0a7cd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/,/g, '.')</value>
      <webElementGuid>c7558d09-18c2-43ac-b76e-aa800b56c428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notaEntrada165843577&quot;)</value>
      <webElementGuid>3ccd79f1-f70c-4965-92e3-780c22aca3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_libroDigital_notas/iframe__iframe2</value>
      <webElementGuid>9132edd0-16ba-44cd-9901-fcaee0af3291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notaEntrada165843577']</value>
      <webElementGuid>47930c7f-367e-4b89-a033-4b28f2673fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='alumno_5843577']/td[13]/input[2]</value>
      <webElementGuid>b9b35c96-0b51-4dcb-ac48-1750595d4a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[13]/input[2]</value>
      <webElementGuid>d7df5638-745b-4e78-b49b-427d949b09d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notasEntrada16[]' and @id = 'notaEntrada165843577']</value>
      <webElementGuid>836982d7-2176-4fc8-91bc-0041a9e8576c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
