<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_libroClases_labelIndiceAsignatura</name>
   <tag></tag>
   <elementGuidId>5cc930c6-fb04-4b42-bee1-ea856d7ce9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='seal'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#seal >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bc4a5c6-2cfa-4614-aee8-24cf197e7f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seal</value>
      <webElementGuid>b807aedd-333d-4d32-8dbe-c5db1068f0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pageRight-margin</value>
      <webElementGuid>32c15889-8533-4716-a499-aa173d211da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ÍNDICE DE ASIGNATURAS ENSEÑANZAS  Enseñanza Básica  N° Asignatura Profesor 1   Orientación  Fabiola Durán, Pedro Córdova 2   Matemática  Fabiola Durán 3   Lenguaje y Comunicación  Fabiola Durán, Nicolas Bustos, Katherine Alejandra Cerda, Rachel Bushell 4   Ciencias Naturales  Fabiola Durán, Pedro Córdova 5   Historia, Geografía y Ciencias Sociales   Fabiola Durán, Pedro Córdova 6   Tecnología  Fabiola Durán, Pedro Córdova 7   Artes Visuales  Fabiola Durán, Pedro Córdova 8   Educación Física y Salud  Pedro Córdova 9   Música  Pedro Córdova 10   Idioma Extranjero: Inglés  Pedro Córdova 11   Religión Católica BB.CC.2020  Pedro Córdova </value>
      <webElementGuid>f9d35d30-2dca-4c45-aca6-1bb6bbff6eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;classbook&quot;)/div[@class=&quot;bb-bookblock bb-vertical&quot;]/div[@class=&quot;bb-item&quot;]/div[@id=&quot;seal&quot;]</value>
      <webElementGuid>ceee9462-7603-47af-af22-d6feb414a038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='seal'])[4]</value>
      <webElementGuid>4ae9cb48-1b1e-4dac-b56a-4372ab92714c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='classbook']/div/div[3]/div[2]</value>
      <webElementGuid>fb432732-ebe4-40ee-9897-beab1bef3d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tesorero'])[1]/following::div[1]</value>
      <webElementGuid>401d33d8-3ad7-43bb-84ed-40954d0f5470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secretario'])[1]/following::div[1]</value>
      <webElementGuid>acb5a054-8cd7-4f76-a553-66b12e4c9717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>7b525d7c-689a-4364-a7ab-c7368149440c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'seal' and (text() = ' ÍNDICE DE ASIGNATURAS ENSEÑANZAS  Enseñanza Básica  N° Asignatura Profesor 1   Orientación  Fabiola Durán, Pedro Córdova 2   Matemática  Fabiola Durán 3   Lenguaje y Comunicación  Fabiola Durán, Nicolas Bustos, Katherine Alejandra Cerda, Rachel Bushell 4   Ciencias Naturales  Fabiola Durán, Pedro Córdova 5   Historia, Geografía y Ciencias Sociales   Fabiola Durán, Pedro Córdova 6   Tecnología  Fabiola Durán, Pedro Córdova 7   Artes Visuales  Fabiola Durán, Pedro Córdova 8   Educación Física y Salud  Pedro Córdova 9   Música  Pedro Córdova 10   Idioma Extranjero: Inglés  Pedro Córdova 11   Religión Católica BB.CC.2020  Pedro Córdova ' or . = ' ÍNDICE DE ASIGNATURAS ENSEÑANZAS  Enseñanza Básica  N° Asignatura Profesor 1   Orientación  Fabiola Durán, Pedro Córdova 2   Matemática  Fabiola Durán 3   Lenguaje y Comunicación  Fabiola Durán, Nicolas Bustos, Katherine Alejandra Cerda, Rachel Bushell 4   Ciencias Naturales  Fabiola Durán, Pedro Córdova 5   Historia, Geografía y Ciencias Sociales   Fabiola Durán, Pedro Córdova 6   Tecnología  Fabiola Durán, Pedro Córdova 7   Artes Visuales  Fabiola Durán, Pedro Córdova 8   Educación Física y Salud  Pedro Córdova 9   Música  Pedro Córdova 10   Idioma Extranjero: Inglés  Pedro Córdova 11   Religión Católica BB.CC.2020  Pedro Córdova ')]</value>
      <webElementGuid>5b84e315-40a3-4bf4-9756-198dbe3857c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
