<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_libroClases_menuLateral_buttonPersonalizar</name>
   <tag></tag>
   <elementGuidId>8b0a7027-54e4-4e1d-b2f6-b31c829f0bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.personalizar-list > div.vs-sidebar--item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Portada'])[1]/following::a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;editPersonalizar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>068faad8-ae9b-490f-ae4d-11daa6f1f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>99f9c0e5-cb5a-4578-973e-4b6b7a16cd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>editPersonalizar</value>
      <webElementGuid>7ff87662-7e5b-4afe-9901-225ca6cc9159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;supports preserve3d csstransforms csstransforms3d csstransitions csstransformspreserve3d vuesax-app-is-ltr&quot;]/body[1]/div[@class=&quot;vs-content-sidebar&quot;]/div[@class=&quot;vs-sidebar vs-sidebar-primary&quot;]/div[@class=&quot;vs-sidebar--items&quot;]/ul[@class=&quot;menu-list&quot;]/li[@class=&quot;list-internos&quot;]/a[@class=&quot;personalizar-list&quot;]/div[@class=&quot;vs-sidebar--item&quot;]/a[1]</value>
      <webElementGuid>fa8a8b55-4aa5-4044-9514-fcc9e5ec7bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portada'])[1]/following::a[2]</value>
      <webElementGuid>e082f0fe-4fc2-48bc-9e5e-6b66afceda02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='book'])[1]/following::a[2]</value>
      <webElementGuid>22675f32-d303-44b3-8420-db8d9df58e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>b150e4e9-8306-47cf-af94-5a860d4fa333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div/a</value>
      <webElementGuid>f23efa5b-84ef-489b-95b2-32bb8d3f85cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'editPersonalizar' or . = 'editPersonalizar')]</value>
      <webElementGuid>c384debd-24b0-4654-857f-34a3e38f2ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
