<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_libroClases_menuLateral_buttonIndice</name>
   <tag></tag>
   <elementGuidId>1878aef3-d744-4073-8d41-331f39e01c92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar'])[1]/following::a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;assignmentÍndice&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f87ee8a0-3921-4c4b-aec3-bcf39373f492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1a576eb4-706e-4396-8b08-bbbe27c40dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>assignmentÍndice</value>
      <webElementGuid>5db39dca-be32-43f6-9117-91043a8100d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;supports preserve3d csstransforms csstransforms3d csstransitions csstransformspreserve3d vuesax-app-is-ltr&quot;]/body[1]/div[@class=&quot;vs-content-sidebar&quot;]/div[@class=&quot;vs-sidebar vs-sidebar-primary&quot;]/div[@class=&quot;vs-sidebar--items&quot;]/ul[@class=&quot;menu-list&quot;]/li[@class=&quot;list-internos&quot;]/a[1]/div[@class=&quot;vs-sidebar--item&quot;]/a[1]</value>
      <webElementGuid>dd5956f1-be7a-48c3-aa5e-1c1edeec0c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar'])[1]/following::a[2]</value>
      <webElementGuid>420964b6-cb55-44d6-9112-1205ced38f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='edit'])[1]/following::a[2]</value>
      <webElementGuid>8a8a933d-dc7f-47de-bcbb-70e346f98942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>f881f344-b357-4a7b-8d36-f2b6c2de8edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/div/a</value>
      <webElementGuid>1b39101f-2b2c-4fda-9719-e5882ebd726c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'assignmentÍndice' or . = 'assignmentÍndice')]</value>
      <webElementGuid>a09cb63a-e2d8-426b-9145-6dd0d1c08e9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
