<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_libroClases_persoButtonGuardarCol</name>
   <tag></tag>
   <elementGuidId>3a9c428d-36bd-405e-bfed-87f52c570791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Guardar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>baf66e2f-e873-4ee0-b37e-4224993d5bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18e32f4d-f549-4eec-b27f-fbc68c1d44d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d1e8db4-ad6a-473f-8869-32815df462ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs-component vs-button vs-button-primary vs-button-filled</value>
      <webElementGuid>ab2402c4-5cbf-4d31-802d-04fda61818fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar
                                                </value>
      <webElementGuid>74b01f58-8d21-4129-8680-cb4e3c473bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;classbook&quot;)/div[@class=&quot;bb-bookblock bb-vertical&quot;]/div[@class=&quot;bb-item&quot;]/div[@class=&quot;modal modal-cambiar-color is-active&quot;]/div[@class=&quot;modal-card text-center center&quot;]/section[@class=&quot;modal-card-body&quot;]/div[@class=&quot;coloresLibro tooltipped traslateDiv&quot;]/div[@class=&quot;contenedorBotones&quot;]/div[@class=&quot;subirImagen&quot;]/div[@class=&quot;botonesPersonalizar&quot;]/button[@class=&quot;vs-component vs-button vs-button-primary vs-button-filled&quot;]</value>
      <webElementGuid>7285b64e-b777-40bf-9743-9d114895f368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='button']</value>
      <webElementGuid>19e8a2cd-6994-467b-b935-09e9064d13b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='classbook']/div/div/div/div[2]/section/div/div/div[2]/div[2]/button</value>
      <webElementGuid>56559f06-19e1-47e2-9e42-1458a63687c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[1]/following::button[1]</value>
      <webElementGuid>94a05e92-bf58-4b91-b0d6-412ba4edda6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reestablecer'])[1]/preceding::button[1]</value>
      <webElementGuid>32202245-bf10-4521-853d-19c24d3fdbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>18d396a4-d63e-4ceb-ada8-df03d989b823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'button' and (text() = 'Guardar
                                                ' or . = 'Guardar
                                                ')]</value>
      <webElementGuid>8ecfa2be-1ff6-4155-964b-527397788bbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
