<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_libroClases__persoButttonColor</name>
   <tag></tag>
   <elementGuidId>ed46f1eb-3745-4a26-9d84-5dbb001b7db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='classbook']/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vc-saturation--black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.vc-saturation--black</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>626b13e2-1530-43e1-8e8f-461ce4c7a5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc-saturation--black</value>
      <webElementGuid>741a7551-dbce-4f30-b8dc-d8031a9ee140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;classbook&quot;)/div[@class=&quot;bb-bookblock bb-vertical&quot;]/div[@class=&quot;bb-item&quot;]/div[@class=&quot;modal modal-cambiar-color is-active&quot;]/div[@class=&quot;modal-card text-center center&quot;]/section[@class=&quot;modal-card-body&quot;]/div[@class=&quot;coloresLibro tooltipped traslateDiv&quot;]/div[@class=&quot;contenedorBotones&quot;]/div[@class=&quot;cambiarColores&quot;]/div[@class=&quot;vc-sketch&quot;]/div[@class=&quot;vc-sketch-saturation-wrap&quot;]/div[@class=&quot;vc-saturation&quot;]/div[@class=&quot;vc-saturation--black&quot;]</value>
      <webElementGuid>bd552721-271c-4a6a-b6f9-e6900ab04382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='classbook']/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>692d47d2-8a4c-4802-834b-df88e6490749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>dd55e96b-2486-4bd6-8f2d-6cac9ab27f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
