<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_asistenciaApoderado_selectCurso</name>
   <tag></tag>
   <elementGuidId>f0df430b-f148-46e4-bfb4-092a9c63b1c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a08c2bed-fef6-4817-9c72-5f8c4952accd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown dropdown-trigger</value>
      <webElementGuid>d234b140-59a1-46ff-8f46-455042923665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74ad5f06-a28c-419e-b48d-76bbc283da74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b72da9f7-d369-4399-8f96-58499775605d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>select-options-10f21635-88cb-4ce2-aaec-74a8be7f2f83</value>
      <webElementGuid>eb8314a8-4633-4335-b723-5db59b83c269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s12 sep-header&quot;]/div[@class=&quot;filter&quot;]/div[@class=&quot;col s4&quot;]/div[@class=&quot;input_content&quot;]/div[@class=&quot;select-wrapper&quot;]/input[@class=&quot;select-dropdown dropdown-trigger&quot;]</value>
      <webElementGuid>3b3606e5-2280-4595-8d3a-207cee320d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_asistenciaApoderado/iframe__iframe2</value>
      <webElementGuid>bab8386d-2401-407b-838c-0478a990b6e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>382aef89-26c7-4dec-b55e-22afc7dd68a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox']/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>8b8e83ba-2b32-463c-9520-a971545026fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>046412cd-0fc4-4534-a857-d4418fa825cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>e62a3144-bc58-4869-ac04-b599be8c917b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
