<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_asistenciaApoderado_selectNivel</name>
   <tag></tag>
   <elementGuidId>d501c8d3-c21d-45f8-b193-438aee631606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.select-dropdown.dropdown-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e66d169-5b29-41f7-9dfb-492428be7dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown dropdown-trigger</value>
      <webElementGuid>b34acdc0-53a9-442c-a7f3-6e7816074a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f38e981d-50c7-4751-a4b5-c38035414170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7be9c6b-1594-4ff1-ae6e-67034d7d594b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>select-options-1187d3c3-4a60-3d65-e6c2-a842ba7276c0</value>
      <webElementGuid>e2cf9775-84ff-4072-bb06-1614ffbae121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s12 sep-header&quot;]/div[@class=&quot;filter&quot;]/div[@class=&quot;col s4&quot;]/div[@class=&quot;input_content&quot;]/div[@class=&quot;select-wrapper&quot;]/input[@class=&quot;select-dropdown dropdown-trigger&quot;]</value>
      <webElementGuid>2c1c6112-a8c3-41b3-88af-2c5c6922fbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_asistenciaApoderado/iframe__iframe2</value>
      <webElementGuid>1b0562d0-2626-4de4-be5b-e576368f4e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>72d971da-ff21-4e5f-af39-4abc7fd71b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>15d5db7e-82f3-423d-aa0c-bae7165b609a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>f41a323c-4497-4cc6-8753-60b46e03a02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>16453301-5cfd-41c6-93a9-a1b8931fa2dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
