<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_asistenciaApoderado_labelPrimeroBasico</name>
   <tag></tag>
   <elementGuidId>75aa3720-19a1-47f6-aa12-757d1ec6cda5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select-options-d16af834-6977-c4e4-4652-50b1e2b324785']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-options-d16af834-6977-c4e4-4652-50b1e2b324785 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=list >> internal:text=&quot;Primero Básico&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>acb8673c-0547-45cb-9e2e-598aeef7f23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primero Básico</value>
      <webElementGuid>e94527d1-dd41-457e-8947-d364dda73452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-options-d16af834-6977-c4e4-4652-50b1e2b324785&quot;)/span[1]</value>
      <webElementGuid>5fb189da-6bdc-4286-b1fa-551ee27b4eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_asistenciaApoderado/iframe__iframe2</value>
      <webElementGuid>7e2e9f02-4a50-474d-8761-6ec674e6d775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='select-options-d16af834-6977-c4e4-4652-50b1e2b324785']/span</value>
      <webElementGuid>b6041349-404f-4af2-b518-3f604a190cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel Medio Menor'])[1]/following::span[3]</value>
      <webElementGuid>2d0e3a4f-a6b3-4b0d-8d34-b20ebb61e74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::span[4]</value>
      <webElementGuid>d984cbe7-009b-49aa-aa5d-be486bf0f590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segundo Básico'])[1]/preceding::span[1]</value>
      <webElementGuid>b4306d4b-b3da-4613-9fac-a99f49c8493a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tercero Básico'])[1]/preceding::span[2]</value>
      <webElementGuid>d89e7e27-edd4-4670-b0e4-04166b0751be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Primero Básico']/parent::*</value>
      <webElementGuid>40d56e87-6336-4e77-9e6b-29e94c220ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span</value>
      <webElementGuid>85ca7d0e-5dcc-484b-8cb2-1e4622c94631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Primero Básico' or . = 'Primero Básico')]</value>
      <webElementGuid>c1721a12-2d57-490b-8a63-0bb27bc05e4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
