<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_asistenciaApoderado_buttonAsistenciaApoderado</name>
   <tag></tag>
   <elementGuidId>0e6ba50a-45ad-48db-ac8d-d2aea79cfe70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='asistencia_apoderado']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#asistencia_apoderado > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Asistencia apoderado&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbc848f2-33bd-439f-8b02-f81370d176cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Asistencia apoderado</value>
      <webElementGuid>9f0359fb-2af5-45eb-8e7b-6532f19a4ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asistencia_apoderado&quot;)/span[1]</value>
      <webElementGuid>9c354336-b88c-4898-8d01-5330a170b7ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='asistencia_apoderado']/span</value>
      <webElementGuid>571031ea-2e02-49dc-bb99-47ecfbcae6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[2]/preceding::span[1]</value>
      <webElementGuid>d1d47923-4683-4aa6-b3e1-a523058415bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalidad'])[2]/preceding::span[2]</value>
      <webElementGuid>7699f306-8878-42e5-987a-cff6295f56ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asistencia apoderado']/parent::*</value>
      <webElementGuid>a9194303-dabc-43a1-9d75-49628cc39c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[10]/a/span</value>
      <webElementGuid>14c78885-bd36-4e77-add4-309f6ec6975e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Asistencia apoderado' or . = ' Asistencia apoderado')]</value>
      <webElementGuid>5d8ffd46-853c-4eb1-8d4a-d2be6c01b75e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
