<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_bitacora_cuttonVer</name>
   <tag></tag>
   <elementGuidId>1aa143fd-93bc-4134-8a8d-ef7f2fa46a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//i[contains(@class,'fa fa-eye')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.fancybox > i.fa.fa-eye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1385 Anamnesis 12-02-2025 Anamnesis 0 QA Auto Ver observación Editar observación Adjuntar archivo Destacar observación Eliminar observación&quot;s] >> internal:attr=[title=&quot;Ver observación&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>837fb01b-666f-4908-b542-28e55ceea84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>b1390c4c-6a1f-4fce-a1d4-5f082a3c2002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>baa86923-02b4-444d-b6cb-1fc17add1716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr-196822&quot;)/td[8]/a[@class=&quot;fancybox&quot;]/i[@class=&quot;fa fa-eye&quot;]</value>
      <webElementGuid>6e1b7a4d-7565-4621-ab25-7df324661f6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-196822']/td[8]/a/i</value>
      <webElementGuid>841ce0eb-cf43-4512-8caa-e750f5ff4d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a/i</value>
      <webElementGuid>8a752af2-9605-463b-be9a-f62b377c6aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
