<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_buttonNotas</name>
   <tag></tag>
   <elementGuidId>dea2c462-1631-43e1-84f2-5ee48311a41c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='grillaAlumnos']/tr/td[14]/span[4]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-line-chart.x18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span:nth-child(4) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f271260a-e476-4f95-a2c7-ffdf45d77cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-line-chart x18</value>
      <webElementGuid>00dcfb7a-6ec2-4cb9-9ce3-1bbbcef0eb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04c4c586-aaa9-4059-b559-876442aceab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grillaAlumnos&quot;)/tr[1]/td[@class=&quot;ancho-herramientas&quot;]/span[@class=&quot;verTooltip&quot;]/a[1]/i[@class=&quot;fa fa-line-chart x18&quot;]</value>
      <webElementGuid>26359377-6b08-4c24-955c-93c3324cec38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='grillaAlumnos']/tr/td[14]/span[4]/a/i</value>
      <webElementGuid>eb027f8f-1bf9-449c-955e-a629e188e5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/a/i</value>
      <webElementGuid>4ee43b60-949c-4693-b0c4-2978e6dc50c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
