<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_buttonCodigoBarra</name>
   <tag></tag>
   <elementGuidId>4a33b84b-3a7f-4d91-91a3-203f915826bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='grillaAlumnos']/tr/td[14]/span[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-barcode.x18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.btn_barcode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>392a81c2-454c-492e-bcd9-8797ef968aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-barcode x18</value>
      <webElementGuid>a692c61b-bdcb-452f-8b90-c026c4b1694c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d21724ce-e05b-4767-9202-5168203d78a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grillaAlumnos&quot;)/tr[1]/td[@class=&quot;ancho-herramientas&quot;]/span[@class=&quot;verTooltip&quot;]/a[@class=&quot;btn_barcode fancybox&quot;]/i[@class=&quot;fa fa-barcode x18&quot;]</value>
      <webElementGuid>a4c759b5-35b6-4c6b-8cc5-d248fe1a3b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='grillaAlumnos']/tr/td[14]/span[3]/a/i</value>
      <webElementGuid>2bcce0dd-3caa-461f-8af4-e1296f37846d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a/i</value>
      <webElementGuid>ea361435-546c-4647-8bb5-839ab7afda0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
