<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_bitacora_buttonDestacar</name>
   <tag></tag>
   <elementGuidId>56ec333e-7397-4841-8a1d-40c850fc372f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[contains(@class,'fa fa-star')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-star</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#a-196822</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2ecd6c11-642b-4f69-afb4-c2786501fb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-star</value>
      <webElementGuid>029cabe6-ec98-4701-b384-9e41ebfbae64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86d8d44f-ef13-44c3-bf35-f44f62555aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-196822&quot;)/i[@class=&quot;fa fa-star&quot;]</value>
      <webElementGuid>79cf984e-d4ce-4587-a98b-46c099d72b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a-196822']/i</value>
      <webElementGuid>a3f94989-491b-470d-8efc-1f9f55992ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>d5763bb7-05c7-42fc-bd25-f2f08eb38e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
