<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_bitacora_buttonBloquear</name>
   <tag></tag>
   <elementGuidId>74bf1c62-c460-43d5-8fe4-16a51dcd31b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[contains(@id,'bloqueo')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bloqueo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a:nth-child(6) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>77894352-bd1e-41ab-befc-24c1f52a148d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-unlock-alt</value>
      <webElementGuid>d7a3cb22-c01f-44d7-b0d5-3bb62322f10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bloqueo</value>
      <webElementGuid>8cfa80fe-e2f1-4b0e-867d-15c37a5d7e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bloquear observación</value>
      <webElementGuid>529fbf96-8315-4a79-ae14-5a1de7ae8af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1da555ae-3f28-4664-83ad-48fd6b67b1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr-196822&quot;)/td[8]/a[6]/i[@id=&quot;bloqueo&quot;]</value>
      <webElementGuid>17c0fbe5-0d31-4e35-9829-00d1ad13e188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='bloqueo']</value>
      <webElementGuid>dfcf8924-0d03-4631-8548-c7895de4c752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr-196822']/td[8]/a[6]/i</value>
      <webElementGuid>78a02e69-6d2d-4411-b614-832b3fdda1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/i</value>
      <webElementGuid>e52ee169-aa5b-4e67-9f72-a27bee930702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'bloqueo' and @title = 'Bloquear observación']</value>
      <webElementGuid>e5d77eb0-9188-4517-81f2-d83002c6b98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
