<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_buttonRegresarVer</name>
   <tag></tag>
   <elementGuidId>63a816d0-ef49-49cf-94c2-688e5fbd9fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='boton_regresar_cabecera_menu']/button/i)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > #boton_regresar_cabecera_menu > button.button-menu-mobile.waves-effect.waves-light.btn-volver-menu > i.fa.fa-mail-reply</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bb23db3f-75c5-4252-926a-3fbb6ccb9bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-mail-reply</value>
      <webElementGuid>422bafaa-d7cc-419d-86fe-f9ea27e10359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alvaro&quot;)/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav navbar-nav hidden-xs&quot;]/li[3]/a[@id=&quot;boton_regresar_cabecera_menu&quot;]/button[@class=&quot;button-menu-mobile waves-effect waves-light btn-volver-menu&quot;]/i[@class=&quot;fa fa-mail-reply&quot;]</value>
      <webElementGuid>17302d66-cc0a-4a9c-a419-0be03ba1c3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='boton_regresar_cabecera_menu']/button/i)[3]</value>
      <webElementGuid>f5d64ffc-e39d-4612-8d1e-1ec1fa0f387b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/button/i</value>
      <webElementGuid>f42e06dd-d8cf-4f43-bef7-bec07e22f577</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
