<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_selectCurso</name>
   <tag></tag>
   <elementGuidId>619f33e0-dcd7-408a-b693-dc918d5bad1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cursos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cursos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cursos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0f7767d7-a09d-48e5-b5ef-bc6a01bacdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>077aded4-72be-4acc-8a4f-06e0cac82c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursos</value>
      <webElementGuid>130e2a45-2858-46be-b862-0d4ecb2a7be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>40b7d852-999f-4bc5-a092-3aa722607b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>generarCabeceraGrillaPrincipal(this.value, 0); cargar_detalle_fotos(); mostrar_herramientas();</value>
      <webElementGuid>f51535e0-2085-4dd3-98f1-4961a012eaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Todos los cursos (2025)primero basico t APrimero Básico BSegundo basicoSegundo Básico BTercero Básico ACuarto Básico AQUINTO ASexto Básico ASexto Basico BSéptimo Básico AOctavo Basico APrimero Medio APRIMERO MEDIO CSegundo Medio ASegundo Medio ACuarto Medio A</value>
      <webElementGuid>e9edcf35-7ac2-4feb-9286-a0ebd3a4df0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursos&quot;)</value>
      <webElementGuid>91631943-df38-46bd-8757-11541abec466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cursos']</value>
      <webElementGuid>6586fff7-e83a-46b5-a5d6-2565889e727e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div[3]/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>6cb54657-5849-4836-85cc-121c7179fcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso:'])[1]/following::select[1]</value>
      <webElementGuid>34147994-1210-4c99-8798-e7eb3defe941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto'])[1]/preceding::select[1]</value>
      <webElementGuid>7b1cf602-7fa3-4854-a96b-d71e810ea20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUT'])[1]/preceding::select[1]</value>
      <webElementGuid>c762411f-b867-4f82-92cf-82131b4db8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>2daf3066-ccea-4a56-bf7e-65242004631b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cursos' and @id = 'cursos' and (text() = ' Todos los cursos (2025)primero basico t APrimero Básico BSegundo basicoSegundo Básico BTercero Básico ACuarto Básico AQUINTO ASexto Básico ASexto Basico BSéptimo Básico AOctavo Basico APrimero Medio APRIMERO MEDIO CSegundo Medio ASegundo Medio ACuarto Medio A' or . = ' Todos los cursos (2025)primero basico t APrimero Básico BSegundo basicoSegundo Básico BTercero Básico ACuarto Básico AQUINTO ASexto Básico ASexto Basico BSéptimo Básico AOctavo Basico APrimero Medio APRIMERO MEDIO CSegundo Medio ASegundo Medio ACuarto Medio A')]</value>
      <webElementGuid>ebab8330-0ff9-4bfc-a80d-e4f966dd6315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
