<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>libroDigital_listado_labelPrioritario</name>
   <tag></tag>
   <elementGuidId>517b3115-d538-42b3-847d-938ad93ef423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datosPersonales']/div/div/table/tbody/tr[2]/td[4]/span/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;RUT : 100765213-1 Alumno prioritario : No&quot;i] >> internal:role=strong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>371f5e2b-0cf9-486b-8b95-a1c949523b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> No</value>
      <webElementGuid>39e7d275-a0cf-4266-ba1e-96b3fea4d5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datosPersonales&quot;)/div[@class=&quot;i-row&quot;]/div[@class=&quot;i-col-12 i-left&quot;]/table[1]/tbody[1]/tr[2]/td[4]/span[1]/strong[1]</value>
      <webElementGuid>de58d08a-b084-4552-94a2-7554de075868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datosPersonales']/div/div/table/tbody/tr[2]/td[4]/span/strong</value>
      <webElementGuid>ea39495e-0dc3-49c5-b516-ecee5ef7b5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': 100765213-1'])[1]/following::strong[1]</value>
      <webElementGuid>6579ae9f-6b3d-4de5-a1d9-ab8fe46a395e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': STANLEY'])[1]/preceding::strong[1]</value>
      <webElementGuid>e60858f1-8021-428d-a444-12afbc8e9215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No']/parent::*</value>
      <webElementGuid>464b5eb3-f2e3-4322-8c9a-972a1b005930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>4473c07a-65d4-4d63-b8ae-76d9db0e021b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' No' or . = ' No')]</value>
      <webElementGuid>f494448c-aeb0-4cbf-913e-6fe2ab57d28a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
